### ISSUE TITLE
spark-csv_2.11-s_2.11 not found

### ISSUE THREAD

**Issue by Lewuathe** [databricks/spark-csv#129]
My spark environment is built from master source for hadoop-2.6.
```
$ build/mvn -Pyarn -Phadoop-2.6 -Dhadoop.version=2.6.0 -DskipTests clean package 
```

I cannot find `1.2.0-s_2.11` but it's okay with only `1.2.0`. In the [README](https://github.com/databricks/spark-csv/blob/master/README.md) and [spark package](http://spark-packages.org/package/databricks/spark-csv), `1.2.0-s_2.11` looks standard way to install spark-csv. Is that correct? 
Should we install with `1.2.0` not `1.2.0-s_2.11`?

```
$ ./bin/spark-shell --packages com.databricks:spark-csv_2.11:1.2.0-s_2.11                                                                                                                                                                               22:23:07
Ivy Default Cache set to: /Users/sasakikai/.ivy2/cache
The jars for the packages stored in: /Users/sasakikai/.ivy2/jars
:: loading settings :: url = jar:file:/Users/sasakikai/spark/assembly/target/scala-2.10/spark-assembly-1.5.0-SNAPSHOT-hadoop2.6.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.databricks#spark-csv_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
        confs: [default]
:: resolution report :: resolve 1713ms :: artifacts dl 0ms
        :: modules in use:
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
        ---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
                module not found: com.databricks#spark-csv_2.11;1.2.0-s_2.11

        ==== local-m2-cache: tried

          file:/Users/sasakikai/.m2/repository/com/databricks/spark-csv_2.11/1.2.0-s_2.11/spark-csv_2.11-1.2.0-s_2.11.pom

          -- artifact com.databricks#spark-csv_2.11;1.2.0-s_2.11!spark-csv_2.11.jar:

          file:/Users/sasakikai/.m2/repository/com/databricks/spark-csv_2.11/1.2.0-s_2.11/spark-csv_2.11-1.2.0-s_2.11.jar

        ==== local-ivy-cache: tried

          /Users/sasakikai/.ivy2/local/com.databricks/spark-csv_2.11/1.2.0-s_2.11/ivys/ivy.xml

        ==== central: tried

          https://repo1.maven.org/maven2/com/databricks/spark-csv_2.11/1.2.0-s_2.11/spark-csv_2.11-1.2.0-s_2.11.pom

          -- artifact com.databricks#spark-csv_2.11;1.2.0-s_2.11!spark-csv_2.11.jar:

          https://repo1.maven.org/maven2/com/databricks/spark-csv_2.11/1.2.0-s_2.11/spark-csv_2.11-1.2.0-s_2.11.jar

        ==== spark-packages: tried

          http://dl.bintray.com/spark-packages/maven/com/databricks/spark-csv_2.11/1.2.0-s_2.11/spark-csv_2.11-1.2.0-s_2.11.pom

          -- artifact com.databricks#spark-csv_2.11;1.2.0-s_2.11!spark-csv_2.11.jar:

          http://dl.bintray.com/spark-packages/maven/com/databricks/spark-csv_2.11/1.2.0-s_2.11/spark-csv_2.11-1.2.0-s_2.11.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: com.databricks#spark-csv_2.11;1.2.0-s_2.11: not found

                ::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: com.databricks#spark-csv_2.11;1.2.0-s_2.11: not found]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1009)
        at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:286)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:153)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

**Comment by brkyvz** [comment]
Yes, please use `com.databricks:spark-csv_2.11:1.2.0`. It's an issue on Spark Packages side, and it will be fixed.

**Comment by JoshRosen** [comment]
Given that this is a Spark Packages issue, I'm going to close this issue. Please re-open if there are any actions to take in `spark-csv` itself.
