### ISSUE TITLE
DataFrames created using CSV reader failing join

### ISSUE THREAD

**Issue by sfelsheim** [databricks/spark-csv#142]
I have two simple CSV files, address and people, with the following contents.

addrId,city,state,zip
0,sometown,wi,4444
2,bedrock,il,1111

first,last,addrId
your,mom,1
fred,flintstone,2

I load them into DataFrames using:

    DataFrame pDf = sqlContext.read().format("com.databricks.spark.csv")
                .option("header", "true")
                .option("inferSchema", "false")
                .option("delimiter", ",")
                .load("/Users/sfelsheim/data/people.csv");

        DataFrame aDf = sqlContext.read().format("com.databricks.spark.csv")
                .option("header", "true")
                .option("inferSchema", "false")
                .option("delimiter", ",")
                .load("/Users/sfelsheim/data/address.csv");

When I try to join pDf and aDf like this:

        DataFrame joined = aDf.join(pDf,
                aDf.col("addrId").equalTo(pDf.col("addrId")));

if fails with this exception:

    Exception in thread "main" org.apache.spark.sql.AnalysisException: Cannot resolve column name     "addrId" among (﻿addrId, city, state, zip);
	at org.apache.spark.sql.DataFrame$$anonfun$resolve$1.apply(DataFrame.scala:159)
	at org.apache.spark.sql.DataFrame$$anonfun$resolve$1.apply(DataFrame.scala:159)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.DataFrame.resolve(DataFrame.scala:158)
	at org.apache.spark.sql.DataFrame.col(DataFrame.scala:558)
	at dw.dataflow.TestJoin.main(TestJoin.java:81)

If I create DataFrames using the exact same two CSV files like this:

    JavaRDD<Person> people = context.textFile("/Users/sfelsheim/data/people.csv").map(
                new Function<String, Person>() {
                    public Person call(String line) throws Exception {
                        String[] parts = line.split(",");

                        Person person = new Person();
                        person.setFirst(parts[0]);
                        person.setLast(parts[1]);
                        person.setAddrId(parts[2]);

                        return person;
                    }
                });

and

      JavaRDD<Address> address = context.textFile("/Users/sfelsheim/data/address.csv").map(
                new Function<String, Address>() {
                    public Address call(String line) throws Exception {
                        String[] parts = line.split(",");

                        Address addr = new Address();
                        addr.setAddrId(parts[0]);
                        addr.setCity(parts[1]);
                        addr.setState(parts[2]);
                        addr.setZip(parts[3]);

                        return addr;
                    }
                });

The join I mentioned above works as I would expect.

Any ideas?

Thanks

Steve

**Comment by sfelsheim** [comment]
One other note.  In application I am working that this problem came from, I am writing the DataFrame created by the CSV reader to HDFS in Parquet format.  This problem persists even when I read the data back into DataFrames from Parquet.

**Comment by JoshRosen** [comment]
Is there a leading space in `address.csv`? I'm wondering if the column name has an extra space character in it, since the spacing in `Cannot resolve column name     "addrId" among (﻿addrId, city, state, zip);` looks funny to me.

**Comment by JoshRosen** [comment]
Just found #96, so I wonder if spaces could be the issue.

**Comment by sfelsheim** [comment]
No, no leading spaces.  Proved this to myself using this code, which works fine.

JavaRDD<Address> address = context.textFile("/Users/sfelsheim/data/address.csv").map(
            new Function<String, Address>() {
                public Address call(String line) throws Exception {
                    String[] parts = line.split(",");

                    Address addr = new Address();
                    addr.setAddrId(parts[0]);
                    addr.setCity(parts[1]);
                    addr.setState(parts[2]);
                    addr.setZip(parts[3]);

                    return addr;
                }
            });
 DataFrame aDf = sqlContext.createDataFrame(address, Address.class);

From:  Josh Rosen
Reply-To:  databricks/spark-csv
Date:  Tuesday, September 8, 2015 at 8:51 PM
To:  databricks/spark-csv
Cc:  Steve Felsheim
Subject:  Re: [spark-csv] DataFrames created using CSV reader failing join (#142)


Is there a leading space in address.csv? I'm wondering if the column name has an extra space character in it, since the spacing in Cannot resolve column name     "addrId" among (﻿addrId, city, state, zip); looks funny to me.

**Comment by sfelsheim** [comment]
The problem seems to be that the CSV was encoded as UTF-8 with BOM.  When I changed the CSV (address.csv) to UTF-8 (no BOM), then it works fine.

Would you like to me to delete issue #142 and create a new one for BOM handling?

Thanks

Steve

From:  Josh Rosen
Reply-To:  databricks/spark-csv
Date:  Tuesday, September 8, 2015 at 8:51 PM
To:  databricks/spark-csv
Cc:  Steve Felsheim
Subject:  Re: [spark-csv] DataFrames created using CSV reader failing join (#142)


Is there a leading space in address.csv? I'm wondering if the column name has an extra space character in it, since the spacing in Cannot resolve column name     "addrId" among (﻿addrId, city, state, zip); looks funny to me.

**Comment by JoshRosen** [comment]
I think that we can repurpose #142 to handle this. Otherwise, feel free to open a new issue and close #142.

**Comment by joshlemer** [comment]
+1

**Comment by umairsheikh** [comment]
So this issue is still there with Scala 2.11.7 and Spark-Core 1.5.2 , databricks 1.3.0.

**Comment by NotYoCheese** [comment]
Just hit this with databricks 1.4, Scala 2.11, spark 1.6.2

**Comment by NoahMarconi** [comment]
Same for Scala 2.11 on Spark 2.0.0 using databricks community edition.

Anyone know of a workaround? I don't have control over the originating csv files so they'll keep coming in this format.

**Comment by HyukjinKwon** [comment]
Not clean and perfect and not even tested but I think this might be a workaround.

```scala
val UTF8_BOM = "..."
val path = "..."
val csvRdd = sparkContext.textFile(path)
val droppedCsvRDD = csvRdd.mapPartitionsWithIndex { (idx, iter) =>
  if (idx == 0) {
    var shouldStripBom = true
    iter.map { line =>
      if (bomSkipped) {
        if (line.startsWith(UTF8_BOM)) {
          // Here, strip BOM.
          line.substring(1);
          bomSkipped = false
        }
      } else {
        line
      }
    }
  } else {
    iter
  }
}
val csvDf = new CsvParser().csvRdd(sqlContext, droppedCsvRDD)
```

**Comment by kyprifog** [comment]
+1
