### ISSUE TITLE
Assembly build not working

### ISSUE THREAD

**Issue by syepes** [databricks/spark-csv#150]
Hello,

I am trying to build spark-csv with all its dependencies, but I am getting the following error.
Anyone know what is causing this issue?

```
# sbt/sbt +assembly
...
[info] ScalaTest
[info] Run completed in 37 seconds, 970 milliseconds.
[info] Total number of tests run: 93
[info] Suites: completed 6, aborted 0
[info] Tests: succeeded 93, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 96, Failed 0, Errors 0, Passed 96
java.lang.RuntimeException: Please add any Spark dependencies by supplying the sparkVersion and sparkComponents. Please remove: org.apache.spark:spark-core:1.5.0:test
        at scala.sys.package$.error(package.scala:27)
        at sbtsparkpackage.SparkPackagePlugin$$anonfun$12$$anonfun$apply$1.apply(SparkPackagePlugin.scala:107)
        at sbtsparkpackage.SparkPackagePlugin$$anonfun$12$$anonfun$apply$1.apply(SparkPackagePlugin.scala:95)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbtsparkpackage.SparkPackagePlugin$$anonfun$12.apply(SparkPackagePlugin.scala:95)
        at sbtsparkpackage.SparkPackagePlugin$$anonfun$12.apply(SparkPackagePlugin.scala:93)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:assembly::assembledMappings) Please add any Spark dependencies by supplying the sparkVersion and sparkComponents. Please remove: org.apache.spark:spark-core:1.5.0:test
[error] Total time: 52 s, completed Sep 17, 2015 7:04:07 PM
```

Thanks for any help,
Sebastian

**Comment by brkyvz** [comment]
Could you please add
spIgnoreProvided := true
to build.sbt please?
On Sep 17, 2015 10:09 AM, "Sebastian YEPES" <notifications@github.com>
wrote:

Hello,

I am trying to build spark-csv with all its dependencies, but I am getting
the following error.
Anyone know what is causing this issue?

# sbt/sbt +assembly
...
[info] ScalaTest
[info] Run completed in 37 seconds, 970 milliseconds.
[info] Total number of tests run: 93
[info] Suites: completed 6, aborted 0
[info] Tests: succeeded 93, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 96, Failed 0, Errors 0, Passed 96
java.lang.RuntimeException: Please add any Spark dependencies by
supplying the sparkVersion and sparkComponents. Please remove:
org.apache.spark:spark-core:1.5.0:test
        at scala.sys.package$.error(package.scala:27)
        at sbtsparkpackage.SparkPackagePlugin$$anonfun$12$$anonfun$apply$1.apply(SparkPackagePlugin.scala:107)
        at sbtsparkpackage.SparkPackagePlugin$$anonfun$12$$anonfun$apply$1.apply(SparkPackagePlugin.scala:95)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbtsparkpackage.SparkPackagePlugin$$anonfun$12.apply(SparkPackagePlugin.scala:95)
        at sbtsparkpackage.SparkPackagePlugin$$anonfun$12.apply(SparkPackagePlugin.scala:93)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:assembly::assembledMappings) Please add any Spark
dependencies by supplying the sparkVersion and sparkComponents. Please
remove: org.apache.spark:spark-core:1.5.0:test
[error] Total time: 52 s, completed Sep 17, 2015 7:04:07 PM

Thanks for any help,
Sebastian

—
Reply to this email directly or view it on GitHub
<https://github.com/databricks/spark-csv/issues/150>.

**Comment by syepes** [comment]
@brkyvz Thanks that did the trick ;-)

**Comment by JoshRosen** [comment]
In order to improve the out-of-the-box experience for users, I think that we should check this change into the repo and should test the assembly step in Travis. I'll submit a PR now to do this.
