### ISSUE TITLE
Failed to load class for data source: com.databricks.spark.csv

### ISSUE THREAD

**Issue by schmee** [databricks/spark-csv#156]
I'm trying to run the example code from the readme, with slight modifications:

```
import org.apache.spark.SparkContext
import org.apache.spark.SparkConf
import org.apache.spark.sql.SQLContext

object Test {
  def main args: Array[String]) {
    val conf = new SparkConf().setAppName("Test")
    val sc = new SparkContext(conf)
    val sqlContext = new SQLContext(sc)
    val df = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").load("cars.csv")
    df.select("year", "model").write.format("com.databricks.spark.csv").save("newcars.csv")
  }
}
```

The file is then packaged with `sbt package` with this .sbt file:

```
name := "Test"

version := "1.0"

scalaVersion := "2.11.7"

libraryDependencies += "org.apache.spark" %% "spark-core" % "1.5.1"
libraryDependencies += "org.apache.spark" %% "spark-hive" % "1.5.1"
libraryDependencies += "com.databricks" %% "spark-csv" % "1.2.0"
```

Here's what happens:

```
➜  bin  ./spark-submit --class Test ~/programming/scala/test/target/scala-2.11/test_2.11-1.0.jar
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
15/10/02 11:51:37 INFO SparkContext: Running Spark version 1.5.1
15/10/02 11:51:37 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/10/02 11:51:38 INFO SecurityManager: Changing view acls to: john
15/10/02 11:51:38 INFO SecurityManager: Changing modify acls to: john
15/10/02 11:51:38 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(john); users with modify permissions: Set(john)
15/10/02 11:51:38 INFO Slf4jLogger: Slf4jLogger started
15/10/02 11:51:38 INFO Remoting: Starting remoting
15/10/02 11:51:39 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriver@172.30.159.63:49771]
15/10/02 11:51:39 INFO Utils: Successfully started service 'sparkDriver' on port 49771.
15/10/02 11:51:39 INFO SparkEnv: Registering MapOutputTracker
15/10/02 11:51:39 INFO SparkEnv: Registering BlockManagerMaster
15/10/02 11:51:39 INFO DiskBlockManager: Created local directory at /private/var/folders/t2/bmq0l4f516789351wk6b_sgh0000gn/T/blockmgr-9835046a-8616-474d-9323-18ece2f27345
15/10/02 11:51:39 INFO MemoryStore: MemoryStore started with capacity 530.0 MB
15/10/02 11:51:39 INFO HttpFileServer: HTTP File server directory is /private/var/folders/t2/bmq0l4f516789351wk6b_sgh0000gn/T/spark-b590218c-0886-4de4-8d54-593b325d4f13/httpd-3ba55a92-42ee-4d40-9ad1-b6fd25bf27c9
15/10/02 11:51:39 INFO HttpServer: Starting HTTP Server
15/10/02 11:51:39 INFO Utils: Successfully started service 'HTTP file server' on port 49772.
15/10/02 11:51:39 INFO SparkEnv: Registering OutputCommitCoordinator
15/10/02 11:51:39 INFO Utils: Successfully started service 'SparkUI' on port 4040.
15/10/02 11:51:39 INFO SparkUI: Started SparkUI at http://172.30.159.63:4040
15/10/02 11:51:39 INFO SparkContext: Added JAR file:/Users/john/programming/scala/test/target/scala-2.11/test_2.11-1.0.jar at http://172.30.159.63:49772/jars/test_2.11-1.0.jar with timestamp 1443779499566
15/10/02 11:51:39 WARN MetricsSystem: Using default name DAGScheduler for source because spark.app.id is not set.
15/10/02 11:51:39 INFO Executor: Starting executor ID driver on host localhost
15/10/02 11:51:39 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 49773.
15/10/02 11:51:39 INFO NettyBlockTransferService: Server created on 49773
15/10/02 11:51:39 INFO BlockManagerMaster: Trying to register BlockManager
15/10/02 11:51:39 INFO BlockManagerMasterEndpoint: Registering block manager localhost:49773 with 530.0 MB RAM, BlockManagerId(driver, localhost, 49773)
15/10/02 11:51:39 INFO BlockManagerMaster: Registered BlockManager
Exception in thread "main" java.lang.ClassNotFoundException: Failed to load class for data source: com.databricks.spark.csv.
    at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.lookupDataSource(ResolvedDataSource.scala:67)
    at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:87)
    at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:114)
    at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:104)
    at Test$.main(Test.scala:10)
    at Test.main(Test.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: com.databricks.spark.csv.DefaultSource
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4$$anonfun$apply$1.apply(ResolvedDataSource.scala:60)
    at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4$$anonfun$apply$1.apply(ResolvedDataSource.scala:60)
    at scala.util.Try$.apply(Try.scala:161)
    at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4.apply(ResolvedDataSource.scala:60)
    at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4.apply(ResolvedDataSource.scala:60)
    at scala.util.Try.orElse(Try.scala:82)
    at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.lookupDataSource(ResolvedDataSource.scala:60)
    ... 14 more
15/10/02 11:51:40 INFO SparkContext: Invoking stop() from shutdown hook
15/10/02 11:51:40 INFO SparkUI: Stopped Spark web UI at http://172.30.159.63:4040
15/10/02 11:51:40 INFO DAGScheduler: Stopping DAGScheduler
15/10/02 11:51:40 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
15/10/02 11:51:40 INFO MemoryStore: MemoryStore cleared
15/10/02 11:51:40 INFO BlockManager: BlockManager stopped
15/10/02 11:51:40 INFO BlockManagerMaster: BlockManagerMaster stopped
15/10/02 11:51:40 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
15/10/02 11:51:40 INFO SparkContext: Successfully stopped SparkContext
15/10/02 11:51:40 INFO ShutdownHookManager: Shutdown hook called
15/10/02 11:51:40 INFO ShutdownHookManager: Deleting directory /private/var/folders/t2/bmq0l4f516789351wk6b_sgh0000gn/T/spark-b590218c-0886-4de4-8d54-593b325d4f13
```

Things I've tried:
- Different combinations of versions for Spark and spark-csv
- Adding `--packages com.databricks:spark-csv_2.11:1.2.0` to the `spark-submit` command

Any idea what's going on here?

**Comment by schmee** [comment]
It might be worth mentioning that running `spark-1.5.1-bin-hadoop2.6/bin/spark-shell --packages com.databricks:spark-csv_2.11:1.2.0` works just fine.

**Comment by meox** [comment]
this works for me:
libraryDependencies += "com.databricks" % "spark-csv_2.11" % "1.2.0"

**Comment by tristanreid** [comment]
If you're using the `--packages com.databricks:spark-csv_2.10:1.2.0` option with the `spark-submit` command, note that it has to go in the specific order:

    spark-submit --packages com.databricks:spark-csv_2.10:1.2.0 your_script.py

If you put it at the end it won't get picked up.

**Comment by m0nhawk** [comment]
And how to fix this without `--package` option in Maven?

**Comment by dhunziker** [comment]
Having the same issue running Python through eclipse with all the required JARs added to the PYTHONPATH.

**Comment by gregmisiorek** [comment]
my java is acting up as well:

Name: java.lang.RuntimeException
Message: Failed to load class for data source: com.databricks.spark.csv
StackTrace: scala.sys.package$.error(package.scala:27)

**Comment by 5ean** [comment]
any people try 1.3.0, due to some reasons, I can not use --package, so I use:

`pyspark --jars="commons-csv-1.2.jar,spark-csv_2.10-1.3.0.jar,spark-xml-utils-1.3.0.jar"`

when I do:
test= `sqlContext.read.format('com.databricks.spark.xml').options(rowTag='row').load('test_{1}.xml'.format(business_date.strftime('%Y%m%d')))`

I got:
` java.lang.ClassNotFoundException: Failed to find data source: com.databricks.spark.xml. Please find packages at http://spark-packages.org`

**Comment by noleto** [comment]
@5ean I was able to solve a similar problem following this solution: http://apache-spark-user-list.1001560.n3.nabble.com/How-to-add-jars-to-standalone-pyspark-program-td22685.html

> I've worked around this by dropping the jars into a directory (for instance: spark_jars) and then creating a spark-defaults.conf file in conf Spark directory containing this: 

>spark.driver.extraClassPath        /home/mj/apps/spark_jars/*

Worked for me.

**Comment by deepakmundhada** [comment]
I'm trying to write XML using spark-xml library with below statement -
 val selectedData = xmlDF.select("*")
selectedData.write.format("xml").mode(SaveMode.Append).option("rootTag", "TXNEXP").option("rowTag", x).save("FIS.xml")

Getting below error. How can I achieve append mode functionality?

Exception in thread "main" java.lang.RuntimeException: Append mode is not supported by com.databricks.spark.xml.DefaultSource15
        at scala.sys.package$.error(package.scala:27)
        at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:80)
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:170)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:146)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:137)
        at com.paysafe.bigdata.commons.sparkjobs.fileloader.XmlLoader$$anonfun$findUnknownMapping$1.apply(XmlLoader.scala:111)
        at com.paysafe.bigdata.commons.sparkjobs.fileloader.XmlLoader$$anonfun$findUnknownMapping$1.apply(XmlLoader.scala:108)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at com.paysafe.bigdata.commons.sparkjobs.fileloader.XmlLoader.findUnknownMapping(XmlLoader.scala:108)
        at com.paysafe.bigdata.commons.sparkjobs.fileloader.XmlLoader.execute(XmlLoader.scala:93)
        at com.paysafe.bigdata.commons.util.LoaderApp$.main(LoaderApp.scala:12)
        at com.paysafe.bigdata.commons.util.LoaderApp.main(LoaderApp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:674)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by HyukjinKwon** [comment]
@deepakmundhada Hi, append mode is not yet supported in spark-xml. See here, https://github.com/databricks/spark-xml/issues/25.

**Comment by isragaytan** [comment]
For me worked in this way

```
package io.visor{

	import org.apache.spark.SparkContext
	import org.apache.spark.SparkContext._
	import org.apache.spark.SparkConf
	import org.apache.spark.sql.SQLContext


object ETL{

	def main(args:Array[String]){
	
		val conf = new SparkConf().setAppName("Csv loading Example")	
		val sc = new SparkContext(conf)
   		val sqlContext = new org.apache.spark.sql.SQLContext(sc)
    	val df = sqlContext.read.format("com.databricks.spark.csv")
    	.option("header","true")
    	.option("inferSchema","true")
        .load("/home/isragaytan/Documents/kosmos.csv")

    	//Show data frame
    	df.show()	
    	

		sc.stop()

	}



}

```
Then in build.sbt

```
name := "ETL"

version := "0.1"

scalaVersion := "2.10.5"

libraryDependencies ++= Seq (
"org.apache.spark" %% "spark-core" % "1.6.2" % "provided",
"org.apache.spark" %% "spark-sql" % "1.6.2" % "provided",
"com.databricks" %% "spark-csv" % "1.4.0" % "provided"
)


```
**Finally in spark submit  dont forget to include the csv packages** ...

_bin/spark-submit --packages com.databricks:spark-csv_2.10:1.4.0 --class "io.visor.ETL" --master local[*] /home/isragaytan/Documents/visor_bd/etl/target/scala-2.10/etl_2.10-0.1.jar_

Hope it helps.

**Comment by rubinrp** [comment]
How can I eliminate the need to specify --packages option into spark-submit command ?

**Comment by H4ml3t** [comment]
Ditto. I tried to compile the library, but it's not including all necessary dependencies apparently. A way to avoid to specify the --package option but rather use the --jar spark-csv_2.10-1.4.0.jar option?

I need this because I can put the jar wherever I want, instead with the package option there is a cache that needs to be maintained and the user may not have rights to write it in the file system.

Cheers,
Luca

**Comment by H4ml3t** [comment]
I'll reply to myself and to @rubinrp saying that it is sufficient to use sbt/sbt assembly instead of package.

Cheers,
Luca

**Comment by jerzygangi** [comment]
Thank you for solving my problem, @tristanreid !
