### ISSUE TITLE
Implement trim feature

### ISSUE THREAD

**Issue by syepes** [databricks/spark-csv#158]
It would be nice to have an option that trims the extra spaces and tabs before parsing the actual values.

Input Data
```
ENDDATEHOUR;STARTDATEHOUR;NUMBER;STATUS
2013-10-17 15:19:57;2013-10-17 15:19:18;  546683456  ;Normal      
```
Spark:
```
val schema = StructType(Array(StructField("ENDDATEHOUR",TimestampType,true),
                                         StructField("STARTDATEHOUR",TimestampType,true),
                                         StructField("NUMBER",IntegerType,true),
                                         StructField("STATUS",StringType,true)))
val df = sqlContext.read.format("com.databricks.spark.csv").options(Map("header" -> "true", "path" -> "logs.csv.lzo", "delimiter" -> ";", "inferSchema" -> "false")).schema(schema).load()
```

Error:
```
java.lang.NumberFormatException: For input string: "  546683456  " at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) at java.lang.Integer.parseInt(Integer.java:580) at java.lang.Integer.parseInt(Integer.java:615) at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229) at scala.collection.immutable.StringOps.toInt(StringOps.scala:31) at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:45)
```

**Comment by HyukjinKwon** [comment]
+1

**Comment by svivekbafna** [comment]
+1

**Comment by HyukjinKwon** [comment]
I agree this can be done with a simple tranformation by users themselves though. I see some users want to just only use SparkSQL (HiveQL interface). I am not sure if we can do this only in SQL. If not, I think this might be worth implementing this feature.

**Comment by etspaceman** [comment]
+1
