### ISSUE TITLE
CSV load with userSchema in PySpark not working

### ISSUE THREAD

**Issue by tonycpsu** [databricks/spark-csv#161]
Test code:

```python
from pyspark import SparkContext
from pyspark.sql import SQLContext
from pyspark.sql.types import *

sc = SparkContext(appName="test")
sql_context = SQLContext(sc)

schema = StructType([StructField("test", StringType(), False)])

df = (
    sql_context.read
    .format('com.databricks.spark.csv')
    .options(userSchema = schema)
    .load("foo.csv")
)

print df
```

Results in:

```python
Traceback (most recent call last):
  File "/tmp/spark/sparktest.py", line 13, in <module>
    .options(userSchema = schema)
  File "/usr/local/Cellar/apache-spark/1.4.0/libexec/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 76, in options
  File "/usr/local/Cellar/apache-spark/1.4.0/libexec/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 529, in __call__
  File "/usr/local/Cellar/apache-spark/1.4.0/libexec/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 265, in get_command_part
AttributeError: 'StructType' object has no attribute '_get_object_id'
```

My goal is to be able to load a CSV file without a header by specifying the field names and types as a schema.  Does this work from PySpark, and if so, what am I doing wrong?

**Comment by learneddamo** [comment]
Facing same issue when using spark-csv over spark v1.4.1. Issue seems to be with the newly introduced DataFrameReader. Quick work around is to use the deprecated SQLContext loader.

Sample Work Around:
df = sqlContext.load(source="com.databricks.spark.csv", header = 'true', schema = customSchema, path = 'cars.csv')
