### ISSUE TITLE
CSV load doesn't work with custom schema having fields with data type other than String

### ISSUE THREAD

**Issue by shashwat7** [databricks/spark-csv#184]
Hi,

I tried reading a CSV file, with a custom schema. 

val ticket:StructType = StructType( Array(
    StructField("tkt_id", LongType, false),
    StructField("tkt_number", StringType, true),
    StructField("tkt_date_of_issue", DateType, true),
    StructField("tkt_pax_type", StringType, true),
    StructField("tkt_off_id", StringType, true),
    StructField("tkt_total_amount", DoubleType, true))

val tkt_df = sqlContext.load("com.databricks.spark.csv", ticket, Map("path" -> ticket_dump_path, "header" -> "true")) 

It shows zero rows are read. But when I change the schema to 
val ticket:StructType = StructType( Array(
    StructField("tkt_id", StringType, false),
    StructField("tkt_number", StringType, true),
    StructField("tkt_date_of_issue", StringType, true),
    StructField("tkt_pax_type", StringType, true),
    StructField("tkt_off_id", StringType, true),
    StructField("tkt_total_amount", StringType, true))

It is able to read successfully...

Sample Input:
TKT_ID,TKT_PRIMARY_NUMBER,TKT_DATE_OF_ISSUE,TKT_PAX_TYPE,TKT_OFF_ID,TKT_TOTAL_AMOUNT
107774743,1052456570488,27/oct/2015,PAX,194968,1386.19
107774744,1059213152304,28/oct/2015,PAX,191488,
107774745,1059213152305,28/oct/2015,PAX,191488,
107774746,1059345473851,28/oct/2015,PAX,191488,1241

**Comment by piccolbo** [comment]
I may have something similar going on. Interfacing R with SQL in my case. If I let the schema inference do its thing I get the wrong schema

```
Source: Spark at:localhost:10000
From: flights [336,776 x 16]

    year month   day dep_time dep_delay arr_time arr_delay carrier tailnum flight origin  dest
   (int) (int) (int)    (chr)     (chr)    (chr)     (chr)   (chr)   (chr)  (int)  (chr) (chr)
1   2013     1     1      517         2      830        11      UA  N14228   1545    EWR   IAH
2   2013     1     1      533         4      850        20      UA  N24211   1714    LGA   IAH
3   2013     1     1      542         2      923        33      AA  N619AA   1141    JFK   MIA
4   2013     1     1      544        -1     1004       -18      B6  N804JB    725    JFK   BQN
5   2013     1     1      554        -6      812       -25      DL  N668DN    461    LGA   ATL
6   2013     1     1      554        -4      740        12      UA  N39463   1696    EWR   ORD
..   ...   ...   ...      ...       ...      ...       ...     ...     ...    ...    ...   ...
Variables not shown: air_time (chr), distance (int), hour (chr), minute (chr)
```

If I specify the schema in create table (you can imagine several of those character cols should be integer)  I get this stack trace

```
Unable to retrieve JDBC result set for SELECT count(*) FROM (SELECT `year`, `month`, `day`, `dep_time`, `dep_delay`, `arr_time`, `arr_delay`, `carrier`, `tailnum`, `flight`, `origin`, `dest`, `air_time`, `distance`, `hour`, `minute`
FROM `flights`) AS `master` (org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 1269.0 failed 1 times, most recent failure: Lost task 1.0 in stage 1269.0 (TID 27767, localhost): java.lang.NumberFormatException: For input string: "NA"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at scala.collection.immutable.StringLike$class.toDouble(StringLike.scala:232)
	at scala.collection.immutable.StringOps.toDouble(StringOps.scala:31)
	at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:48)
	at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelatio
```

This seems to point to a problem with parsing NAs. When I tried by binary search to find which was the first offending line, it couldn't parse past line 95, but the first instance of an NA is several hundred lines later. Sorry if this is not close enough to the reporter's original concern, I am happy to split to its own issue if it's better. My educated guess is that it's two instances of a too strict parser. The data is in an R package called nycflights13, data.frame is called "flights". I can provide the exact SQL if needed. Thanks

**Comment by falaki** [comment]
@shashwat7 use FAIL_FAST parsing mode with your schema and see what record causes the failure. I suspect there are values in your data that cannot be parsed. You may need to preform some cleaning.

**Comment by piccolbo** [comment]
FAILFAST did not provide additional information, but it was a problem with NAs. Once filtered out in advance, problem disappears.

**Comment by nealmcb** [comment]
I ran into a similar or identical problem, trying to parse the line     

    63869,Apollo_asteroids,089959n(89959) 2002 NT7,2015-03-17 21:39:21,089959,uppercase,page

via this schema:

    customSchema = StructType([
      StructField("cl_from", LongType(), True),
      StructField("cl_to", StringType(), True),
      StructField("cl_sortkey", StringType(), True),
      StructField("cl_timestamp", TimestampType(), True),
      StructField("cl_sortkey_prefix", StringType(), True),
      StructField("cl_collation", StringType(), True),
      StructField("cl_type", StringType(), True),
      ])

It worked to parse it this way:

    customSchemaStrings = StructType([
      StructField("cl_from", StringType(), True),
      StructField("cl_to", StringType(), True),
       StructField("cl_sortkey", StringType(), True),
      StructField("cl_timestamp", StringType(), True),
      StructField("cl_sortkey_prefix", StringType(), True),
      StructField("cl_collation", StringType(), True),
      StructField("cl_type", StringType(), True),
      ])

    categoryLinksTableStringsDF = (sqlContext.read.format('com.databricks.spark.csv')
     .options(header='false')
     .load(dbwikidir+name, schema = customSchemaStrings)
     .cache() )


The error was `java.lang.NumberFormatException: For input string: "89959) 2002 NT7"` so for some reason it was trying to find a number inside some parenthesis in a StringType field.

    org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 76.0 failed 1 times, most recent failure: Lost task 0.0 in stage 76.0 (TID 231, localhost): java.lang.NumberFormatException: For input string: "89959) 2002 NT7"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at scala.collection.immutable.StringLike$class.toLong(StringLike.scala:230)
	at scala.collection.immutable.StringOps.toLong(StringOps.scala:31)
	at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:46)
	at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:119)
	at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:105)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.sql.columnar.InMemoryRelation$$anonfun$3$$anon$1.next(InMemoryColumnarTableScan.scala:127)
	at org.apache.spark.sql.columnar.InMemoryRelation$$anonfun$3$$anon$1.next(InMemoryColumnarTableScan.scala:120)
	at org.apache.spark.storage.MemoryStore.unrollSafely(MemoryStore.scala:278)
	at org.apache.spark.CacheManager.putInBlockManager(CacheManager.scala:171)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:78)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:262)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by falaki** [comment]
@nealmcb I suspect that line in your file has extra delimiter characters.

**Comment by nealmcb** [comment]
@falaki It is a strange-looking line (wikipedia category information for asteroid https://en.wikipedia.org/wiki/(89959)_2002_NT7), but the commas split it up appropriately.  The third column, "cl_sortkey" is indeed supposed to be '089959n(89959) 2002 NT7''

**Comment by pvillacorta-stratio** [comment]
I am experimenting a very similar problem (FAILFAST has apparently no effect) in Pyspark 2.1.0. If I specify the custom schema as spark.read..option("inferSchema", "false").option("mode", "FAILFAST").option("schema", myschema).csv("/path"), my schema has no effect and everything is read as String (FAILFAST seems to be ignored). But when I specify spark.read.option("mode", "FAILFAST").csv(schema = myschema, path = "/path/to/file.csv") then it works. 

Am I missing something? Is it not possible to specify .option("schema", customSchema) anymore in Pyspark 2.1.0?
