### ISSUE TITLE
Drop elements with malformatted Strings for TimestampType in DROPMALFORMED

### ISSUE THREAD

**Issue by fabboe** [databricks/spark-csv#196]
Hello,
I'm wondering whether a String that is not castable to TimestampType, should be caught and dropped in DROPMALFORMED mode, or raise this exception?

It works nicely on the non-corrupt elements, but then fails when rows with wrong schema appear.
```
structType = StructType(List(StructField(moviename,StringType,true),...,StructField(start_time,TimestampType,true)))
df = sqlContext.read.format('com.databricks.spark.csv') \ 
.options(header='false', escape='"', delimiter='|', mode='DROPMALFORMED') \
.load('hdfs://master/my.csv', schema=structType)
df.count()
```

```
Py4JJavaError: An error occurred while calling o127.count.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 399 in stage 7.0 failed 4 times, most recent failure: Lost task 399.3 in stage 7.0 (TID 1337, worker03): java.lang.IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
	at java.sql.Timestamp.valueOf(Timestamp.java:202)
	at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:62)
	at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:118)
	at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:104)
```

Maybe catch this exception [here](https://github.com/databricks/spark-csv/blob/master/src/main/scala/com/databricks/spark/csv/CsvRelation.scala#L127) and drop the record since it doesn't match the schema?

**Comment by HyukjinKwon** [comment]
This was fixed in https://github.com/databricks/spark-csv/pull/221.

**Comment by HyukjinKwon** [comment]
@fabboe Could we maybe close this?
