### ISSUE TITLE
Error  java.lang.String cannot be cast to org.apache.spark.unsafe.types.UTF8String

### ISSUE THREAD

**Issue by kamakay** [databricks/spark-csv#206]
Dear all I am trying on a windows machine to perform some basical csv manipulation using spark-shell. When accessinf rdd i receive this error for each line of the source csv.

 java.lang.String cannot be cast to org.apache.spark.unsafe.types.UTF8String

the command is

val df = sqlContext.read.format("com.databricks.spark.csv").option("inferSchema", "true").option("delimiter",",").option("header", "true").load("C:/SparkCourse/fake.csv").collect()

Can you help me to find out the solution?
Many thanks in advance

Roberto

**Comment by falaki** [comment]
Please try specifying encoding. Please try both UTF-8 and UTF-16.

**Comment by kamakay** [comment]
Hi,

I tried with both UTF-8 and UTF-16, modyfing also line separator (from windows to linux and viceversa).

I still receive the error

**Comment by marmbrus** [comment]
This doesn't look like an encoding error to me.  Can you provide the stack
trace?  My guess is the version of spark-csv is incompatible with the
version of spark.

**Comment by kamakay** [comment]
I am using spark 1.5.1 on scala 2.10.4

I launch the shell with this parameter

spark-shell --packages com.databricks:spark-csv_2.10:1.0.3

Voila my stack trace

15/12/12 19:41:18 ERROR CsvRelation$: Exception while parsing line: "Irene","Lup",45,"Italy".
java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.spark.unsafe.types.UTF8String
        at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow$class.getUTF8String(rows.scala:45)
        at org.apache.spark.sql.catalyst.expressions.GenericMutableRow.getUTF8String(rows.scala:247)
        at org.apache.spark.sql.catalyst.expressions.BoundReference.eval(BoundAttribute.scala:49)
        at org.apache.spark.sql.catalyst.expressions.UnaryExpression.eval(Expression.scala:247)
        at org.apache.spark.sql.catalyst.expressions.InterpretedMutableProjection.apply(Projection.scala:82)
        at org.apache.spark.sql.catalyst.expressions.InterpretedMutableProjection.apply(Projection.scala:61)
        at com.databricks.spark.csv.CsvRelation$$anonfun$com$databricks$spark$csv$CsvRelation$$parseCSV$1.apply(CsvRelat
ion.scala:150)
        at com.databricks.spark.csv.CsvRelation$$anonfun$com$databricks$spark$csv$CsvRelation$$parseCSV$1.apply(CsvRelat
ion.scala:130)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
        at scala.collection.AbstractIterator.to(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:905)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:905)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1848)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1848)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:88)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by kamakay** [comment]
Solved by myself 
used spark-shell --packages com.databricks:spark-csv_2.10:1.0.3
instead of
spark-shell --packages com.databricks:spark-csv_2.10:1.3.0

**Comment by nivemaham** [comment]
I got the same issue. I think the versions mentioned above are swapped. 
The error preserved when i used com.databricks:spark-csv_2.10:1.0.3 where as got solved for com.databricks:spark-csv_2.10:1.3.0. 
Thanks

**Comment by ShivaShinde** [comment]
Got the same issue, just change the version name to 1.3.0 or above, 1.0.3 seems to be not compatible.
