### ISSUE TITLE
AmazonClientException when trying to write to S3 (running AWS EMR 4.2)

### ISSUE THREAD

**Issue by gsindholt** [databricks/spark-csv#225]
When I try to use spark-csv to store data on S3, I am consistently running into this exception:

    com.amazonaws.AmazonClientException: Unable to execute HTTP request: Read timed out
	    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:516)
	    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:317)
	    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3595)
	    at com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1511)
	    at com.amazonaws.services.s3.transfer.internal.CopyCallable.copyInOneChunk(CopyCallable.java:146)
	    at com.amazonaws.services.s3.transfer.internal.CopyCallable.call(CopyCallable.java:134)
	    at com.amazonaws.services.s3.transfer.internal.CopyMonitor.copy(CopyMonitor.java:193)
	    at com.amazonaws.services.s3.transfer.internal.CopyMonitor.call(CopyMonitor.java:147)
	    at com.amazonaws.services.s3.transfer.internal.CopyMonitor.call(CopyMonitor.java:47)
	    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	    at java.lang.Thread.run(Thread.java:745)
    Caused by: java.net.SocketTimeoutException: Read timed out
	    at java.net.SocketInputStream.socketRead0(Native Method)
	    at java.net.SocketInputStream.read(SocketInputStream.java:152)
	    at java.net.SocketInputStream.read(SocketInputStream.java:122)
	    at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
	    at sun.security.ssl.InputRecord.read(InputRecord.java:480)
	    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:946)
	    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:903)
	    at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
	    at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
	    at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
	    at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273)
	    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	    at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
	    at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
	    at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:197)
	    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	    at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:66)
	    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	    at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
	    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
	    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:749)
	    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:505)
	    ... 12 more

I'm using spark-csv 1.3 (I have tried 1.2 also, but the same error occurs) and running on AWS EMR using EMR 4.2 with pre-installed Spark 1.5.2. Save command used is:

    dataFrame.write.format("com.databricks.spark.csv").save(outputPath)

If I store the data as parquet instead, there are no problems. The exception only occurs when using spark-csv.

**Comment by mydpy** [comment]
I think this issue is also appearing 
[on StackOverflow](http://stackoverflow.com/questions/35613479/loading-csv-into-pyspark-from-s3?noredirect=1#comment58911982_35613479)

**Comment by gsindholt** [comment]
I discovered that if I use s3://... instead of s3n://... everything works fine.

**Comment by aarondav** [comment]
Note that EMR rewrites s3:// to be their own proprietary implementation
more similar to "s3a" in nature. I doubt they set proper defaults for s3n
regarding timeouts and retries which are typically necessary for stable s3n
usage.
