### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.databricks.spark.csv.util.InferSchema

### ISSUE THREAD

**Issue by napsternxg** [databricks/spark-csv#233]
I am running R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
with Spark installed from their source github repository. 

I am getting an error when using the inferSchema = "true". A similar code runs correctly in 

When I try to run the following command:
```
> df <- read.df(sqlContext, "out/data.txt", source = "com.databricks.spark.csv", delimiter="\t", header="true", inferSchema="true")
```

I am getting the following error:
```
16/01/19 14:56:54 ERROR RBackendHandler: loadDF on org.apache.spark.sql.api.r.SQLUtils failed
Error in invokeJava(isStatic = TRUE, className, methodName, ...) : 
  java.lang.NoClassDefFoundError: Could not initialize class com.databricks.spark.csv.util.InferSchema$
        at com.databricks.spark.csv.CsvRelation.inferSchema(CsvRelation.scala:231)
        at com.databricks.spark.csv.CsvRelation.<init>(CsvRelation.scala:72)
        at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:157)
        at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:44)
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:160)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:108)
        at org.apache.spark.sql.api.r.SQLUtils$.loadDF(SQLUtils.scala:160)
        at org.apache.spark.sql.api.r.SQLUtils.loadDF(SQLUtils.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invok
```

If I use the option "InferSchem='true'", I get a different kind of error:

```
16/01/19 15:04:04 ERROR RBackendHandler: loadDF on org.apache.spark.sql.api.r.SQLUtils failed
Error in invokeJava(isStatic = TRUE, className, methodName, ...) : 
  java.lang.NoClassDefFoundError: Could not initialize class com.databricks.spark.csv.util.InferSchema$
        at com.databricks.spark.csv.CsvRelation.inferSchema(CsvRelation.scala:231)
        at com.databricks.spark.csv.CsvRelation.<init>(CsvRelation.scala:72)
        at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:157)
        at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:44)
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:160)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:108)
        at org.apache.spark.sql.api.r.SQLUtils$.loadDF(SQLUtils.scala:160)
        at org.apache.spark.sql.api.r.SQLUtils.loadDF(SQLUtils.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invok

```

However, when I run the command without the option `inferSchema="true"` my data frames work correctly.

My `.RProfile` looks like the following:
```
# Sample Rprofile.site file 

# Things you might want to change
.First <- function(){
  cat("\nWelcome at", date(), "\n") 
  SPARK_HOME <- "/content/username/SOFTWARE/spark"
  Sys.setenv('SPARKR_SUBMIT_ARGS'='"--packages" "com.databricks:spark-csv_2.10:1.3.0" "sparkr-shell"')
  .libPaths(c(file.path(SPARK_HOME, "R", "lib"), .libPaths()))
  library(SparkR)
  sc <<- sparkR.init(master="local[20]", appName="Author Role SparkR", sparkHome=SPARK_HOME,
    sparkEnvir=list(spark.local.dir="./tmp",
    spark.executor.memory="50g",
    spark.driver.maxResultSize="50g",
    spark.driver.maemory="50g",
    sparkPackages=c("com.databricks:spark-csv_2.10:1.3.0")))
}

.Last <- function(){ 
  cat("\nGoodbye at ", date(), "\n")
}

```

My Spark packages are loaded successfully:

```
Welcome at Tue Jan 19 14:43:19 2016 

Attaching package: â€˜SparkRâ€™

The following objects are masked from â€˜package:baseâ€™:

    colnames, colnames<-, intersect, rank, rbind, sample, subset,
    summary, table, transform

Launching java with spark-submit command /content/username/SOFTWARE/spark/bin/spark-submit   "--packages" "com.databricks:spark-csv_2.10:1.3.0" "sparkr-shell" /tmp/RtmpYgN5sO/backend_port72d91098cda7 
Ivy Default Cache set to: /homed/username/.ivy2/cache
The jars for the packages stored in: /homed/username/.ivy2/jars
:: loading settings :: url = jar:file:/content/username/SOFTWARE/spark/assembly/target/scala-2.10/spark-assembly-2.0.0-SNAPSHOT-hadoop2.2.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.databricks#spark-csv_2.10 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
        confs: [default]
        found com.databricks#spark-csv_2.10;1.3.0 in central
        found org.apache.commons#commons-csv;1.1 in central
        found com.univocity#univocity-parsers;1.5.1 in central
:: resolution report :: resolve 512ms :: artifacts dl 42ms
        :: modules in use:
        com.databricks#spark-csv_2.10;1.3.0 from central in [default]
        com.univocity#univocity-parsers;1.5.1 from central in [default]
        org.apache.commons#commons-csv;1.1 from central in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
        ---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent
        confs: [default]
        0 artifacts copied, 3 already retrieved (0kB/15ms)


> 

```

**Comment by falaki** [comment]
What version of Spark are you using? This seems like a binary compatibility issue between spark-csv and spark Jars.

**Comment by napsternxg** [comment]
I am using spark installed from source using the master branch. 

> with Spark installed from their source github repository.

**Comment by falaki** [comment]
In master you don't need spark-csv. CSV data source is built into SparkSQL. Just use it as follows:
```r
df <- read.df(sqlContext, "out/data.txt", source = "csv", delimiter="\t", header="true", inferSchema="true")
```

**Comment by napsternxg** [comment]
Cool thanks. Works.
