### ISSUE TITLE
java.lang.NegativeArraySizeException 

### ISSUE THREAD

**Issue by ziakayani** [databricks/spark-csv#240]
I've noticed with we deal with the DataFrame and Apply some complex operations, then finally push that data to sink it throughs this Exception. If I move on slowly it works fine i.e. apply a transformation and show it or save it. But when we create a complex DAG of Job then finally execute that DAG this Exception occours.

Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 3.0 failed 4 times, most recent failure: Lost task 0.3 in stage 3.0 (TID 16, 192.168.23.107): java.lang.NegativeArraySizeException
        at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$6.apply(CsvRelation.scala:171)
        at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$6.apply(CsvRelation.scala:162)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.insertAll(BypassMergeSortShuffleWriter.java:118)
        at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:88)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1283)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1271)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1270)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1270)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:697)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:697)
        at scala.Option.foreach(Option.scala:236)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:697)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1496)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1458)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1447)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:567)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1824)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1837)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1914)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply$mcV$sp(PairRDDFunctions.scala:1124)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply(PairRDDFunctions.scala:1065)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply(PairRDDFunctions.scala:1065)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
        at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopDataset(PairRDDFunctions.scala:1065)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply$mcV$sp(PairRDDFunctions.scala:989)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:965)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:965)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
        at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:965)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply$mcV$sp(PairRDDFunctions.scala:897)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:897)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:897)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
        at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:896)
        at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply$mcV$sp(RDD.scala:1430)
        at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1409)
        at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1409)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
        at org.apache.spark.rdd.RDD.saveAsTextFile(RDD.scala:1409)
        at com.databricks.spark.csv.package$CsvSchemaRDD.saveAsCsvFile(package.scala:180)
        at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:185)
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:170)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:146)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:137)
        at com.platalytics.platform.testing.App$.main(App.scala:168)
        at com.platalytics.platform.testing.App.main(App.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:674)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.NegativeArraySizeException
        at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$6.apply(CsvRelation.scala:171)
        at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$6.apply(CsvRelation.scala:162)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.insertAll(BypassMergeSortShuffleWriter.java:118)
        at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:88)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by falaki** [comment]
Please provide additional details: versions of spark and spark-csv, sample of your data and you query.

**Comment by ziakayani** [comment]
This is a complex example where I got this issue.

**Purchases.csv - 34G - 719,332,082 Records
Returns.csv - 469M - 10,131,593 Records
Users.csv - 319M - 500,000 Records**

    val customSchema = StructType(Array(
      StructField("TxnID", IntegerType, true),
      StructField("UserID", IntegerType, true),
      StructField("Timestamp", StringType, true),
      StructField("ItemID", IntegerType, true),
      StructField("Quantity", IntegerType, true),
      StructField("UnitPrice", DoubleType, true)))
    
    val uSchema = StructType(Array(
      StructField("UserID", IntegerType, true),
      StructField("FirstName", StringType, true),
      StructField("LastName", StringType, true),
      StructField("Email", StringType, true),
      StructField("ZipCode", StringType, true),
      StructField("City", StringType, true),
      StructField("Country", StringType, true)))
    
    val purchases = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").schema(customSchema).load("/BigData/Purchases.csv").as("purchases")
    
    val users = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").schema(uSchema).load("/BigData/Users.csv").as("users")
    val returns = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").schema(customSchema).load("/BigData/Returns.csv").as("returns")
    
    val totalPurchases = purchases.withColumn("TOTAL_PURCHASE", purchases("Quantity").plus(purchases("UnitPrice"))).as("tp")
    val totalReturns = returns.withColumn("TOTAL_RETURN", (returns("Quantity").plus(returns("UnitPrice")))).as("tr")
    
    val ufields = users.schema.fieldNames
    val pfields = purchases.schema.fieldNames
    val rfields = returns.schema.fieldNames
    
    val up = users.join(totalPurchases, $"users.UserID" === $"tp.UserID")
        .selectExpr((ufields.drop(1).map(x => "users." + x + " as up_" + x) ++ totalPurchases.schema.fieldNames.map(x => "tp." + x + " as up_" + x)): _*)
    val ur = users.join(totalReturns, $"users.UserID" === $"tr.UserID") 
        .selectExpr((ufields.drop(1).map(x => "users." + x + " as ur_" + x) ++ totalReturns.schema.fieldNames.map(x => "tr." + x + " as ur_" + x)): _*)
          
    val sump = up.groupBy("up_UserID", "up_FirstName", "up_LastName", "up_Email", "up_Country")
        .agg(sum($"up_TOTAL_PURCHASE") as "PURCHASE_SUM")
    val sumr = ur.groupBy("ur_UserID", "ur_FirstName", "ur_LastName", "ur_Email", "ur_Country")
        .agg(sum($"ur_TOTAL_RETURN") as "RETURN_SUM")
    
    
    val joined = sump.join(sumr, $"ur_UserID" === $"up_UserID")    
        .selectExpr( Seq("up_UserID as UserID", "ur_FirstName as FirstName", "ur_LastName as LastName", "ur_Email as Email", "ur_Country as Country", "PURCHASE_SUM", "RETURN_SUM"): _*)
    
    val net = joined.withColumn("USER_NET_PURCHASE", (joined("PURCHASE_SUM").minus(joined("RETURN_SUM"))))
    
    val result = net.withColumn("USER_MEMBERS", 
        when($"USER_NET_PURCHASE" > 0 && $"USER_NET_PURCHASE" < 1999,"Bronze").
        when($"USER_NET_PURCHASE" > 2000 && $"USER_NET_PURCHASE" < 4999,"Silver").
        otherwise("Gold"))
    
    result.write.format("com.databricks.spark.csv").option("header", "true").save("/purch3/tags/")`

**Comment by ziakayani** [comment]
Spark CSV is working fine, I've looked into it deeply, Its actually Spark Bug, tracked [here](https://issues.apache.org/jira/browse/SPARK-10538) When I persist the DataFrame after ingestion and then join both DataFrames, it works fine.

**Comment by HyukjinKwon** [comment]
I believe the PR https://github.com/databricks/spark-csv/pull/251 fixes this issue.

**Comment by raschild** [comment]
@ziakayani  +1 for persist

**Comment by HyukjinKwon** [comment]
Fixed in https://github.com/databricks/spark-csv/pull/251.

Can we maybe close this? @raschild @ziakayani @falaki

**Comment by oluies** [comment]
+1 for persist

**Comment by soniacisneros** [comment]
@HyukjinKwon Issue in #251 is related to tokens length, different to this issue, which is related to a failure when processing complex operations over a relatively large DataFrames, likely to be when the DF has many rows (millons at least).  Issue #251 does not provide the full log as this issue, that might be why it seem to be the same but it is not.

**Comment by polinom** [comment]
I was having the same issue and fixed it by providing older version of `spark-csv`.

I have spark 1.6.2 and was having the same problem with `spark-csv_2.11-1.3.0`. It was working fine after I've put spark-csv_2.10-1.4.0 as my dependencies in env variable like so:

```
export SPARKR_SUBMIT_ARGS="--packages com.databricks:spark-csv_2.10:1.4.0 pyspark-shell"
```

**Comment by Arnold1** [comment]
what is this Caused by: java.lang.NegativeArraySizeException caused? how to fix it? i see the same issue...
