### ISSUE TITLE
Commit ab648ad causes writing CSV to fail

### ISSUE THREAD

**Issue by mathieulongtin** [databricks/spark-csv#268]
The commit https://github.com/databricks/spark-csv/commit/ab648ad6fa042fc2e240adb86ac674c4e8559f7c causes writing CSV to fail. I isolated it by compiling with the previous commit and then this commit. The current HEAD fails too.

The code (in Python):
```
result = sqlContext.sql(query)
writer = result.write.format("com.databricks.spark.csv")
writer.save(output_path)
```

The stack trace:
```
py4j.protocol.Py4JJavaError: An error occurred while calling o38.save.
: java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
        at com.databricks.spark.csv.util.CompressionCodecs$.<init>(CompressionCodecs.scala:29)
        at com.databricks.spark.csv.util.CompressionCodecs$.<clinit>(CompressionCodecs.scala)
        at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:186)
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:139)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:259)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:722)
```

**Comment by mathieulongtin** [comment]
Never mind. This was due to compiling with Scala 2.11 and using a Spark that was compiled with Scala 2.10. Compiling with the same version as Spark fixes the problem.
