### ISSUE TITLE
FileNotFoundException when attempting to write an Amazon s3 location, file is .gz even with no codec specified

### ISSUE THREAD

**Issue by shriyaarora** [databricks/spark-csv#272]
I am using the spark-csv library to write the results of my Spark job to an AWS S3 location and even though the write is successful I see two issues.

1. The output file is a compressed .gz file - even thought I did not specify any codec in the option of the dataframe writer
2. I get a FileNotFoundException exception with the following stacktrace:
`java.io.FileNotFoundException: File s3://baseDirecotry/path.csv/_temporary/0 does not exist.
	at com.amazon.ws.emr.hadoop.fs.s3n.S3NativeFileSystem.listStatus(S3NativeFileSystem.java:950)
	at com.amazon.ws.emr.hadoop.fs.s3n.S3NativeFileSystem.listStatus(S3NativeFileSystem.java:892)
	at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1483)
	at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1523)
	at com.amazon.ws.emr.hadoop.fs.EmrFileSystem.listStatus(EmrFileSystem.java:353)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.getAllCommittedTaskPaths(FileOutputCommitter.java:269)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitJob(FileOutputCommitter.java:309)
	at org.apache.hadoop.mapred.FileOutputCommitter.commitJob(FileOutputCommitter.java:136)
	at org.apache.spark.SparkHadoopWriter.commitJob(SparkHadoopWriter.scala:112)`

**Comment by Gauravshah** [comment]
I think "2" has to do with s3 eventual consistency model, not sure how to go about it though

**Comment by Gauravshah** [comment]
using algorithm version does solve most of the eventual consistency problems. Actual solution is with hadoop 2.9 S3 Guard

**Comment by rachit1010** [comment]
yeah this is surely S3 listing inconsistency problem listed here:
https://hadoop.apache.org/docs/r3.1.1/hadoop-aws/tools/hadoop-aws/committers.html

S3Guard is the way to go.
