### ISSUE TITLE
issue with reading null values

### ISSUE THREAD

**Issue by amitmohanty** [databricks/spark-csv#290]
I know there has been some discussion around reading null values in spark-csv, but I could not find any concrete answer. So, here I go.

I have a csv file whose contents are like this

![image](https://cloud.githubusercontent.com/assets/1369847/13642395/56100ff0-e5ea-11e5-99ae-b7f7eee9311c.png)

I am starting my spark-shell like this 

`$ /s/god/spark-1.6.0-bin-hadoop2.6/bin/spark-shell --jars /s/god/spark-1.6.0-bin-hadoop2.6/lib/spark-csv_2.10-1.3.0.jar,/s/god/spark-1.6.0-bin-hadoop2.6/lib/commons-csv-1.2.jar --master yarn-client --num-executors 20 --executor-cores 8 --executor-memory 24g --driver-memory 8g`

And do the following

`scala> val trainSchema = StructType(Array(StructField("ID", IntegerType, true), StructField("ID", DoubleType, true)))`

`scala> val a = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("nullValue", "null").schema(trainSchema).load("/user/god/test_data.csv")
`
and

`scala> a.show()
`
causes the following error:

`java.text.ParseException: Unparseable number: "null"`

**Comment by HyukjinKwon** [comment]
It looks the problem is that the fields in the schema is not set currently.

it looks working fine. Would you try the codes below?

- codes

```scala
val schema = StructType(
  Array(
    StructField("id", IntegerType, true),
    StructField("value", DoubleType, true)))
val results = sqlContext
  .read
  .format("com.databricks.spark.csv")
  .option("header", "true")
  .option("nullValue", "null")
  .schema(schema)
  .load("/user/god/test_data.csv")
results.show()
```

- output

```
+---+-----+
| id|value|
+---+-----+
|  1| null|
|  1| null|
|  1| null|
|  1| null|
|  1| null|
|  2|  2.0|
|  2|  2.1|
|  2|  3.1|
|  2|  3.8|
|  3| null|
|  3| null|
|  3| null|
|  3|  4.0|
|  3| null|
|  3|  2.0|
|  3|  2.0|
|  3| null|
+---+-----+
```

**Comment by amitmohanty** [comment]
I think I am still having the same problem. The complete error messages are here:

```scala

scala> import org.apache.spark.sql.types._
import org.apache.spark.sql.types._

scala> val mySchema = StructType(Array(StructField("id", IntegerType, true), StructField("value", DoubleType, true)))
mySchema: org.apache.spark.sql.types.StructType = StructType(StructField(id,IntegerType,true), StructField(value,DoubleType,true))

scala> val results = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("nullValue","null").schema(mySchema).load("test_data.csv")
results: org.apache.spark.sql.DataFrame = [id: int, value: double]

scala> results.show()
16/03/09 21:08:48 INFO storage.MemoryStore: Block broadcast_0 stored as values in memory (estimated size 246.0 KB, free 246.0 KB)
16/03/09 21:08:48 INFO storage.MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 24.9 KB, free 271.0 KB)
16/03/09 21:08:48 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on 19.1.2.67:34256 (size: 24.9 KB, free: 5.5 GB)
16/03/09 21:08:48 INFO spark.SparkContext: Created broadcast 0 from textFile at TextFile.scala:30
16/03/09 21:08:48 INFO mapred.FileInputFormat: Total input paths to process : 1
16/03/09 21:08:48 INFO spark.SparkContext: Starting job: take at CsvRelation.scala:249
16/03/09 21:08:48 INFO scheduler.DAGScheduler: Got job 0 (take at CsvRelation.scala:249) with 1 output partitions
16/03/09 21:08:48 INFO scheduler.DAGScheduler: Final stage: ResultStage 0 (take at CsvRelation.scala:249)
16/03/09 21:08:48 INFO scheduler.DAGScheduler: Parents of final stage: List()
16/03/09 21:08:48 INFO scheduler.DAGScheduler: Missing parents: List()
16/03/09 21:08:48 INFO scheduler.DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[1] at textFile at TextFile.scala:30), which has no missing parents
16/03/09 21:08:48 INFO storage.MemoryStore: Block broadcast_1 stored as values in memory (estimated size 3.1 KB, free 274.0 KB)
16/03/09 21:08:48 INFO storage.MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 1814.0 B, free 275.8 KB)
16/03/09 21:08:48 INFO storage.BlockManagerInfo: Added broadcast_1_piece0 in memory on 19.1.2.67:34256 (size: 1814.0 B, free: 5.5 GB)
16/03/09 21:08:48 INFO spark.SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1006
16/03/09 21:08:48 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[1] at textFile at TextFile.scala:30)
16/03/09 21:08:48 INFO cluster.YarnScheduler: Adding task set 0.0 with 1 tasks
16/03/09 21:08:48 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, hpce3r05n25.hpc.hello-there.com, partition 0,RACK_LOCAL, 2267 bytes)
16/03/09 21:08:48 INFO storage.BlockManagerInfo: Added broadcast_1_piece0 in memory on hpce3r05n25.hpc.hello-there.com:38583 (size: 1814.0 B, free: 17.0 GB)
16/03/09 21:08:48 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on hpce3r05n25.hpc.hello-there.com:38583 (size: 24.9 KB, free: 17.0 GB)
16/03/09 21:08:49 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 1126 ms on hpce3r05n25.hpc.hello-there.com (1/1)
16/03/09 21:08:49 INFO cluster.YarnScheduler: Removed TaskSet 0.0, whose tasks have all completed, from pool
16/03/09 21:08:49 INFO scheduler.DAGScheduler: ResultStage 0 (take at CsvRelation.scala:249) finished in 1.133 s
16/03/09 21:08:49 INFO scheduler.DAGScheduler: Job 0 finished: take at CsvRelation.scala:249, took 1.249243 s
16/03/09 21:08:49 INFO spark.SparkContext: Starting job: take at CsvRelation.scala:249
16/03/09 21:08:49 INFO scheduler.DAGScheduler: Got job 1 (take at CsvRelation.scala:249) with 1 output partitions
16/03/09 21:08:49 INFO scheduler.DAGScheduler: Final stage: ResultStage 1 (take at CsvRelation.scala:249)
16/03/09 21:08:49 INFO scheduler.DAGScheduler: Parents of final stage: List()
16/03/09 21:08:49 INFO scheduler.DAGScheduler: Missing parents: List()
16/03/09 21:08:49 INFO scheduler.DAGScheduler: Submitting ResultStage 1 (MapPartitionsRDD[1] at textFile at TextFile.scala:30), which has no missing parents
16/03/09 21:08:49 INFO storage.MemoryStore: Block broadcast_2 stored as values in memory (estimated size 3.1 KB, free 278.9 KB)
16/03/09 21:08:49 INFO storage.MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 1809.0 B, free 280.7 KB)
16/03/09 21:08:49 INFO storage.BlockManagerInfo: Added broadcast_2_piece0 in memory on 19.1.2.67:34256 (size: 1809.0 B, free: 5.5 GB)
16/03/09 21:08:49 INFO spark.SparkContext: Created broadcast 2 from broadcast at DAGScheduler.scala:1006
16/03/09 21:08:49 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 1 (MapPartitionsRDD[1] at textFile at TextFile.scala:30)
16/03/09 21:08:49 INFO cluster.YarnScheduler: Adding task set 1.0 with 1 tasks
16/03/09 21:08:49 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 1.0 (TID 1, hpce3r05n25.hpc.hello-there.com, partition 1,RACK_LOCAL, 2267 bytes)
16/03/09 21:08:49 INFO storage.BlockManagerInfo: Added broadcast_2_piece0 in memory on hpce3r05n25.hpc.hello-there.com:38583 (size: 1809.0 B, free: 17.0 GB)
16/03/09 21:08:49 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 1.0 (TID 1) in 42 ms on hpce3r05n25.hpc.hello-there.com (1/1)
16/03/09 21:08:49 INFO scheduler.DAGScheduler: ResultStage 1 (take at CsvRelation.scala:249) finished in 0.042 s
16/03/09 21:08:49 INFO cluster.YarnScheduler: Removed TaskSet 1.0, whose tasks have all completed, from pool
16/03/09 21:08:49 INFO scheduler.DAGScheduler: Job 1 finished: take at CsvRelation.scala:249, took 0.049885 s
16/03/09 21:08:49 INFO storage.MemoryStore: Block broadcast_3 stored as values in memory (estimated size 246.1 KB, free 526.7 KB)
16/03/09 21:08:49 INFO storage.MemoryStore: Block broadcast_3_piece0 stored as bytes in memory (estimated size 24.9 KB, free 551.7 KB)
16/03/09 21:08:49 INFO storage.BlockManagerInfo: Added broadcast_3_piece0 in memory on 19.1.2.67:34256 (size: 24.9 KB, free: 5.5 GB)
16/03/09 21:08:49 INFO spark.SparkContext: Created broadcast 3 from textFile at TextFile.scala:30
16/03/09 21:08:49 INFO mapred.FileInputFormat: Total input paths to process : 1
16/03/09 21:08:49 INFO spark.SparkContext: Starting job: show at <console>:36
16/03/09 21:08:49 INFO scheduler.DAGScheduler: Got job 2 (show at <console>:36) with 1 output partitions
16/03/09 21:08:49 INFO scheduler.DAGScheduler: Final stage: ResultStage 2 (show at <console>:36)
16/03/09 21:08:49 INFO scheduler.DAGScheduler: Parents of final stage: List()
16/03/09 21:08:49 INFO scheduler.DAGScheduler: Missing parents: List()
16/03/09 21:08:49 INFO scheduler.DAGScheduler: Submitting ResultStage 2 (MapPartitionsRDD[7] at show at <console>:36), which has no missing parents
16/03/09 21:08:49 INFO storage.MemoryStore: Block broadcast_4 stored as values in memory (estimated size 6.8 KB, free 558.5 KB)
16/03/09 21:08:49 INFO storage.MemoryStore: Block broadcast_4_piece0 stored as bytes in memory (estimated size 3.8 KB, free 562.3 KB)
16/03/09 21:08:49 INFO storage.BlockManagerInfo: Added broadcast_4_piece0 in memory on 19.1.2.67:34256 (size: 3.8 KB, free: 5.5 GB)
16/03/09 21:08:49 INFO spark.SparkContext: Created broadcast 4 from broadcast at DAGScheduler.scala:1006
16/03/09 21:08:49 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 2 (MapPartitionsRDD[7] at show at <console>:36)
16/03/09 21:08:49 INFO cluster.YarnScheduler: Adding task set 2.0 with 1 tasks
16/03/09 21:08:49 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 2.0 (TID 2, hpce3r05n25.hpc.hello-there.com, partition 0,RACK_LOCAL, 2267 bytes)
16/03/09 21:08:49 INFO storage.BlockManagerInfo: Added broadcast_4_piece0 in memory on hpce3r05n25.hpc.hello-there.com:38583 (size: 3.8 KB, free: 17.0 GB)
16/03/09 21:08:50 INFO storage.BlockManagerInfo: Added broadcast_3_piece0 in memory on hpce3r05n25.hpc.hello-there.com:38583 (size: 24.9 KB, free: 17.0 GB)
16/03/09 21:08:50 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 2.0 (TID 2, hpce3r05n25.hpc.hello-there.com): java.text.ParseException: Unparseable number: "null"
        at java.text.NumberFormat.parse(NumberFormat.java:385)
        at com.databricks.spark.csv.util.TypeCast$$anonfun$castTo$4.apply$mcD$sp(TypeCast.scala:58)
        at com.databricks.spark.csv.util.TypeCast$$anonfun$castTo$4.apply(TypeCast.scala:58)
        at com.databricks.spark.csv.util.TypeCast$$anonfun$castTo$4.apply(TypeCast.scala:58)
        at scala.util.Try.getOrElse(Try.scala:77)
        at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:58)
        at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:118)
        at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:104)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:308)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
        at scala.collection.AbstractIterator.to(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

16/03/09 21:08:50 INFO scheduler.TaskSetManager: Starting task 0.1 in stage 2.0 (TID 3, hpce3r05n25.hpc.hello-there.com, partition 0,RACK_LOCAL, 2267 bytes)
16/03/09 21:08:50 INFO scheduler.TaskSetManager: Lost task 0.1 in stage 2.0 (TID 3) on executor hpce3r05n25.hpc.hello-there.com: java.text.ParseException (Unparseable number: "null") [duplicate 1]
16/03/09 21:08:50 INFO scheduler.TaskSetManager: Starting task 0.2 in stage 2.0 (TID 4, hpce3r05n25.hpc.hello-there.com, partition 0,RACK_LOCAL, 2267 bytes)
16/03/09 21:08:50 INFO scheduler.TaskSetManager: Lost task 0.2 in stage 2.0 (TID 4) on executor hpce3r05n25.hpc.hello-there.com: java.text.ParseException (Unparseable number: "null") [duplicate 2]
16/03/09 21:08:50 INFO scheduler.TaskSetManager: Starting task 0.3 in stage 2.0 (TID 5, hpce3r05n25.hpc.hello-there.com, partition 0,RACK_LOCAL, 2267 bytes)
16/03/09 21:08:50 INFO scheduler.TaskSetManager: Lost task 0.3 in stage 2.0 (TID 5) on executor hpce3r05n25.hpc.hello-there.com: java.text.ParseException (Unparseable number: "null") [duplicate 3]
16/03/09 21:08:50 ERROR scheduler.TaskSetManager: Task 0 in stage 2.0 failed 4 times; aborting job
16/03/09 21:08:50 INFO cluster.YarnScheduler: Removed TaskSet 2.0, whose tasks have all completed, from pool
16/03/09 21:08:50 INFO cluster.YarnScheduler: Cancelling stage 2
16/03/09 21:08:50 INFO scheduler.DAGScheduler: ResultStage 2 (show at <console>:36) failed in 0.629 s
16/03/09 21:08:50 INFO scheduler.DAGScheduler: Job 2 failed: show at <console>:36, took 0.640024 s
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 4 times, most recent failure: Lost task 0.3 in stage 2.0 (TID 5, hpce3r05n25.hpc.hello-there.com): java.text.ParseException: Unparseable number: "null"
        at java.text.NumberFormat.parse(NumberFormat.java:385)
        at com.databricks.spark.csv.util.TypeCast$$anonfun$castTo$4.apply$mcD$sp(TypeCast.scala:58)
        at com.databricks.spark.csv.util.TypeCast$$anonfun$castTo$4.apply(TypeCast.scala:58)
        at com.databricks.spark.csv.util.TypeCast$$anonfun$castTo$4.apply(TypeCast.scala:58)
        at scala.util.Try.getOrElse(Try.scala:77)
        at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:58)
        at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:118)
        at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:104)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:308)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
        at scala.collection.AbstractIterator.to(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at scala.Option.foreach(Option.scala:236)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1858)
        at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:212)
        at org.apache.spark.sql.execution.Limit.executeCollect(basicOperators.scala:165)
        at org.apache.spark.sql.execution.SparkPlan.executeCollectPublic(SparkPlan.scala:174)
        at org.apache.spark.sql.DataFrame$$anonfun$org$apache$spark$sql$DataFrame$$execute$1$1.apply(DataFrame.scala:1538)
        at org.apache.spark.sql.DataFrame$$anonfun$org$apache$spark$sql$DataFrame$$execute$1$1.apply(DataFrame.scala:1538)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:56)
        at org.apache.spark.sql.DataFrame.withNewExecutionId(DataFrame.scala:2125)
        at org.apache.spark.sql.DataFrame.org$apache$spark$sql$DataFrame$$execute$1(DataFrame.scala:1537)
        at org.apache.spark.sql.DataFrame.org$apache$spark$sql$DataFrame$$collect(DataFrame.scala:1544)
        at org.apache.spark.sql.DataFrame$$anonfun$head$1.apply(DataFrame.scala:1414)
        at org.apache.spark.sql.DataFrame$$anonfun$head$1.apply(DataFrame.scala:1413)
        at org.apache.spark.sql.DataFrame.withCallback(DataFrame.scala:2138)
        at org.apache.spark.sql.DataFrame.head(DataFrame.scala:1413)
        at org.apache.spark.sql.DataFrame.take(DataFrame.scala:1495)
        at org.apache.spark.sql.DataFrame.showString(DataFrame.scala:171)
        at org.apache.spark.sql.DataFrame.show(DataFrame.scala:394)
        at org.apache.spark.sql.DataFrame.show(DataFrame.scala:355)
        at org.apache.spark.sql.DataFrame.show(DataFrame.scala:363)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:36)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:41)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:43)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:45)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:47)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:49)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:51)
        at $iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:53)
        at $iwC$$iwC$$iwC$$iwC.<init>(<console>:55)
        at $iwC$$iwC$$iwC.<init>(<console>:57)
        at $iwC$$iwC.<init>(<console>:59)
        at $iwC.<init>(<console>:61)
        at <init>(<console>:63)
        at .<init>(<console>:67)
        at .<clinit>(<console>)
        at .<init>(<console>:7)
        at .<clinit>(<console>)
        at $print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1065)
        at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1346)
        at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:840)
        at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:871)
        at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:819)
        at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:857)
        at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:902)
        at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:814)
        at org.apache.spark.repl.SparkILoop.processLine$1(SparkILoop.scala:657)
        at org.apache.spark.repl.SparkILoop.innerLoop$1(SparkILoop.scala:665)
        at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$loop(SparkILoop.scala:670)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply$mcZ$sp(SparkILoop.scala:997)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
        at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
        at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$process(SparkILoop.scala:945)
        at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1059)
        at org.apache.spark.repl.Main$.main(Main.scala:31)
        at org.apache.spark.repl.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.text.ParseException: Unparseable number: "null"
        at java.text.NumberFormat.parse(NumberFormat.java:385)
        at com.databricks.spark.csv.util.TypeCast$$anonfun$castTo$4.apply$mcD$sp(TypeCast.scala:58)
        at com.databricks.spark.csv.util.TypeCast$$anonfun$castTo$4.apply(TypeCast.scala:58)
        at com.databricks.spark.csv.util.TypeCast$$anonfun$castTo$4.apply(TypeCast.scala:58)
        at scala.util.Try.getOrElse(Try.scala:77)
        at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:58)
        at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:118)
        at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:104)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:308)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
        at scala.collection.AbstractIterator.to(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)


scala>


```

**Comment by weichen1984** [comment]
Looking at your code, you are using spark csv 1.3.0. Try using 1.4.0 to see if this goes away.

**Comment by HyukjinKwon** [comment]
Yes. This was fixed in 1.4.0, https://github.com/databricks/spark-csv/pull/224. I think we can close this.
