### ISSUE TITLE
Unable to load CSV file from S3 bucket 

### ISSUE THREAD

**Issue by pranita-s** [databricks/spark-csv#297]
Hi !
I am facing problems in loading CSV file from S3 bucket using read.df() function.
read.csv() is working but as its slow I wish to use read.df(). 

I have 1 master and 2 slaves.
The values of AWS Key Id and Secret Key is present in core-site.xml file.
Code:
library("SparkR",lib.loc="/root/spark/R/lib")
Sys.setenv(SPARK_HOME="/root/spark")
sc<- sparkR.init(sparkPackages="com.databricks:spark-csv_2.11:1.0.3")
sqlContext<- sparkRSQL.init(sc)
data_sparkrdf<- read.df(sqlContext,"s3n://xxxxx:xxxxx@s3-ap-southeast-1.amazonaws.com/foldername/filename.csv",source="com.databricks.spark.csv")

Error:
16/03/18 05:10:49 INFO storage.MemoryStore: Block broadcast_11 stored as values in memory (estimated size 88.1 KB, free 463.2 KB)
16/03/18 05:10:49 INFO storage.MemoryStore: Block broadcast_11_piece0 stored as bytes in memory (estimated size 5.6 KB, free 468.9 KB)
16/03/18 05:10:49 INFO storage.BlockManagerInfo: Added broadcast_11_piece0 in memory on 172.31.21.194:39882 (size: 5.6 KB, free: 511.5 MB)
16/03/18 05:10:49 INFO spark.SparkContext: Created broadcast 11 from textFile at CsvRelation.scala:114
16/03/18 05:10:50 ERROR r.RBackendHandler: loadDF on org.apache.spark.sql.api.r.SQLUtils failed
Error in invokeJava(isStatic = TRUE, className, methodName, ...) : 
  org.apache.hadoop.fs.s3.S3Exception: org.jets3t.service.S3ServiceException: S3 HEAD request failed for '/foldername%2Ffilename.csv' - ResponseCode=403, ResponseMessage=Forbidden
	at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.handleServiceException(Jets3tNativeFileSystemStore.java:229)
	at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.retrieveMetadata(Jets3tNativeFileSystemStore.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:85)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:62)
	at org.apache.hadoop.fs.s3native.$Proxy14.retrieveMetadata(Unknown Source)
	

Please help to resolve it ! Thanks in advance !

**Comment by sundi133** [comment]
@pranita-s i am facing the same issue, do you remember how you got it resolved ?

**Comment by pranita-s** [comment]
@sundi133 I mistake was inclusion of "s3-ap-southeast-1.amazonaws.com"

Just do this, it will be resolved 
data_sparkrdf<- read.df(sqlContext,"s3n://xxxxx:xxxxx@foldername/filename.csv",source="com.databricks.spark.csv")
Don't forget to make folder public.
