### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.databricks.spark.csv.util.CompressionCodecs$

### ISSUE THREAD

**Issue by AEDWIP** [databricks/spark-csv#303]
## I use Jupyter python3 notebook. I am running spark-1.6.1-bin-hadoop2.6

Here is the script I use to start pyspark with the  spark-csv package
```
#!/bin/sh 

# packages are ',' seperate with no white space
extraPkgs="--packages com.databricks:spark-csv_2.11:1.4.0,datastax:spark-cassandra-connector:1.6.0-M1-s_2.10"

export PYSPARK_PYTHON=python3
export PYSPARK_DRIVER_PYTHON=python3
IPYTHON_OPTS=notebook $SPARK_ROOT/bin/pyspark $extraPkgs --conf spark.cassandra.connection.host=ec2-53-152-102-222.us-west-1.compute.amazonaws.com $*
```

## my python code and stack trace are bellow

Kind regards

Andy

In [16]:

```
#https://github.com/databricks/spark-csv#python-api
outputFile = "./AEDWIP_explore.csv"
df3.write.format('com.databricks.spark.csv').save(outputFile)
```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-16-2853d8f0cb32> in <module>()
      1 #https://github.com/databricks/spark-csv#python-api
      2 outputFile = "./AEDWIP_explore.csv"
----> 3 df3.write.format('com.databricks.spark.csv').save(outputFile)

/Users/andrewdavidson/workSpace/spark/spark-1.6.1-bin-hadoop2.6/python/pyspark/sql/readwriter.py in save(self, path, format, mode, partitionBy, **options)
    395             self._jwrite.save()
    396         else:
--> 397             self._jwrite.save(path)
    398 
    399     @since(1.4)

/Users/andrewdavidson/workSpace/spark/spark-1.6.1-bin-hadoop2.6/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
    811         answer = self.gateway_client.send_command(command)
    812         return_value = get_return_value(
--> 813             answer, self.gateway_client, self.target_id, self.name)
    814 
    815         for temp_arg in temp_args:

/Users/andrewdavidson/workSpace/spark/spark-1.6.1-bin-hadoop2.6/python/pyspark/sql/utils.py in deco(*a, **kw)
     43     def deco(*a, **kw):
     44         try:
---> 45             return f(*a, **kw)
     46         except py4j.protocol.Py4JJavaError as e:
     47             s = e.java_exception.toString()

/Users/andrewdavidson/workSpace/spark/spark-1.6.1-bin-hadoop2.6/python/lib/py4j-0.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    306                 raise Py4JJavaError(
    307                     "An error occurred while calling {0}{1}{2}.\n".
--> 308                     format(target_id, ".", name), value)
    309             else:
    310                 raise Py4JError(

Py4JJavaError: An error occurred while calling o158.save.
: java.lang.NoClassDefFoundError: Could not initialize class com.databricks.spark.csv.util.CompressionCodecs$
	at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:189)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:745)

**Comment by AEDWIP** [comment]
using the version 1.3 syntax and using --packages com.databricks:spark-csv_2.11:1.3.0 works
df3.write.save(outputURLHDFS, 'com.databricks.spark.csv', header = 'true')

I tried version 1.4 and version 1.3 syntax with com.databricks:spark-csv_2.11:1.4.0 and got the error listed in original bug report

kind regards

Andy

**Comment by eyadsibai** [comment]
+1

**Comment by jomach** [comment]
+1

**Comment by gourav-sg** [comment]
+1

**Comment by nalingarg2** [comment]
+1

**Comment by mikekaminsky** [comment]
+1

**Comment by falaki** [comment]
Thanks for reporting. Looking into it.

**Comment by falaki** [comment]
The error relates to using different version of Scala. Make sure you use spark-csv compiled with scala 2.10 if your spark jars are 2.10.

**Comment by skunkwerk** [comment]
Which pre-built version of Spark will work with spark-csv 2.11?  As it doesn't work with 1.6.1 pre-built for Hadoop.
Or do I have to compile Spark myself to use with this library?

**Comment by HyukjinKwon** [comment]
@skunkwerk Have you tried versions compiled by both `2.11` and `2.10`?

**Comment by HimanshuBabbar** [comment]
I have spark-sql_2.11 ver 1.6.0 and spark-csv_2.11. I have tried with 1.2.0, 1.3.0. and 1.40. and am still  getting the same classNotFoundException. Any suggestions?

**Comment by MostafaAlaa2016** [comment]
+1

**Comment by gourav-sg** [comment]
Hi,

I am super confused about this. Its been six months or so I guess and csv
is already prebuilt in to SPARK.

Can you please show the output of sparkSession.version?

Regards,
Gourav Sengupta
