### ISSUE TITLE
CsvRelation$: Exception while parsing line:..... when using limit operation 

### ISSUE THREAD

**Issue by nivemaham** [databricks/spark-csv#316]
I am getting following exception when i perform a df.limit(1000) on a DataFrame created which has empty value, where as i don't get any exception when i don't perform limit() operation. 
```
16/04/26 13:26:01 ERROR CsvRelation$: Exception while parsing line: 07/04/2015,Credit reporting,,Incorrect information on credit report,Account terms,"Creditor Contact DetailsXXXX XXXX, WIXXXX ( XXXX ) XXXX purchased an item at XXXX, My credit limit is {$100.00}, I told the cashier that, I told her I would pay the remaining balance that exceeding {$100.00} in cash. I did that. When I got the bill it was {$110.00}, which I paid in full before the due date. Now I find it lowered my credit score to no fault of my own. . 
java.io.IOException: (startline 1) EOF reached before encapsulated token finished
	at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Lexer.java:282)
	at org.apache.commons.csv.Lexer.nextToken(Lexer.java:152)
	at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:498)
	at org.apache.commons.csv.CSVParser.getRecords(CSVParser.java:365)
	at com.databricks.spark.csv.CsvRelation$$anonfun$com$databricks$spark$csv$CsvRelation$$parseCSV$1.apply(CsvRelation.scala:301)
	at com.databricks.spark.csv.CsvRelation$$anonfun$com$databricks$spark$csv$CsvRelation$$parseCSV$1.apply(CsvRelation.scala:299)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
```

The code which works fine is
```
  def makeDataSet(dataPath: String): DataFrame = {
    this.filename = dataPath
     sqlContext.read
      .format("com.databricks.spark.csv")
      .option("header", "true")
      .option("treatEmptyValuesAsNulls", "true" )
      .load(dataPath).na.fill("NA")
  }
```
The code which fails is 
```
  def makeDataSet(dataPath: String): DataFrame = {
    val df =sqlContext.read
      .format("com.databricks.spark.csv")
      .option("header", "true")
      .option("treatEmptyValuesAsNulls", "true" )
      .load(dataPath).na.fill("NA")

    df.limit(2000) // returns a new DF 
  }
```

Can anyone help me with this? (This is the first time i am trying with a dataset which has empty values. What should be the proper way to create base dataframe to perform other data cleaning operations on top of it provided the input files can contain empty values)

**Comment by HyukjinKwon** [comment]
I suspect an issue at Apache Common CSV. Do you mind if I ask the data? I want to reproduce.

**Comment by nivemaham** [comment]
Hi 
It is an open data, i downloaded the csv file from here [https://catalog.data.gov/dataset/consumer-complaint-database](https://catalog.data.gov/dataset/consumer-complaint-database)

**Comment by falaki** [comment]
Can you try using univocity parser?
```option("parserLib", "univocity")```

**Comment by nivemaham** [comment]
Thanks falaki. It works.
The working solution is 
```
  def makeDataSet(dataPath: String): DataFrame = {
    val df =sqlContext.read
      .format("com.databricks.spark.csv")
      .option("header", "true")
      .option("treatEmptyValuesAsNulls", "true" )
      .option("parserLib", "univocity")
      .load(dataPath).na.fill("NA")

    df.limit(2000) // returns a new DF 
  }
```
