### ISSUE TITLE
NoSuchMethodError org.apache.commons.csv.CSVParser.parse

### ISSUE THREAD

**Issue by mbrio** [databricks/spark-csv#319]
I am trying to use the spark-csv library to read in data from a TSV file and I am unfortunately getting an exception when using the commons parserLib. I am able to get around this error when using the univocity parserLib, but I wanted to bring it to your attention. I am using scala 2.10, I am requiring it through my build.sbt file (`"com.databricks" %% "spark-csv" % "1.4.0"`), and I am building a fat jar utilizing `addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.3")` with the merge strategy: 

```
mergeStrategy in assembly <<= (mergeStrategy in assembly) { (old) =>
  {
    case m if m.toLowerCase.endsWith("manifest.mf") => MergeStrategy.discard
    case m if m.startsWith("META-INF") => MergeStrategy.discard
    case PathList("javax", "servlet", xs @ _*) => MergeStrategy.first
    case PathList("org", "apache", xs @ _*) => MergeStrategy.first
    case PathList("org", "jboss", xs @ _*) => MergeStrategy.first
    case "about.html"  => MergeStrategy.rename
    case "reference.conf" => MergeStrategy.concat
    case _ => MergeStrategy.first
  }
}
```

When I use the commons parserLib with the following code:

```
val schema = StructType(Array(
  StructField("user", StringType, false),
  StructField("following", StringType, false)
))

_kernel.sqlContext.read
  .format("com.databricks.spark.csv")
  .option("delimiter", "\t")
  .schema(schema)
  .load(path)
```

I get the following error:

```
6/04/27 09:35:46 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.NoSuchMethodError: org.apache.commons.csv.CSVParser.parse(Ljava/lang/String;Lorg/apache/commons/csv/CSVFormat;)Lorg/apache/commons/csv/CSVParser;
	at com.databricks.spark.csv.CsvRelation$$anonfun$com$databricks$spark$csv$CsvRelation$$parseCSV$1.apply(CsvRelation.scala:301)
	at com.databricks.spark.csv.CsvRelation$$anonfun$com$databricks$spark$csv$CsvRelation$$parseCSV$1.apply(CsvRelation.scala:299)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1$$anonfun$2.apply(TungstenAggregate.scala:88)
	at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1$$anonfun$2.apply(TungstenAggregate.scala:86)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Again, this goes away as soon as I switch over to univocity.

--mike

**Comment by HyukjinKwon** [comment]
I guess you just downloaded a jar without dependent jars. I rememeber I saw this exception when I try to do so.

**Comment by Naresh523** [comment]
@HyukjinKwon  
what are those other dependent jars required?

**Comment by HyukjinKwon** [comment]
Here, https://github.com/databricks/spark-csv/issues/326#issuecomment-218327620

I think most of such exceptions are caused by not matching Scala version or dependencies.

**Comment by Naresh523** [comment]
Issue resolved!

**Comment by saurabhkumar2015** [comment]
how was this issue resolved ?
