### ISSUE TITLE
dateFormat may not work in python (python 2.7, Spark 1.6.1)

### ISSUE THREAD

**Issue by 5ean** [databricks/spark-csv#323]
I use python to load csv to dataframe. I am also facing the datetime format issue.

here is my code:
df = sqlContext.read.format('com.databricks.spark.csv').options(header='true',dateFormat='dd/MM/yyyy HH:mm:ss').load('test.csv',schema = schema)

the timestamp is like this "19/08/2013 00:00:00'

for datetime, the type in Schema is TimestampType

Exception:
Caused by: java.lang.IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
        at java.sql.Timestamp.valueOf(Timestamp.java:235)
        at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:62)

**Comment by 5ean** [comment]
more info:

CSV:
```
Column1,Column2,Column3,Column4
1,string,1.11,19/03/2016 00:00:00
2,string,2.22,19/03/2016 00:00:00
3,string,3.33,19/03/2016 00:00:00
4,string,4.44,19/03/2016 00:00:00
```
Schema:
test_schema = StructType([
        StructField("Column1", IntegerType(), True),
        StructField("Column2", StringType(), True),
	StructField("Column3", FloatType(), True),
	StructField("Column4", TimestampType(), True)])

df = sqlContext.read.format('com.databricks.spark.csv').options(header='true',dateFormat='dd/MM/yyyy HH:mm:ss').load(r'File:///Users/user/test.csv',schema = test_schema)

exception:
```
Caused by: java.lang.IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
        at java.sql.Timestamp.valueOf(Timestamp.java:235)
        at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:62)
        at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:118)
        at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:104)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:308)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
        at scala.collection.AbstractIterator.to(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
```

**Comment by falaki** [comment]
DateTime format feature is not released yet. It is in master, and you can compile it.

**Comment by jerzygangi** [comment]
@falaki Is this issue closed yet?

**Comment by falaki** [comment]
Yes, the latest release includes an option to specify datetime format.
