### ISSUE TITLE
An error occurred while calling o43.save

### ISSUE THREAD

**Issue by hshteingart** [databricks/spark-csv#325]
Couldn't do the saving on python 3 with pyspark.
Added the depenedecies: 
```
os.environ[
    'PYSPARK_SUBMIT_ARGS'] = '--packages com.databricks:spark-csv_2.11:1.4.0 pyspark-shell'
```
and then I got the following error.

```    df.write.format('com.databricks.spark.csv').save(csv_output)
  File "C:\Spark\python\pyspark\sql\readwriter.py", line 397, in save
    self._jwrite.save(path)
  File "C:\Spark\python\lib\py4j-0.9-src.zip\py4j\java_gateway.py", line 813, in __call__
  File "C:\Spark\python\pyspark\sql\utils.py", line 45, in deco
    return f(*a, **kw)
  File "C:\Spark\python\lib\py4j-0.9-src.zip\py4j\protocol.py", line 308, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o43.save.
: java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
	at com.databricks.spark.csv.util.CompressionCodecs$.<init>(CompressionCodecs.scala:29)
	at com.databricks.spark.csv.util.CompressionCodecs$.<clinit>(CompressionCodecs.scala)
	at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:189)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by nchammas** [comment]
If you're using the default build of Spark 1.x, you need to use the Scala 2.10 version of the library, not 2.11.

```
com.databricks:spark-csv_2.10:1.4.0
```

The error message here could be more helpful...

**Comment by edevil** [comment]
I ran into this problem. @nchammas workaround did the trick.

**Comment by alonrolnik** [comment]
Me 2, Thanks @nchammas 👍

**Comment by nchammas** [comment]
@vlyubin - Is a better error message in these circumstances not practical? It would be good to get a brief comment, even if it's "Can't do anything about this now", when closing issues.
