### ISSUE TITLE
NoClassDefFoundError: org/apache/commons/csv/CSVFormat

### ISSUE THREAD

**Issue by kkarthik21** [databricks/spark-csv#326]
I am trying to use the spark-csv with Spark-Job-Server (SJS). I experience the below exception in latest version 1.4.0. I just downloaded from maven repo. 

Note : both spark-csv_2.10-1.4.0.jar and common-csv-1.2.jar are added in classpath of SJS and Spark.
```
java.lang.NoClassDefFoundError: org/apache/commons/csv/CSVFormat
	at com.databricks.spark.csv.package$.<init>(package.scala:27)
	at com.databricks.spark.csv.package$.<clinit>(package.scala)
	at com.databricks.spark.csv.CsvRelation.inferSchema(CsvRelation.scala:235)
	at com.databricks.spark.csv.CsvRelation.<init>(CsvRelation.scala:73)
	at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:162)
	at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:44)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:158)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:109)
	at spark.jobserver.BPUploadSchema.uploadSchema(BPUploadSchema.java:118)
	at spark.jobserver.UploadSchemaScala$.runJob(UploadSchemaScala.scala:33)
	at spark.jobserver.UploadSchemaScala$.runJob(UploadSchemaScala.scala:13)
	at spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:301)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.csv.CSVFormat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
```

Appreciate your advice!
---Karthik

**Comment by HyukjinKwon** [comment]
@kkarthik21 I believe you need to download the dependencies, univocity parser and Apache common csv, which are...http://search.maven.org/remotecontent?filepath=com/univocity/univocity-parsers/1.5.1/univocity-parsers-1.5.1.jar for univocity and http://search.maven.org/remotecontent?filepath=org/apache/commons/commons-csv/1.1/commons-csv-1.1.jar for Apache common csv.

**Comment by mjmhall** [comment]
I got the same error when using spark-csv_2.10-1.4.0.jar on spark 1.6.1, so I switched to the versions that the databricks community edition is using (spark-csv_2.10-1.3.2.jar, commons-csv-1.1.jar, univocity-parsers-1.5.1.jar) and spark-csv works fine now.

**Comment by kkarthik21** [comment]
@HyukjinKwon - Yes it works. Thanks!
@mjmhall  - We don't need to downgrade to 1.3.2. It's working in 1.4.0 after adding the dependencies

**Comment by HyukjinKwon** [comment]
Great!

**Comment by Naresh523** [comment]
@kkarthik21 @HyukjinKwon 
I'm facing the similar issue, i'm using common-csv 1.3/1.4 and univocity-parsers 2.1.2 but still i'm getting the same error. Can someone please help me out?

**Comment by Naresh523** [comment]
Should the CSVFormat class be found from univocity-parsers jar or from common-csv jar?
When i build the project, these two jars are there in the jar but not CSVFormat class in common-csv jar 
I have tried to pass these jars through spark-command too but, no luck :(

scala-library-2.10.5
spark-assembly_2.10-1.5.0-cdh5.5.0
spark-xml_2.10-0.2.0
spark-csv_2.10-1.4.0
common-csv-1.4
univocity-parsers-2.1.2

**Comment by Naresh523** [comment]
the spark-application is not able to find the common-csv jar, even though it has been added through spark-command  or included in as dependency.
Any ideas will be appreciated!

--Thanks,
Naresh.

**Comment by mjmhall** [comment]
Hi Naresh

Can you provide details of how you are registering the jar files please. Are you using spark-shell? Also it's worth checking to ensure the jar files exist on all the spark servers.

**Comment by Naresh523** [comment]
I have added these jars as dependency in maven and built it as uber jar.

**Comment by Naresh523** [comment]
Issue resolved! I didn't required univocity-parser, not sure why!

**Comment by ebuildy** [comment]
Here https://mvnrepository.com/artifact/com.databricks/spark-csv_2.10/1.5.0 it's saying compile dep: ``commons-csv`` and ``univocity-parsers`` ,  they should be included right?
