### ISSUE TITLE
Error while adding spark-csv library in pyspark through cmd

### ISSUE THREAD

**Issue by mahima221** [databricks/spark-csv#343]
I'm trying to add spark-csv library to use in my pyspark IDE (PyCharm). I have Spark 1.6.1 built for Hadoop 2.4.0 and Scala version 2.10.5. I'm getting following errors when I try to add it through cmd. I want to access spark-csv from IDE directly as well.

```
    C:\spark-1.6.1-bin-hadoop2.4>bin\pyspark --packages com.databricks:spark-csv_2.10:1.0.3
    Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    Ivy Default Cache set to: C:\Users\Mahima\.ivy2\cache
    The jars for the packages stored in: C:\Users\Mahima\.ivy2\jars
    :: loading settings :: url = jar:file:/C:/spark-1.6.1-bin-hadoop2.4/lib/spark-assembly-1.6.1-hadoop2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
    com.databricks#spark-csv_2.10 added as a dependency
    :: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
            confs: [default]
            found com.databricks#spark-csv_2.10;1.0.3 in central
            found org.apache.commons#commons-csv;1.1 in central
    downloading https://repo1.maven.org/maven2/com/databricks/spark-csv_2.10/1.0.3/spark-csv_2.10-1.0.3.jar ...
            [SUCCESSFUL ] com.databricks#spark-csv_2.10;1.0.3!spark-csv_2.10.jar (833ms)
    :: resolution report :: resolve 6592ms :: artifacts dl 857ms
            :: modules in use:
            com.databricks#spark-csv_2.10;1.0.3 from central in [default]
            org.apache.commons#commons-csv;1.1 from central in [default]
            ---------------------------------------------------------------------
            |                  |            modules            ||   artifacts   |
            |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
            ---------------------------------------------------------------------
            |      default     |   2   |   1   |   1   |   0   ||   2   |   1   |
            ---------------------------------------------------------------------
    :: retrieving :: org.apache.spark#spark-submit-parent
            confs: [default]
            1 artifacts copied, 1 already retrieved (54kB/60ms)
    16/06/22 20:42:02 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
    16/06/22 20:42:03 ERROR Shell: Failed to locate the winutils binary in the hadoop binary path
    java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
            at org.apache.hadoop.util.Shell.getQualifiedBinPath(Shell.java:318)
            at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:333)
            at org.apache.hadoop.util.Shell.<clinit>(Shell.java:326)
            at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:76)
            at org.apache.hadoop.security.Groups.parseStaticMapping(Groups.java:93)
            at org.apache.hadoop.security.Groups.<init>(Groups.java:77)
            at org.apache.hadoop.security.Groups.getUserToGroupsMappingService(Groups.java:240)
            at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:255)
            at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:232)
            at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:718)
            at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:703)
            at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:605)
            at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2160)
            at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2160)
            at scala.Option.getOrElse(Option.scala:120)
            at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2160)
            at org.apache.spark.SparkContext.<init>(SparkContext.scala:322)
            at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:59)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
            at java.lang.reflect.Constructor.newInstance(Unknown Source)
            at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:234)
            at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
            at py4j.Gateway.invoke(Gateway.java:214)
            at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:79)
            at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:68)
            at py4j.GatewayConnection.run(GatewayConnection.java:209)
            at java.lang.Thread.run(Unknown Source)
    16/06/22 20:42:26 WARN : Your hostname, Mahima resolves to a loopback/non-reachable address: fe80:0:0:0:4950:202:cee6:f31f%22, but we couldn't find any external IP address!
    16/06/22 20:42:28 ERROR SparkContext: Error initializing SparkContext.
    java.lang.NullPointerException
            at java.lang.ProcessBuilder.start(Unknown Source)
            at org.apache.hadoop.util.Shell.runCommand(Shell.java:445)
            at org.apache.hadoop.util.Shell.run(Shell.java:418)
            at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:650)
            at org.apache.hadoop.fs.FileUtil.chmod(FileUtil.java:873)
            at org.apache.hadoop.fs.FileUtil.chmod(FileUtil.java:853)
            at org.apache.spark.util.Utils$.fetchFile(Utils.scala:406)
            at org.apache.spark.SparkContext.addFile(SparkContext.scala:1386)
            at org.apache.spark.SparkContext.addFile(SparkContext.scala:1340)
            at org.apache.spark.SparkContext$$anonfun$15.apply(SparkContext.scala:491)
            at org.apache.spark.SparkContext$$anonfun$15.apply(SparkContext.scala:491)
            at scala.collection.immutable.List.foreach(List.scala:318)
            at org.apache.spark.SparkContext.<init>(SparkContext.scala:491)
            at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:59)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
            at java.lang.reflect.Constructor.newInstance(Unknown Source)
            at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:234)
            at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
            at py4j.Gateway.invoke(Gateway.java:214)
            at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:79)
            at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:68)
            at py4j.GatewayConnection.run(GatewayConnection.java:209)
            at java.lang.Thread.run(Unknown Source)
    16/06/22 20:42:28 WARN MetricsSystem: Stopping a MetricsSystem that is not running
    Traceback (most recent call last):
      File "C:\spark-1.6.1-bin-hadoop2.4\bin\..\python\pyspark\shell.py", line 43, in <module>
        sc = SparkContext(pyFiles=add_files)
      File "C:\spark-1.6.1-bin-hadoop2.4\python\pyspark\context.py", line 115, in __init__
        conf, jsc, profiler_cls)
      File "C:\spark-1.6.1-bin-hadoop2.4\python\pyspark\context.py", line 172, in _do_init
        self._jsc = jsc or self._initialize_context(self._conf._jconf)
      File "C:\spark-1.6.1-bin-hadoop2.4\python\pyspark\context.py", line 235, in _initialize_context
        return self._jvm.JavaSparkContext(jconf)
      File "C:\spark-1.6.1-bin-hadoop2.4\python\lib\py4j-0.9-src.zip\py4j\java_gateway.py", line 1064, in __call__
      File "C:\spark-1.6.1-bin-hadoop2.4\python\lib\py4j-0.9-src.zip\py4j\protocol.py", line 308, in get_return_value
    py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
    : java.lang.NullPointerException
            at java.lang.ProcessBuilder.start(Unknown Source)
            at org.apache.hadoop.util.Shell.runCommand(Shell.java:445)
            at org.apache.hadoop.util.Shell.run(Shell.java:418)
            at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:650)
            at org.apache.hadoop.fs.FileUtil.chmod(FileUtil.java:873)
            at org.apache.hadoop.fs.FileUtil.chmod(FileUtil.java:853)
            at org.apache.spark.util.Utils$.fetchFile(Utils.scala:406)
            at org.apache.spark.SparkContext.addFile(SparkContext.scala:1386)
            at org.apache.spark.SparkContext.addFile(SparkContext.scala:1340)
            at org.apache.spark.SparkContext$$anonfun$15.apply(SparkContext.scala:491)
            at org.apache.spark.SparkContext$$anonfun$15.apply(SparkContext.scala:491)
            at scala.collection.immutable.List.foreach(List.scala:318)
            at org.apache.spark.SparkContext.<init>(SparkContext.scala:491)
            at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:59)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
            at java.lang.reflect.Constructor.newInstance(Unknown Source)
            at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:234)
            at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
            at py4j.Gateway.invoke(Gateway.java:214)
            at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:79)
            at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:68)
            at py4j.GatewayConnection.run(GatewayConnection.java:209)
            at java.lang.Thread.run(Unknown Source)
    
    >>> from pyspark.sql import SQLContext
    >>> sqlcon = SQLContext(sc)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    NameError: name 'sc' is not defined
    >>> sqlcon = SQLContext()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: __init__() takes at least 2 arguments (1 given)
    >>>
```

Thanks in advance.

**Comment by vp4gb** [comment]
did you get the solution ?
