### ISSUE TITLE
support multiple dateFormats within same file

### ISSUE THREAD

**Issue by bruce-szalwinski** [databricks/spark-csv#356]
I see that if my dates and timestamps are in Date.valueOf() and Timestamp.valueOf() respectively, then I don't have to specify dateFormat.  I also see that if they are not in this format, then I can use the dateFormat option to specify the format.  What I'm running into is a file that contains both date fields and timestamp fields and neither one is in the standard format.  I can specify the format for one or the other, but I get parsing errors for the date field if I specify the timestamp format and i get invalid data for the timestamp field if I specify the date format.

Is there a way to specify multiple dateFormats?

This shows the parsing error when specifying the dateFormat for the timestamp.

`import org.apache.spark.sql.types.{StructType, StructField, StringType, IntegerType, DateType, TimestampType}

val schema = StructType(Array(
     StructField("id", IntegerType, true),
     StructField("dateField", DateType, true),
     StructField("timestampField", TimestampType, true)))
     
val df = sqlContext.read.
	format("com.databricks.spark.csv").
	schema(schema).
	option("delimiter", "|").
	option("dateFormat", "yyyy-MM-dd HH:mm:ss").
	option("inferSchema", "true").
	load("./date_and_timestamp.csv")`

And given input file that looks like:

`1|01-06-2016|2016-06-01 01:01:01`

I get exception:

`scala> df.show()
16/07/11 12:52:57 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.text.ParseException: Unparseable date: "01-06-2016"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:73)
	at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:120)
	at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:106)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:308)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
16/07/11 12:52:57 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, localhost): java.text.ParseException: Unparseable date: "01-06-2016"`

And this shows the problem if I specify the dateFormat for the date.

`val df = sqlContext.read.
	format("com.databricks.spark.csv").
	schema(schema).
	option("delimiter", "|").
	option("dateFormat", "dd-MM-yyyy").
	option("inferSchema", "true").
	load("./date_and_timestamp.csv")`

`scala> df.show()
+---+----------+--------------------+
| id| dateField|      timestampField|
+---+----------+--------------------+
|  1|2016-06-01|0006-12-07 00:00:...|
+---+----------+--------------------+
`

**Comment by Sree2015** [comment]
For this issue i have see the comments on previous pull request to support 3 different date formats. I have a requirement to deal with more than 3 formats in fact it depends on the number of different formats per table. Any suggests?

**Comment by bruce-szalwinski** [comment]
It's why I wasn't a fan of just supporting a fixed number of date formats.  Rather, I was a fan of supporting a list of date formats.  There was some concern that a comma delimited list might have a date format that itself contained a comma.  For that case, I was suggesting that the user be able to supply the delimiter and it defaults to a comma.

Perhaps this will sway the reviewers to support a list of formats :).  If so, I'll be happy to reopen the PR and have another go.

**Comment by falaki** [comment]
I suggest you file this as a Spark JIRA. I have put spark-csv package on maintenance mode. That is, not new or changing API will be merged. Only bug fixes and possibly performance improvements. 

That said, this use case is valid and I believe it can be addressed in latest version of CSV data source in upstream Spark. My suggested API is something like this;

```
val df = sqlContext.read.
    format("csv").
    schema(schema).
    option("delimiter", "|").
    option("dateFormat1", "dd-MM-yyyy").
    option("dateFormat2", "dd/MM/yyyy").
    option("dateFormat3", "dd-MM-yy").
    option("inferSchema", "true").
    load("date_and_timestamp.csv")
```

The advantage of having different numbered option names is that:
* they can be used in DDL:
```
CREATE TABLE cars 
USING csv
OPTIONS (path "date_and_timestamp.csv", header "true", inferSchema "true", dateFormat1 "dd-MM-yyyy", dateFormat2 "dd/MM/yyyy", dateFormat3 "dd-MM-yy")
```
* It is backwards compatible. 
* It does not require extra complexity in API to support parsing a list of format strings.

**Comment by Sree2015** [comment]
Sure, Thankyou

**Comment by pieterjanverbruggen** [comment]
I also have the same issue. I don't see a requirement for multiple date formats. You can always read them in as String. However the Date format will normally be different than the Timestamp format. Luckily for reading the solution is to not define a dateFormat, however for writing it will use the Timestamp format making it not possible to read in the data as a Date in a later phase. The perfect fix would be to have a timestampFormat option?

**Comment by osvyryd** [comment]
Hi @pieterjanverbruggen,

I see from your comment that it is possible to read date in String format. 
Could you give a hint how to do it? Is it a possibility to tell Spark to assume that dates are strings?

Best regards,
Olga

**Comment by pieterjanverbruggen** [comment]
@osvyryd Hi Olga, No you cannot tell Spark that a date is a string, as you will need to define one type only. Just read it in as a String instead of Date and do the conversion yourself...

**Comment by osvyryd** [comment]
Hello @pieterjanverbruggen,

Ok, thank you for the quick answer!

**Comment by cottrell** [comment]
If you don't think multiple date formats are a reasonable thing, it kind of begs the question as to why have *any* types at all besides string in read csv (which is a valid approach). 

falaki's suggestion above is good and really should have made it into the API by now.

**Comment by sumanentc** [comment]
Is multiple date format supported while reading from csv file.
val df = sqlContext.read.
    format("csv").
    schema(schema).
    option("delimiter", "|").
    option("dateFormat1", "dd-MM-yyyy","dd/MM/yyyy","dd-MM-yy").
    option("inferSchema", "false").
    load("date_and_timestamp.csv")
