### ISSUE TITLE
Too many bytes before delimiter

### ISSUE THREAD

**Issue by shashwat7** [databricks/spark-csv#363]
Hi all,

I am seeing very weird issue while loading a file from HDFS. My file in HDFS is `^` separated.

I've written this piece of code to load the data.
`    val bkg_pax_df = sqlContext.load("com.databricks.spark.csv", Sbr.booking_passenger,
      Map("path" -> dump_path,
        "header" -> "false",
        "mode" -> "DROPMALFORMED",
        "delimiter" -> "^",
        "charset" -> Charset.forName("US-ASCII").name()))`
I convert this dataframe to RDD, and perform several `filter`, `keyBy`, `map`, `join `operations on it.

Sometimes, the execution goes fine while sometimes it fails with 
`java.io.IOException: Too many bytes before delimiter: 2147483648
	at org.apache.hadoop.util.LineReader.readCustomLine(LineReader.java:347)
	at org.apache.hadoop.util.LineReader.readLine(LineReader.java:172)
	at org.apache.hadoop.mapred.LineRecordReader.<init>(LineRecordReader.java:134)
	at org.apache.hadoop.mapred.TextInputFormat.getRecordReader(TextInputFormat.java:67)
	at org.apache.spark.rdd.HadoopRDD$$anon$1.<init>(HadoopRDD.scala:236)
	at org.apache.spark.rdd.HadoopRDD.compute(HadoopRDD.scala:212)
	at org.apache.spark.rdd.HadoopRDD.compute(HadoopRDD.scala:101)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:70)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:242)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)`

It seems just as if re-arranging the code makes it change the behavior, I am not able to identify why sometimes it work and sometimes doesn't. Any leads to figure out why does this happen would be really helpful. Thanks.

Btw, I use spark-csv-1.30 and spark-1.3.0

**Comment by HyukjinKwon** [comment]
My guess is some of your files have different encodings (non-ascii compatible one). Could you double-check that maybe?
