### ISSUE TITLE
Spark 2.0.0 - Dot in column name causes reading csv to fail

### ISSUE THREAD

**Issue by anshbansal** [databricks/spark-csv#369]
I have a test csv 

> "id.1"
> ""
> ""

I am trying to read it using the following

```
import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;
import org.apache.spark.sql.SparkSession;

public class Main {

    public static void main(String[] args) {
        SparkSession spark = SparkSession
                .builder()
                .appName("my app")
                .getOrCreate();

        String filePath = "/home/aseem/test.csv";

        Dataset<Row> df = spark.read()
                .format("csv")
                .option("header", "true")
                .option("nullValue", "")
                .csv(filePath)
                ;

        df.show();
    }

}
```

It causes 

```
Exception in thread "main" org.apache.spark.sql.AnalysisException: Unable to resolve impressionid.1 given [impressionid.1];
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolve$1$$anonfun$apply$5.apply(LogicalPlan.scala:134)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolve$1$$anonfun$apply$5.apply(LogicalPlan.scala:134)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolve$1.apply(LogicalPlan.scala:133)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolve$1.apply(LogicalPlan.scala:129)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at org.apache.spark.sql.types.StructType.foreach(StructType.scala:95)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at org.apache.spark.sql.types.StructType.map(StructType.scala:95)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolve(LogicalPlan.scala:129)
        at org.apache.spark.sql.execution.datasources.FileSourceStrategy$.apply(FileSourceStrategy.scala:87)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:60)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:60)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:61)
        at org.apache.spark.sql.execution.SparkPlanner.plan(SparkPlanner.scala:47)
        at org.apache.spark.sql.execution.SparkPlanner$$anonfun$plan$1$$anonfun$apply$1.applyOrElse(SparkPlanner.scala:51)
        at org.apache.spark.sql.execution.SparkPlanner$$anonfun$plan$1$$anonfun$apply$1.applyOrElse(SparkPlanner.scala:48)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:301)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:301)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:300)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:298)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:298)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5.apply(TreeNode.scala:321)
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:179)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformChildren(TreeNode.scala:319)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:298)
        at org.apache.spark.sql.execution.SparkPlanner$$anonfun$plan$1.apply(SparkPlanner.scala:48)
        at org.apache.spark.sql.execution.SparkPlanner$$anonfun$plan$1.apply(SparkPlanner.scala:48)
```

**Comment by HyukjinKwon** [comment]
Yes, it is. Actually, this is a Spark issue. Please check out https://issues.apache.org/jira/browse/SPARK-16698

This will be fine from Spark 2.0.1!

**Comment by anshbansal** [comment]
Thanks for sharing that. Should I instead raise any new issues in Apache Spark JIRA if they relate to Spark 2.0.0 onwards?

I know this is going off-topic but does Spark follow a fixed release schedule or is it when the core contributors decide enough things have been changed?

**Comment by HyukjinKwon** [comment]
Yea, I think that'd make sense :). Please cc me in CSV related issues if you don't mind  (I am really interested in those)

**Comment by Denisevi4** [comment]
Is there a way to deal with this issue in the meantime before 2.0.1 is released?

**Comment by anshbansal** [comment]
@Denisevi4 In my case I found a way to change the upstream data. But you can write a simple program to manually replace the `.` to` _` before reading in spark.

**Comment by aminaaslam** [comment]
I am using spark 2.0.2 but still getting the same error. Is there any other setting that need to be done in spark conf?? 
Exception in thread "main" org.apache.spark.sql.AnalysisException: Cannot resolve column name "OnlineNewMerchCtryCntHourly.cnt.hour3" among (CardOperationsId, RunTimestamp, LOCAL_TIMESTAMP, TxnChannelCode, TxnSourceTypeCode, SourceSystemCode, AccountSourceUniqueId, CardId, CardSourceRefId, DeviceId, MerchantRefId, MerchantName, MerchantCategory, MerchantAddressLine1, MerchantAddressLine2, MerchantAddressLine3, MerchantCity, MerchantZone, MerchantPostalCode, MerchantCountryCode, IssuerRefId, AcquirerRefId, AcquirerCountryCode, AuthId, AuthTimestamp, AuthSource, AuthResponse, AuthResReasonCode, AuthAvailableCreditLimit, AmountOrig, CurrencyCodeOrig, AmountCashBack, AmountAccount, AmountBase, CurrencyCodeAccount, CurrencyCodeBase, CardFunction, CardType, CardNrOfflinePin, CardSequenceNumber, CardCreditLimitMonthly, CardCreditLimitWeekly, CardCreditLimitDaily, DvcPosEntryMode, DvcVerificationCap, OrgUnitCode, CustomerPresentIndicator, PosTerminalAttended, Secure3d, CvvMatch, ErrorCorrectFlag, PosConditionCode, PosCaptureCode, AvsResponseCode, AccountSourceRefId, TransactionLocation, OwnDevice, CardHolderName, Disposition, DeviceName, DeviceCategory, DeviceCity, DeviceZone, DevicePostalCode, DeviceCountryCode, ECommerceFlag, ProductIndicator, CreditDebitCode, MerchantFSA, DeviceFSA, PinIndicator, Fraud, Alerted, CardLimit, KnownATMLocation_df, KnownPOS81Merchant, DomesticGeoDistance, KnownCPMerchant_df, DomesticGeoTimeDiff, ATMMerchantGeoDistance, OnlineNewMerchCtryCntHourly.cnt.hour1, OnlineNewMerchCtryCntHourly.cnt.hour3, OnlineNewMerchCtryCntHourly.cnt.hour4, OnlineNewMerchCtryCntHourly.cnt.hour10, OnlineNewMerchCtryCntHourly.cnt.hour15, OnlineNewMerchCtryCntHourly.cnt.hour24, POSTerminalAttendedAuthAmount.acc.day.total, POSTerminalAttendedAuthAmount.acc.day.present, POSTerminalAttendedAuthAmount.acc.day.past1, POSTerminalAttendedAuthAmount.acc.day.past3, POSTerminalAttendedAuthAmount.acc.day.past10, POSTerminalAttendedAuthAmount.acc.day.past15, POSTerminalAttendedAuthAmount.acc.day.past29, HighRiskMCCAmount.acc.hour.total, HighRiskMCCAmount.acc.hour.present, HighRiskMCCAmount.acc.hour.past1, HighRiskMCCAmount.acc.hour.past3, HighRiskMCCAmount.acc.hour.past4, HighRiskMCCAmount.acc.hour.past10, HighRiskMCCAmount.acc.hour.past15, HighRiskMCCAmount.acc.hour.past23, POSSum.acc.month.total, POSSum.acc.month.present, HighRiskPOSCnt.cnt.hour.total, HighRiskPOSCnt.cnt.hour.present, HighRiskPOSCnt.cnt.hour.past1, HighRiskPOSCnt.cnt.hour.past3, HighRiskPOSCnt.cnt.hour.past4, HighRiskPOSCnt.cnt.hour.past10, HighRiskPOSCnt.cnt.hour.past15, HighRiskPOSCnt.cnt.hour.past24, HighRiskPOSCnt.cnt.hour.past29, FuelPumpCount.cnt.day.total, FuelPumpCount.cnt.day.present, FuelPumpCount.cnt.day.past1, FuelPumpCount.cnt.day.past3, FuelPumpCount.cnt.day.past10, FuelPumpCount.cnt.day.past15, FuelPumpCount.cnt.day.past29, CardNotPresentCardingCnt.cnt.day.total, CardNotPresentCardingCnt.cnt.day.present, CardNotPresentCardingCnt.cnt.day.past1, CardNotPresentCardingCnt.cnt.day.past3, CardNotPresentCardingCnt.cnt.day.past6, NotECommerceAuthAmount.acc.day.total, NotECommerceAuthAmount.acc.day.present, NotECommerceAuthAmount.acc.day.past1, NotECommerceAuthAmount.acc.day.past3, NotECommerceAuthAmount.acc.day.past10, NotECommerceAuthAmount.acc.day.past15, NotECommerceAuthAmount.acc.day.past29, HourlyAuthAmt.acc.hour1, HourlyAuthAmt.acc.hour3, HourlyAuthAmt.acc.hour4, HourlyAuthAmt.acc.hour10, HourlyAuthAmt.acc.hour15, HourlyAuthAmt.acc.hour25, CashAdvanceTransactionsAcc.acc.day.total, CashAdvanceTransactionsAcc.acc.day.present, CashAdvanceTransactionsAcc.acc.day.past1, CashAdvanceTransactionsAcc.acc.day.past3, CashAdvanceTransactionsAcc.acc.day.past10, CashAdvanceTransactionsAcc.acc.day.past15, CashAdvanceTransactionsAcc.acc.day.past29, NonEMVTransactionsCount.cnt.day.total, NonEMVTransactionsCount.cnt.day.present, NonEMVTransactionsCount.cnt.day.past1, NonEMVTransactionsCount.cnt.day.past3, NonEMVTransactionsCount.cnt.day.past10, NonEMVTransactionsCount.cnt.day.past15, NonEMVTransactionsCount.cnt.day.past29, NonEMVTransactionsAcc.acc.day.total, NonEMVTransactionsAcc.acc.day.present, NonEMVTransactionsAcc.acc.day.past1, NonEMVTransactionsAcc.acc.day.past3, NonEMVTransactionsAcc.acc.day.past10, NonEMVTransactionsAcc.acc.day.past15, NonEMVTransactionsAcc.acc.day.past29, CorporateNonEMVCardsCount.cnt.day.total, CorporateNonEMVCardsCount.cnt.day.present, CorporateNonEMVCardsCount.cnt.day.past1, CorporateNonEMVCardsCount.cnt.day.past3, CorporateNonEMVCardsCount.cnt.day.past10, CorporateNonEMVCardsCount.cnt.day.past15, CorporateNonEMVCardsCount.cnt.day.past29, DomesticAuthCounter.cnt.day.total, DomesticAuthCounter.cnt.day.present, DomesticAuthCounter.cnt.day.past1, DomesticAuthCounter.cnt.day.past3, DomesticAuthCounter.cnt.day.past10, DomesticAuthCounter.cnt.day.past15, DomesticAuthCounter.cnt.day.past29, CustomerNotPresentAuthAmount.acc.day.total, CustomerNotPresentAuthAmount.acc.day.present, CustomerNotPresentAuthAmount.acc.day.past1, CustomerNotPresentAuthAmount.acc.day.past3, CustomerNotPresentAuthAmount.acc.day.past10, CustomerNotPresentAuthAmount.acc.day.past15, CustomerNotPresentAuthAmount.acc.day.past29, ATMDepositCounter.cnt.day.total, ATMDepositCounter.cnt.day.present, ATMDepositCounter.cnt.day.past1, ATMDepositCounter.cnt.day.past3, ATMDepositCounter.cnt.day.past10, ATMDepositCounter.cnt.day.past15, ATMDepositCounter.cnt.day.past29, POSTerminalAttendedAuthCount.cnt.day.total, POSTerminalAttendedAuthCount.cnt.day.present, POSTerminalAttendedAuthCount.cnt.day.past1, POSTerminalAttendedAuthCount.cnt.day.past3, POSTerminalAttendedAuthCount.cnt.day.past10, POSTerminalAttendedAuthCount.cnt.day.past15, POSTerminalAttendedAuthCount.cnt.day.past29, CashAdvanceTransactionsCount.cnt.day.total, CashAdvanceTransactionsCount.cnt.day.present, CashAdvanceTransactionsCount.cnt.day.past1, CashAdvanceTransactionsCount.cnt.day.past3, CashAdvanceTransactionsCount.cnt.day.past10, CashAdvanceTransactionsCount.cnt.day.past15, CashAdvanceTransactionsCount.cnt.day.past29, OnlineNewMerchCtryCntDaily.cnt.day.total, OnlineNewMerchCtryCntDaily.cnt.day.present, OnlineNewMerchCtryCntDaily.cnt.day.past1, OnlineNewMerchCtryCntDaily.cnt.day.past3, OnlineNewMerchCtryCntDaily.cnt.day.past4, ECommerceAuthCount.cnt.day.total, ECommerceAuthCount.cnt.day.present, ECommerceAuthCount.cnt.day.past1, ECommerceAuthCount.cnt.day.past3, ECommerceAuthCount.cnt.day.past10, ECommerceAuthCount.cnt.day.past15, ECommerceAuthCount.cnt.day.past29, ATMHighRiskDebitCounter.cnt.day.total, ATMHighRiskDebitCounter.cnt.day.present, ATMHighRiskDebitCounter.cnt.day.past1, ATMHighRiskDebitCounter.cnt.day.past3, ATMHighRiskDebitCounter.cnt.day.past10, ATMHighRiskDebitCounter.cnt.day.past15, ATMHighRiskDebitCounter.cnt.day.past29, DomesticAuthCount.cnt.hour1, DomesticAuthCount.cnt.hour3, DomesticAuthCount.cnt.hour4, DomesticAuthCount.cnt.hour10, DomesticAuthCount.cnt.hour15, DomesticAuthCount.cnt.hour25, NotECommerceAuthCount.cnt.day.total, NotECommerceAuthCount.cnt.day.present, NotECommerceAuthCount.cnt.day.past1, NotECommerceAuthCount.cnt.day.past3, NotECommerceAuthCount.cnt.day.past10, NotECommerceAuthCount.cnt.day.past15, NotECommerceAuthCount.cnt.day.past29, EMVTransactionsCount.cnt.day.total, EMVTransactionsCount.cnt.day.present, EMVTransactionsCount.cnt.day.past1, EMVTransactionsCount.cnt.day.past3, EMVTransactionsCount.cnt.day.past10, EMVTransactionsCount.cnt.day.past15, EMVTransactionsCount.cnt.day.past29, CustomerNotPresentAuthCount.cnt.day.total, CustomerNotPresentAuthCount.cnt.day.present, CustomerNotPresentAuthCount.cnt.day.past1, CustomerNotPresentAuthCount.cnt.day.past3, CustomerNotPresentAuthCount.cnt.day.past10, CustomerNotPresentAuthCount.cnt.day.past15, CustomerNotPresentAuthCount.cnt.day.past29, OnlinePOSCountForever.cnt.present, ATMCashAdvanceLimitExceededAcc.acc.day.total, ATMCashAdvanceLimitExceededAcc.acc.day.present, ATMCashAdvanceLimitExceededAcc.acc.day.past1, ATMCashAdvanceLimitExceededAcc.acc.day.past3, ATMCashAdvanceLimitExceededAcc.acc.day.past10, ATMCashAdvanceLimitExceededAcc.acc.day.past15, ATMCashAdvanceLimitExceededAcc.acc.day.past29, CorporateNonEMVCardsAcc.acc.day.total, CorporateNonEMVCardsAcc.acc.day.present, CorporateNonEMVCardsAcc.acc.day.past1, CorporateNonEMVCardsAcc.acc.day.past3, CorporateNonEMVCardsAcc.acc.day.past10, CorporateNonEMVCardsAcc.acc.day.past15, CorporateNonEMVCardsAcc.acc.day.past29, SmallPOSAuthorizationCount.cnt.hour1, SmallPOSAuthorizationCount.cnt.hour3, SmallPOSAuthorizationCount.cnt.hour4, SmallPOSAuthorizationCount.cnt.hour10, SmallPOSAuthorizationCount.cnt.hour15, SmallPOSAuthorizationCount.cnt.hour24, HourlyAuthCnt.cnt.hour1, HourlyAuthCnt.cnt.hour3, HourlyAuthCnt.cnt.hour4, HourlyAuthCnt.cnt.hour10, HourlyAuthCnt.cnt.hour15, HourlyAuthCnt.cnt.hour25, InternationalAuthCounter.cnt.day.total, InternationalAuthCounter.cnt.day.present, InternationalAuthCounter.cnt.day.past1, InternationalAuthCounter.cnt.day.past3, InternationalAuthCounter.cnt.day.past10, InternationalAuthCounter.cnt.day.past15, InternationalAuthCounter.cnt.day.past29, POS_Count.cnt.day.total, POS_Count.cnt.day.present, POS_Count.cnt.day.past1, POS_Count.cnt.day.past3, POS_Count.cnt.day.past10, POS_Count.cnt.day.past15, POS_Count.cnt.day.past29, LowValueECommerceAuthCnt.cnt.day.total, LowValueECommerceAuthCnt.cnt.day.present, LowValueECommerceAuthCnt.cnt.day.past1, LowValueECommerceAuthCnt.cnt.day.past3, LowValueECommerceAuthCnt.cnt.day.past10, LowValueECommerceAuthCnt.cnt.day.past15, LowValueECommerceAuthCnt.cnt.day.past29, ConsecutiveChannelAndAmount.cnt.hour1, ConsecutiveChannelAndAmount.cnt.hour3, ConsecutiveChannelAndAmount.cnt.hour4, ConsecutiveChannelAndAmount.cnt.hour10, ConsecutiveChannelAndAmount.cnt.hour15, ConsecutiveChannelAndAmount.cnt.hour24, ATMDepositMax.max.day.total, ATMDepositMax.max.day.present, ATMDepositMax.max.day.past1, ATMDepositMax.max.day.past3, ATMDepositMax.max.day.past4, POSInternationalCnt.cnt.week.total, POSInternationalCnt.cnt.week.present, POSInternationalCnt.cnt.week.past1, POSInternationalCnt.cnt.week.past3, OnlineNewMerchCtryAmtDaily.acc.day.total, OnlineNewMerchCtryAmtDaily.acc.day.present, OnlineNewMerchCtryAmtDaily.acc.day.past1, OnlineNewMerchCtryAmtDaily.acc.day.past3, OnlineNewMerchCtryAmtDaily.acc.day.past4, ATMCashAdvanceLimitExceededCount.cnt.day.total, ATMCashAdvanceLimitExceededCount.cnt.day.present, ATMCashAdvanceLimitExceededCount.cnt.day.past1, ATMCashAdvanceLimitExceededCount.cnt.day.past3, ATMCashAdvanceLimitExceededCount.cnt.day.past10, ATMCashAdvanceLimitExceededCount.cnt.day.past15, ATMCashAdvanceLimitExceededCount.cnt.day.past29, ATMHighRiskDebitAccumulator.acc.day.total, ATMHighRiskDebitAccumulator.acc.day.present, ATMHighRiskDebitAccumulator.acc.day.past1, ATMHighRiskDebitAccumulator.acc.day.past3, ATMHighRiskDebitAccumulator.acc.day.past10, ATMHighRiskDebitAccumulator.acc.day.past15, ATMHighRiskDebitAccumulator.acc.day.past29, OnlinePOSCount.cnt.present, OnlinePOSCount.cnt.day.present, OnlinePOSCount.cnt.day.past1, OnlinePOSCount.cnt.day.past3, OnlinePOSCount.cnt.day.past9, EMVTransactionsAcc.acc.day.total, EMVTransactionsAcc.acc.day.present, EMVTransactionsAcc.acc.day.past1, EMVTransactionsAcc.acc.day.past3, EMVTransactionsAcc.acc.day.past10, EMVTransactionsAcc.acc.day.past15, EMVTransactionsAcc.acc.day.past29, NewMerchantCountryCount.cnt.hour1, NewMerchantCountryCount.cnt.hour3, NewMerchantCountryCount.cnt.hour4, NewMerchantCountryCount.cnt.hour10, NewMerchantCountryCount.cnt.hour15, NewMerchantCountryCount.cnt.hour24, ATMDepositAccumulator.acc.day.total, ATMDepositAccumulator.acc.day.present, ATMDepositAccumulator.acc.day.past1, ATMDepositAccumulator.acc.day.past3, ATMDepositAccumulator.acc.day.past10, ATMDepositAccumulator.acc.day.past15, ATMDepositAccumulator.acc.day.past29, CustomerPresentAuthAmount.acc.day.total, CustomerPresentAuthAmount.acc.day.present, CustomerPresentAuthAmount.acc.day.past1, CustomerPresentAuthAmount.acc.day.past3, CustomerPresentAuthAmount.acc.day.past10, CustomerPresentAuthAmount.acc.day.past15, CustomerPresentAuthAmount.acc.day.past29, AlternatingCountrySwapCounter.cnt.day.total, AlternatingCountrySwapCounter.cnt.day.present, AlternatingCountrySwapCounter.cnt.day.past1, AlternatingCountrySwapCounter.cnt.day.past3, AlternatingCountrySwapCounter.cnt.day.past6, SmallOnlineAuthorizationCount.cnt.hour1, SmallOnlineAuthorizationCount.cnt.hour3, SmallOnlineAuthorizationCount.cnt.hour4, SmallOnlineAuthorizationCount.cnt.hour10, SmallOnlineAuthorizationCount.cnt.hour15, SmallOnlineAuthorizationCount.cnt.hour24, HighRiskPOSSum.acc.hour.total, HighRiskPOSSum.acc.hour.present, HighRiskPOSSum.acc.hour.past1, HighRiskPOSSum.acc.hour.past3, HighRiskPOSSum.acc.hour.past4, HighRiskPOSSum.acc.hour.past10, HighRiskPOSSum.acc.hour.past15, HighRiskPOSSum.acc.hour.past24, HighRiskPOSSum.acc.hour.past29);
	at org.apache.spark.sql.Dataset$$anonfun$resolve$1.apply(Dataset.scala:220)
	at org.apache.spark.sql.Dataset$$anonfun$resolve$1.apply(Dataset.scala:220)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.Dataset.resolve(Dataset.scala:219)
	at org.apache.spark.sql.Dataset.col(Dataset.scala:921)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at com.baesystems.ai.analytics.learning.classification.ClassificationFunction.execute(ClassificationFunction.java:81)
	at com.baesystems.ai.analytics.ModelingEngine.main(ModelingEngine.java:73)

**Comment by nikhilkalyankar** [comment]
I changed the Spark version to 2.1.0 & then to 2.2.0 and the `read` for both is error free. I believe Spark fixes this issue with `backticks` on column names. However, I had the same issue with `"/" (forward slash)`. I did the following to get this error:

```
//errorColumn is a String which I retrieved from df.columns();
Iterator<Row> itr = df.groupby(errorColumn).count().select(errorColumn).toLocalIterator();
if (itr != null)
	while (itr.hasNext())
			System.out.println(itr.next().get(0));
```

This is the error:

```
org.apache.spark.sql.AnalysisException: cannot resolve '`State-owned Bank and/or Govt. Agency as Source of Financing`' given input columns: [Other Source of Financing, Access to finance as major/severe barrier, Size, Have Checking, # Enterprises, Underserved, Have Access to Credit, Average loan duration (months), Loan size - average size per revenue, Average deposit gap per enterprise, Private Commercial Bank as Source of Financing, Total credit value gap, Owned by, Non-bank Financial Institution as Source of Financing, Country, SME?, Region, Loan rejection rate, Unserved, State-owned Bank and/or Govt. Agency as Source of Financing, Well served, Average credit value gap per enterprise, Total deposit gap, Does not need credit, Have Loan, Have Overdraft];;
'Project ['State-owned Bank and/or Govt. Agency as Source of Financing]
+- Relation[Region#12,Country#13,Size#14,Owned by#15,SME?#16,# Enterprises#17,Have Checking#18,Have Overdraft#19,Have Loan#20,Have Access to Credit#21,Access to finance as major/severe barrier#22,Does not need credit#23,Unserved#24,Underserved#25,Well served#26,Loan size - average size per revenue#27,Average loan duration (months)#28,Loan rejection rate#29,Private Commercial Bank as Source of Financing#30,State-owned Bank and/or Govt. Agency as Source of Financing#31,Non-bank Financial Institution as Source of Financing#32,Other Source of Financing#33,Average credit value gap per enterprise#34,Total credit value gap#35L,... 2 more fields] csv

	at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:88)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:85)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:288)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:268)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:268)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:279)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:289)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1$1.apply(QueryPlan.scala:293)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:293)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$6.apply(QueryPlan.scala:298)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:298)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:268)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:85)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:78)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:127)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:78)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:91)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:52)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:66)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withPlan(Dataset.scala:2872)
	at org.apache.spark.sql.Dataset.select(Dataset.scala:1153)
	at org.apache.spark.sql.Dataset.select(Dataset.scala:1171)
	at org.apache.spark.sql.Dataset.select(Dataset.scala:1171)
	at io.utilities.ColumnManager.manage(ColumnManager.java:165)
	at io.utilities.ColumnManager.read(ColumnManager.java:114)
	at io.test.Main.main(Main.java:117)
```

The only workaround, I could come up with this is renaming all the columns by eliminating special characters immediately after reading:

```
for (String column : df.columns())
        df = df.withColumnRenamed(column, column.replaceAll("[^a-zA-Z0-9]", " "));
```
