### ISSUE TITLE
java.lang.IllegalArgumentException: requirement failed: Decimal precision 35 exceeds max precision 20

### ISSUE THREAD

**Issue by crazylab** [databricks/spark-csv#371]
I have a column which basically consists of very large numbers. The schema shows the column is of DecimalType. But whenever it is encountering some numbers like
48772130600436761996023412922286
48772130600436761996023412922286
..
it is throwing an exception with the message "java.lang.IllegalArgumentException: requirement failed: Decimal precision 35 exceeds max precision 20"

Here is the StackTrace as follows:
java.lang.IllegalArgumentException: requirement failed: Decimal precision 35 exceeds max precision 20
	at scala.Predef$.require(Predef.scala:233)
	at org.apache.spark.sql.types.Decimal.set(Decimal.scala:112)
	at org.apache.spark.sql.types.Decimal$.apply(Decimal.scala:405)
	at org.apache.spark.sql.execution.datasources.csv.CSVTypeCast$.castTo(CSVInferSchema.scala:278)
	at org.apache.spark.sql.execution.datasources.csv.CSVRelation$$anonfun$csvParser$3.apply(CSVRelation.scala:115)
	at org.apache.spark.sql.execution.datasources.csv.CSVRelation$$anonfun$csvParser$3.apply(CSVRelation.scala:84)
	at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat$$anonfun$buildReader$1$$anonfun$apply$1.apply(CSVFileFormat.scala:125)
	at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat$$anonfun$buildReader$1$$anonfun$apply$1.apply(CSVFileFormat.scala:124)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:91)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithoutKey$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:79)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:47)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
16/08/05 16:37:17 WARN TaskSetManager: Lost task 0.0 in stage 3.0 (TID 4, localhost): java.lang.IllegalArgumentException: requirement failed: Decimal precision 35 exceeds max precision 20
	at scala.Predef$.require(Predef.scala:233)
	at org.apache.spark.sql.types.Decimal.set(Decimal.scala:112)
	at org.apache.spark.sql.types.Decimal$.apply(Decimal.scala:405)
	at org.apache.spark.sql.execution.datasources.csv.CSVTypeCast$.castTo(CSVInferSchema.scala:278)
	at org.apache.spark.sql.execution.datasources.csv.CSVRelation$$anonfun$csvParser$3.apply(CSVRelation.scala:115)
	at org.apache.spark.sql.execution.datasources.csv.CSVRelation$$anonfun$csvParser$3.apply(CSVRelation.scala:84)
	at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat$$anonfun$buildReader$1$$anonfun$apply$1.apply(CSVFileFormat.scala:125)
	at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat$$anonfun$buildReader$1$$anonfun$apply$1.apply(CSVFileFormat.scala:124)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:91)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithoutKey$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:79)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:47)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by falaki** [comment]
I see. We are using default Decimal construction in Spark, which sets precision to 20. Supporting this requires a patch to the data source to include an option for decimal precision. Alternatively you can manually specify the schema to be `String` for that column and then transform it with a UDF and specify a higher value for precision.

**Comment by crazylab** [comment]
@falaki thanks for writing back. Can you please specify how to apply the patch to the data source?

**Comment by falaki** [comment]
You can submit a PR that adds a new option, say `decimalPercision`.

**Comment by HyukjinKwon** [comment]
@falaki and @crazylab How about supporting flexible precision for big numbers maybe? I have done this in Spark, https://github.com/apache/spark/pull/11724. This might be helpful.

**Comment by HyukjinKwon** [comment]
Maybe, fixing this will also resolve https://github.com/databricks/spark-csv/issues/292.

**Comment by marcos-f** [comment]
What's worst is that I don't even know which field or what value is making things blow up. If it at least included the value in the exception message I would possibly have a clue about what's going on. Looking at a sea of data and not sure what's in it.

**Comment by falaki** [comment]
@marcos-f have you tried setting mode to "FAILFAST"? This will print the offending row for you as soon as it encounters it.

**Comment by tonyfraser** [comment]
Marcos can you put an example of using failfast in there?

**Comment by pramodanarase** [comment]
I am also facing similar type of issue
`java.lang.IllegalArgumentException: requirement failed: Decimal precision 39 exceeds max precision 38
	at scala.Predef$.require(Predef.scala:224) ~[scala-library-2.11.8.jar:?]
	at org.apache.spark.sql.types.Decimal.set(Decimal.scala:112) ~[spark-catalyst_2.11-2.0.2.jar:2.0.2]`

Please let me know how to debug the spark sql query and which column giving this error.
I have print the schema but i did not find any column with precision 39.

**Comment by tonyfraser** [comment]
With respect to this thread I figured out my issue. Of course it was the data. Data was following a schema 99% of the time but the other 1% was bad. I had to not infer schema and then DROPMALFORMED.

It would still be great to see an example of how to use FAILFAST.

**Comment by Gajapathy91** [comment]
I am also facing the same problem, not sure how to identify which record in my input is causing it...! `Caused by: java.lang.IllegalArgumentException: requirement failed: Decimal precision 6 exceeds max precision 3`. Could anyone please post how to use DROPMALFORMED or FAILFAST
