### ISSUE TITLE
empty/null Timestamp field

### ISSUE THREAD

**Issue by mpekalski** [databricks/spark-csv#388]
I have problem with spark 2.0.0, spark-csv 1.5.0, and scala 2.11.8.

I have a csv file that I want to convert to parquet. There is a column with timestamps and some of them are missing, those are empty strings (without quotes). I get exception thrown:
```
16/10/23 02:46:08 ERROR Utils: Aborting task
java.lang.IllegalArgumentException
	at java.sql.Date.valueOf(Date.java:143)
	at org.apache.spark.sql.catalyst.util.DateTimeUtils$.stringToTime(DateTimeUtils.scala:137)
	at org.apache.spark.sql.execution.datasources.csv.CSVTypeCast$.castTo(CSVInferSchema.scala:287)
	at org.apache.spark.sql.execution.datasources.csv.CSVRelation$$anonfun$csvParser$3.apply(CSVRelation.scala:115)
	at org.apache.spark.sql.execution.datasources.csv.CSVRelation$$anonfun$csvParser$3.apply(CSVRelation.scala:84)
...
```

The options I use when reading csv
```
"delimiter" -> ","
"header" -> "true"
"inferSchema" -> "true"
"treatEmptyValuesAsNulls" ->"true"
"nullValue"->""
```

The execution goes through **CSVINferSchema.scala** (lines 284-287) in **spark-sql_2.11-2.0.0-sources.jar**
```
      case _: TimestampType =>
        // This one will lose microseconds parts.
        // See https://issues.apache.org/jira/browse/SPARK-10681.
        DateTimeUtils.stringToTime(datum).getTime  * 1000L
```
it invokes `Date.valueOf(s)` in **DateTimeUtils.scala** **spark-catalyst_2.11-2.0.0-sources.jar** that then throws excepion in **java.sql.Date.valueOf**. 

Is that a bug, I am doing something wrong, or there is a way to pass a default value?

**Comment by falaki** [comment]
I believe Spark 2.0 will not be using spark-csv package when loading CSV data. The package was inlined in Spark. Would you please file this as a bug in Spark JIRA <https://issues.apache.org/jira/browse/spark>? Feel free to ping me as (~falaki) there.
