### ISSUE TITLE
Pyspark setting comment to null does not seem possible

### ISSUE THREAD

**Issue by GeorgeDittmar** [databricks/spark-csv#396]
This might not be a bug but more a failing to understand how to turn comments off completely in spark-csv via python calls. So far everything I have tried to get it to work has failed or returned me the error 

> Traceback (most recent call last):
  File "/home/r629922/read_csv_emr.py", line 91, in <module>
    curr_df = sqlContext.read.format('com.databricks.spark.csv').option("comment","").options(delimiter=delimiter).load(curr_tbl,schema=df_schema)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 137, in load
  File "/usr/lib/spark/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py", line 813, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 45, in deco
  File "/usr/lib/spark/python/lib/py4j-0.9-src.zip/py4j/protocol.py", line 308, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o53.load.
: java.lang.Exception: Comment marker cannot be more than one character.
> 

or some mix of that when I try to set comment to "null" or None. The data I have has keys that begin with # and we just noticed this when we suddenly had data loss of all rows starting with # so I want to turn comments off completely. Also why was # decided as to be used by default?

**Comment by falaki** [comment]
@GeorgeDittmar this is good point. Using the data source API dues not support passing `null` for an option. I also agree with you that our choice is default is not ideal, specially now that it not possible to disable in python. Have you tried this on 2.0? Do you encounter the same problem? If so, would you please also file a JIRA for spark 2.0?

**Comment by GeorgeDittmar** [comment]
I havent tried this in 2.0 since the production system I am using is running on a 1.6.1 cluster. I will test out in a 2.0 cluster to see if this is still an issue or not.
