### ISSUE TITLE
Error saving data frame as CSV

### ISSUE THREAD

**Issue by RafaelAcostaQ2** [databricks/spark-csv#406]
Hi,
I'm trying to save a df into a csv file in HDFS and it fails with the following error

------------
ERROR datasources.InsertIntoHadoopFsRelationCommand: Aborting job.
org.apache.spark.SparkException: Job aborted due to stage failure: Task 5 in stage 1.0 failed 4 times, most recent failure: Lost task 5.3 in stage 1.0 (TID 11, hadoop-6): java.io.InvalidClassException: org.apache.commons.lang3.time.FastDateFormat; local class incompatible: stream classdesc serialVersionUID = 1, local class serialVersionUID = 2
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:617)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1622)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

------------

This is my source code
test.py
--------------
from __future__ import print_function
import os
import sys
from ua_parser import user_agent_parser
from pyspark import SparkContext, SparkConf
from pyspark.sql import SQLContext, SparkSession

def parse_ua_info(raw_line):
    cols = raw_line.split('|')
    ret = user_agent_parser.Parse(cols[1])
    return (cols[0], ret.get('device').get('family'), ret.get('os').get('family'), ret.get('user_agent').get('family'))

spark = SparkSession\
    .builder\
    .appName("PythonTest")\
    .getOrCreate()

rdd_raw = spark.read.text('workspace/test.txt').rdd.map(lambda r: r[0])
df = rdd_raw.map(lambda x: parse_ua_info(x)).toDF(['emd5', 'device', 'os', 'browser']).cache()
df.write.format("com.databricks.spark.csv").save("workspace/{dest}".format(dest=sys.argv[1]))

spark.stop()
---------

I'm using python 3.5 with Spark 2.0. 
Java version installed in my cluster it's 1.7 and scala 2.11.8

Thanks in advanced

**Comment by psyshetty** [comment]
Getting this error with scala as well.

**Comment by MarsJiao** [comment]
Getting this error with scala as well. It there any ideas to solve it ?

**Comment by jb44** [comment]
+1 getting this error

**Comment by psyshetty** [comment]
We upgraded to spark 2.1 and got rid of this error.
