### ISSUE TITLE
Cannot load a pipe-delimiter CSV

### ISSUE THREAD

**Issue by JankoJerinic** [databricks/spark-csv#416]
Hi,

I'm having issues loading a quoted, pipe-delimited CSV. Using Spark 2.1.0 with Scala version 2.11.8, Java 1.8.0_121. 

I'm loading
[test.txt](https://github.com/databricks/spark-csv/files/823556/test.txt)
 via: 

```
val df = sqlContext.read.format("com.databricks.spark.csv")  
  .option("header", "false")  
  .option("inferSchema", "false")  
  .option("delimiter", '|')  
  .load("test.txt")
```

Also tried with `option("delimiter", "|")`, using explicit versions of spark-csv via --package parameter, nothing seems to help.

Exception being thrown is: 

```
java.lang.IllegalArgumentException: Delimiter cannot be more than one character: 124
  at org.apache.spark.sql.execution.datasources.csv.CSVTypeCast$.toChar(CSVInferSchema.scala:322)
  at org.apache.spark.sql.execution.datasources.csv.CSVOptions.<init>(CSVOptions.scala:71)
  at org.apache.spark.sql.execution.datasources.csv.CSVOptions.<init>(CSVOptions.scala:31)
  at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat.inferSchema(CSVFileFormat.scala:55)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$7.apply(DataSource.scala:184)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$7.apply(DataSource.scala:184)
  at scala.Option.orElse(Option.scala:289)
  at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$getOrInferFileFormatSchema(DataSource.scala:183)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:387)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:135)
  ... 48 elided
```

The test file cannot be simpler, attached.

**Comment by Landes1977** [comment]
I would also like to know how to resolve this issue.

**Comment by TDaglis** [comment]
@JankoJerinic @Landes1977 
Replace the since quotes of the delimiter with double quotes. Instead of `option("delimiter", '|')  `. it should be `option("delimiter", "|")  `.
This should fix your issues.

**Comment by thejasbabu** [comment]
Remove the extra space, the error message clearly says it supports only one character. It should be just "|" and not " | "
