### ISSUE TITLE
Spark 2 incorrectly requires positive JDBC parameter. Incorrect for MySQL JDBC driver.

### ISSUE THREAD

**Issue by leonburda** [databricks/spark-csv#437]
java.lang.IllegalArgumentException: requirement failed: Invalid value `-2147483648` for parameter `fetchsize`. The minimum value is 0. When the value is 0, the JDBC driver ignores the value and does the estimates.
        at scala.Predef$.require(Predef.scala:224)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:105)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:34)
        at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:32)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:330)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:125)
...

For MySQL have to set oprtion 'fetchsize' to Integer.MIN_VALUE which is negative value. If not set, cannot precess large JDBC tables that does not fit in memory. See for instance https://stackoverflow.com/questions/2447324/streaming-large-result-sets-with-mysql

**Comment by technology20nn** [comment]
Me too!
