### ISSUE TITLE
Unparseable number Issue while writing data to parquet file from Spark DataFrame

### ISSUE THREAD

**Issue by vivekgautam104** [databricks/spark-csv#439]
Hi,

I created a dataframe in Spark and loaded the data in the dataframe from AWS S3. When I'm writing the data to parquet from dataframe, it throws a following error:

Caused by: java.text.ParseException: Unparseable number: "$250.00-$254.99"
	at java.text.NumberFormat.parse(NumberFormat.java:385)
	at org.apache.spark.sql.execution.datasources.csv.CSVTypeCast$$anonfun$castTo$2.apply$mcF$sp(CSVInferSchema.scala:261)
	at org.apache.spark.sql.execution.datasources.csv.CSVTypeCast$$anonfun$castTo$2.apply(CSVInferSchema.scala:261)
	at org.apache.spark.sql.execution.datasources.csv.CSVTypeCast$$anonfun$castTo$2.apply(CSVInferSchema.scala:261) 

I do have column in my dataset which has the value "$250.00-$254.99" and this column is defined as StringType in my dataframe.

Any help will be appreciated.

Thanks,
Vivek

**Comment by finlay1888** [comment]
Also observing this issue, same scenario.   Column is correctly defined as "StringType":
2017-07-27 15:49:47.768  INFO 6894 --- [           main] o.apache.spark.sql.internal.SharedState  : Warehouse path is '/data/EDI/edi_parquet/NAP/'.
root
|-- TNPTLOG_TRANS_TYPE_NAP: string (nullable = true)

2017-07-27 15:50:05.581  INFO 6894 --- [ker for task 15] o.a.s.s.e.d.parquet.ParquetWriteSupport  : Initialized Parquet WriteSupport with Catalyst schema:
…
    "name" : "TNPTLOG_TRANS_REF_NAP",
    "type" : "string",
    "nullable" : true,
    "metadata" : { }
  },
and corresponding Parquet message type:
message spark_schema {
  optional binary TNPTLOG_TRANS_REF_NAP (UTF8);

Error:
java.text.ParseException: Unparseable number: "P11064441275095"
        at java.text.NumberFormat.parse(NumberFormat.java:350) ~[na:1.7.0_75]

**Comment by HyukjinKwon** [comment]
Can you guys check if the type of the column is actually numeric?

**Comment by finlay1888** [comment]
The column type is string in my case -  both in schema definition and the source data itself, as above.   Yet this error is thrown.

**Comment by HyukjinKwon** [comment]
Would.you be able to share codes, input and Spark version?
