### ISSUE TITLE
Issue with spark-csv. java.lang.NoClassDefFoundError: org/apache/commons/csv/CSVFormat

### ISSUE THREAD

**Issue by cziko** [databricks/spark-csv#58]
Hi there,

I've bumped into following issue:

1.) Submitting a job. df.save("path_to_csv", "com.databricks.spark.csv")
2.) Job executes on the cluster
3.) Only after it's about to be stored to csv I'm getting the following error:

15/05/02 18:14:44 WARN scheduler.TaskSetManager: Lost task 1.0 in stage 5.0 (TID 533, ip-10-140-173-224.ec2.internal): java.lang.NoClassDefFoundError: org/apache/commons/csv/CSVFormat
	at com.databricks.spark.csv.package$CsvSchemaRDD$$anonfun$5.apply(package.scala:97)
	at com.databricks.spark.csv.package$CsvSchemaRDD$$anonfun$5.apply(package.scala:96)
	at org.apache.spark.rdd.RDD$$anonfun$14.apply(RDD.scala:634)
	at org.apache.spark.rdd.RDD$$anonfun$14.apply(RDD.scala:634)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.csv.CSVFormat
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 16 more

15/05/02 18:14:44 INFO scheduler.TaskSetManager: Starting task 1.1 in stage 5.0 (TID 550, ip-10-146-166-229.ec2.internal, PROCESS_LOCAL, 1345 bytes)
15/05/02 18:14:44 INFO scheduler.TaskSetManager: Lost task 6.0 in stage 5.0 (TID 538) on executor ip-10-146-166-229.ec2.internal: java.lang.NoClassDefFoundError (org/apache/commons/csv/CSVFormat) [duplicate 1]

Any thoughts are more than welcome.

**Comment by falaki** [comment]
How do you include the spark-csv Jar file? Are you doing this?
```
bin/spark-shell --packages com.databricks:spark-csv_2.10:1.0.3
```

**Comment by cziko** [comment]
Yeah,

Thanks. I had issue in my configuration file.

**Comment by nevi-me** [comment]
I've also come across the issue, I've included the .jar file in my spark-defaults.conf. I can see it in my classpaths, but I get the above error. @cziko how did you resolve it?

**Comment by kevinskii** [comment]
It seems that the org/apache/commons/csv/CSVFormat dependency isn't being packaged in the spark-csv jar file. Downloading the binary from (https://commons.apache.org/proper/commons-csv/download_csv.cgi), extracting the .jar from it and setting the permissions, and finally including it in the list of comma-separated JAR files following the "--jar" option when running the Spark shell solved it for me.

Example:
bin/pyspark --jars /path/to/spark-csv.jar,/path/to/commons-csv.jar

**Comment by anabranch** [comment]
@kevinskii fixed my issue.

**Comment by PamLev** [comment]
Hi Kevinskii, 

I have the same problem but I'm new to Linux so I'm not sure what do you mean by "extracting the .jar from download_csv.cgi". Can you tell me how to do it? Really appreciate your help.
_Pam

**Comment by pawanparimi** [comment]
Hi, 
I am facing the same  <Caused by: java.lang.ClassNotFoundException: org.apache.commons.csv.CSVFormat>.

I am using the Spark SQL thrift server, query fails with the above exception on any table (only with csv data). I am supplying both the jars 1) commons-csv-1.2.jar and 2) spark-csv_2.10-1.3.0.jar from spark-env.sh SPARK_CLASSPATH variable.

I have observer this behavior only when i run this spark thrift server on spark standalone and yarn-client mode. but everything works fine on local mode.

please help me.

**Comment by kevinskii** [comment]
@PamLev: Sorry for the late reply. In case this issue is still affecting you or anyone else, by "extracting the .jar" I mean go to the Apache commons-csv download page at my link above, and download the one of the binaries. At the time of this writing it can be either "commons-csv-1.2-bin.zip" or "commons-csv-1.2.bin.tar.gz". When you uncompress the binary you'll see a single commons-csv-1.2.jar file in it. Copy this .jar over to the Linux machine that you're running Spark on and follow the rest of my original comment above.

**Comment by ksxh** [comment]
@kevinskii I followed your instructions, I can load csv using spark-csv, for example
`df = sqlContext.load(source="com.databricks.spark.csv", path = "file:/home/hello/pa_type_sg.txt")`

But I can't write to csv, for example, 
`df.write.format('com.databricks.spark.csv').save('file:/home/hello/newcars.csv')`

with error message

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hello/spark/spark-1.6.0-bin-hadoop2.6/python/pyspark/sql/readwriter.py", line 387, in save
    self._jwrite.save(path)
  File "/home/hello/spark/spark-1.6.0-bin-hadoop2.6/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py", line 813, in __call__
  File "/home/hello/spark/spark-1.6.0-bin-hadoop2.6/python/pyspark/sql/utils.py", line 45, in deco
    return f(*a, **kw)
  File "/home/hello/spark/spark-1.6.0-bin-hadoop2.6/python/lib/py4j-0.9-src.zip/py4j/protocol.py", line 308, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o28.save.
: java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
	at com.databricks.spark.csv.util.CompressionCodecs$.<init>(CompressionCodecs.scala:29)
	at com.databricks.spark.csv.util.CompressionCodecs$.<clinit>(CompressionCodecs.scala)
	at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:189)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:745)
`

Do you have any suggestion? Thanks for your help!

**Comment by kevinskii** [comment]
@ksxh: You meay want to try using "file://" instead of "file:" in your save method, i.e.:

df.write.format('com.databricks.spark.csv').save('**file://**/home/hello/newcars.csv')

It's possible that the read() is able to handle the malformed protocol, but the write() in the csv package cannot.

**Comment by Naresh523** [comment]
@cziko  
I'm facing similar issue, can you please elaborate what was the issue with the configuration file?

**Comment by gilv** [comment]
I have stand alone Spark cluster, 3 workers 1 master.
I am using ./bin/spark-submit --packages com.databricks:spark-csv_2.10:1.4.0 --master ... --deploy-mode cluster my.jar.
However it fails on the worker nodes with exception

xception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.worker.DriverWrapper$.main(DriverWrapper.scala:58)
	at org.apache.spark.deploy.worker.DriverWrapper.main(DriverWrapper.scala)
Caused by: java.lang.ClassNotFoundException: Failed to find data source: com.databricks.spark.csv. Please find packages at http://spark-packages.org
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.lookupDataSource(ResolvedDataSource.scala:77)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:219)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:139)
	at com.ibm.spark.test.swift.Runner.main(Runner.java:113)
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.databricks.spark.csv.DefaultSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4$$anonfun$apply$1.apply(ResolvedDataSource.scala:62)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4$$anonfun$apply$1.apply(ResolvedDataSource.scala:62)
	at scala.util.Try$.apply(Try.scala:161)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4.apply(ResolvedDataSource.scala:62)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4.apply(ResolvedDataSource.scala:62)
	at scala.util.Try.orElse(Try.scala:82)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.lookupDataSource(ResolvedDataSource.scala:62)
	... 10 more

I have to add that it perfectly works when i write --master local[4]
