### ISSUE TITLE
Add simple install instructions details

### ISSUE THREAD

**Issue by lebigot** [databricks/spark-csv#59]
I wanted to use spark-csv, but the installation instructions refer to frameworks that I don't know.

It would be most useful if you could add detailed installation instructions. For instance for someone who is only familiar with Python and has only downloaded (and successfully used) the pre-compiled version of Spark. :)

**Comment by falaki** [comment]
Doesn't following command work for you (with your pre-compiled version of Spark)?
```sh
$ bin/spark-shell --packages com.databricks:spark-csv_2.10:1.0.3
```

**Comment by lebigot** [comment]
Thanks, this was very helpful: this was close enough to the answer to my need. :) I wanted to use spark-csv

I would strongly suggest that you update the installation documentation, for example in the following places:

1) Starting with the Linking section, that mentions "coordinates", is completely confusing for someone like me who knows Python and PySpark, but not much about Java and Scala. Introducing this section with some context (like "If you are using …") would help a lot: instead of being lost when I read it (how do I do that? do I need to do that in my case?), I would understand what the purpose of this Linking section is, and skip it.

2) The section "Using with Apache Spark" mentions using the "`--jars`" command line option, but the example uses `--packages` instead. This is confusing as well, and I wondered if I should use `--jars` somewhere. I guess `--packages` was meant instead??

3) In the same section, I saw `spark-shell`, so I thought that the example was not for me: I need to use the Python equivalent (`pyspark`). So, I strongly suggest to mention this usage too (I tried the same `--packages` with `pyspark` and it worked).

4) This still does not describe what to do when running non-interactively. I discovered that `spark-submit` actually accepts the same `--packages` option. Stating this explicitly would help a lot.

Points 2–4 could be simply summarized by saying that you simply pass `--packages` to a Spark shell (Scala or Python) or to `spark-submit`.

5) For people not familiar with how handling such packages works, it is worth mentioning what the `--packages` option does. In particular, I had to check that it installed the package for good (instead of, for some reason, downloaded it each time). So, adding that `--packages` does just this would let users who are not familiar at all with packages know that they are covered (even if they are on the road with no connection).

These remarks are longer than the final documentation text, but I prefer to not write a documentation patch: it is better if experts write it. :)

**Comment by falaki** [comment]
Thanks for your suggestions. Will include them.

**Comment by karenyyng** [comment]
Some follow up questions:
1. Do we have to add the compiled jar, .e.g `$<PATH_TO>/spark-csv/target/scala-2.10/spark-csv_2.1X-1.2.0.jar` to the `CLASSPATH` variable of Spark?

2. When I try to run the following: 
```Python
>>> df = sqlContext.load(source="com.databricks.spark.csv", header="true", path = "cars.csv")
```
I get an error
```
java.lang.NoClassDefFoundError: org/apache/commons/csv/CSVFormat
```
Does this package require the installation of [Common CSV](http://commons.apache.org/proper/commons-csv/index.html) as a dependency?

**Comment by falaki** [comment]
Yes, you need to include dependancies for spark-csv as well. A I suggested before, the recommended approach is using ```--packages``` flag with Spark.

**Comment by jougNY** [comment]
I'm in a company environment and when I try to execute without success.
bin\spark-shell --packages com.databricks:spark-csv_2.11:1.2.0

I thin I have to specify somewhere the proxy but I have not idea where.

Any idea?


I got these errors:
Ivy Default Cache set to: C:\Users\jcoppey\.ivy2\cache
The jars for the packages stored in: C:\Users\jcoppey\.ivy2\jars
:: loading settings :: url = jar:file:/C:/Spark/lib/spark-assembly-1.5.1-hadoop2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.databricks#spark-csv_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
        confs: [default]
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.
:: resolution report :: resolve 4796ms :: artifacts dl 0ms
        :: modules in use:
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
        ---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
        Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/com/databricks/spark-csv_2.11/1.2.0/spark-csv_2.11-1.2.0.pom

        Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/com/databricks/spark-csv_2.11/1.2.0/spark-csv_2.11-1.2.0.jar

        Host dl.bintray.com not found. url=http://dl.bintray.com/spark-packages/maven/com/databricks/spark-csv_2.11/1.2.0/spark-csv_2.11-1.2.0.pom

        Host dl.bintray.com not found. url=http://dl.bintray.com/spark-packages/maven/com/databricks/spark-csv_2.11/1.2.0/spark-csv_2.11-1.2.0.jar

                module not found: com.databricks#spark-csv_2.11;1.2.0

        ==== local-m2-cache: tried

          file:/C:/Users/jcoppey/.m2/repository/com/databricks/spark-csv_2.11/1.2.0/spark-csv_2.11-1.2.0.pom

          -- artifact com.databricks#spark-csv_2.11;1.2.0!spark-csv_2.11.jar:

          file:/C:/Users/jcoppey/.m2/repository/com/databricks/spark-csv_2.11/1.2.0/spark-csv_2.11-1.2.0.jar

        ==== local-ivy-cache: tried

          C:\Users\jcoppey\.ivy2\local\com.databricks\spark-csv_2.11\1.2.0\ivys\ivy.xml

        ==== central: tried

          https://repo1.maven.org/maven2/com/databricks/spark-csv_2.11/1.2.0/spark-csv_2.11-1.2.0.pom

          -- artifact com.databricks#spark-csv_2.11;1.2.0!spark-csv_2.11.jar:

          https://repo1.maven.org/maven2/com/databricks/spark-csv_2.11/1.2.0/spark-csv_2.11-1.2.0.jar

        ==== spark-packages: tried

          http://dl.bintray.com/spark-packages/maven/com/databricks/spark-csv_2.11/1.2.0/spark-csv_2.11-1.2.0.pom

          -- artifact com.databricks#spark-csv_2.11;1.2.0!spark-csv_2.11.jar:

          http://dl.bintray.com/spark-packages/maven/com/databricks/spark-csv_2.11/1.2.0/spark-csv_2.11-1.2.0.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: com.databricks#spark-csv_2.11;1.2.0: not found

                ::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: com.databricks#spark-csv_2.11;1.2.0: not found]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1009)
        at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:286)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:153)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by jaxxie** [comment]
@jougNY This error message is likely that your company environment does not have internet connection or the proxy is blocking maven.org. In this case, you can download the 2 jar files first 
1. http://mvnrepository.com/artifact/com.databricks/spark-csv_2.10   -  The spark csv jar
2. http://mvnrepository.com/artifact/org.apache.commons/commons-csv/1.2   -  The common csv jar dependecy

Save the 2 jar file to somewhere. For me I have it saved under $SPARK_HOME/lib. 
There after to run spark shell with this
``` ./bin/spark-shell --jars lib/spark-csv_2.10-1.2.0.jar,lib/commons-csv-1.2.jar ```

It should work.

**Comment by FRosner** [comment]
I have the same proxy error. The proxy is configured and wget works fine on the URL (so it is not blocked). The documentation of spark-packages should contain a way to tell it the proxy. Any ideas?

**Comment by chrislaing** [comment]
I also have the same issue with a proxy (which is otherwise correctly configured). As @FRosner says, there must be a way to make spark-packages aware of the proxy. It would be great if we could get some documentation of this soon.

**Comment by amitmohanty** [comment]
@falaki Based on your instruction, I tried to do this: 

`/user/god/spark-1.6.0-bin-hadoop2.6/bin/spark-shell --jars /user/god/spark-1.6.0-bin-hadoop2.6/lib/spark-csv_2.10-1.3.0.jar, /user/god/spark-1.6.0-bin-hadoop2.6/lib/commons-csv-1.2.jar --master yarn-client --num-executors 20 --executor-cores 8 --executor-memory 24g --driver-memory 8g
`

then 

`scala> val df = sqlContext.read.format("com.databricks.spark.csv").load("airlinesmall.csv")
`

But I am getting the errors below. Do I need to do some imports before executing the above? 

__PS__: I downloaded the jar files from links provided by @jaxxie . 

## Error Msg
`java.lang.NoClassDefFoundError: org/apache/commons/csv/CSVFormat
        at com.databricks.spark.csv.package$.<init>(package.scala:27)
        at com.databricks.spark.csv.package$.<clinit>(package.scala)
        at com.databricks.spark.csv.CsvRelation.inferSchema(CsvRelation.scala:218)
        at com.databricks.spark.csv.CsvRelation.<init>(CsvRelation.scala:72)
        at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:157)
        at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:44)
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:158)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:109)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:25)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:30)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:32)
        at $iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:34)
        at $iwC$$iwC$$iwC$$iwC.<init>(<console>:36)
        at $iwC$$iwC$$iwC.<init>(<console>:38)
        at $iwC$$iwC.<init>(<console>:40)
        at $iwC.<init>(<console>:42)
        at <init>(<console>:44)
        at .<init>(<console>:48)
        at .<clinit>(<console>)
        at .<init>(<console>:7)
        at .<clinit>(<console>)
        at $print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1065)
        at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1346)
        at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:840)
        at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:871)
        at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:819)
        at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:857)
        at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:902)
        at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:814)
        at org.apache.spark.repl.SparkILoop.processLine$1(SparkILoop.scala:657)
        at org.apache.spark.repl.SparkILoop.innerLoop$1(SparkILoop.scala:665)
        at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$loop(SparkILoop.scala:670)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply$mcZ$sp(SparkILoop.scala:997)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
        at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
        at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$process(SparkILoop.scala:945)
        at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1059)
        at org.apache.spark.repl.Main$.main(Main.scala:31)
        at org.apache.spark.repl.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.csv.CSVFormat
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 55 more
`

**Comment by FRosner** [comment]
@amitmohanty try removing the space between your two --jars.

**Comment by darrenfu** [comment]
That works for me.

**Comment by maxmed** [comment]
with pyspark you can also try

bin/pyspark  --jars <lib>.jar --py-files <lib>.jar

**Comment by Nomii5007** [comment]
@falaki hello sir. I want to ask how can i load spark-csv in jupyter notebook? I managed to to load this in python standalone mode `$ bin/pyspark --packages com.databricks:spark-csv_2.10:1.0.3` but could find a way to load in jupyter notebook in windows. plz help.

**Comment by falaki** [comment]
Unfortunately, I am not familiar with the procedure for loading third party libraries in iPython notebooks.

**Comment by JamesHealey94** [comment]
@Nomii5007 Does this help?
```
%%configure -f
{ "packages":["com.databricks:spark-csv_2.10:1.0.3"] }
```

**Comment by Nomii5007** [comment]
@JamesHealey94 I have installed anaconda 2.7 and spark 1.6.1 
I managed to start jupyter notebook with loaded spark-csv by setting this `PYSPARK_DRIVER_PYTHON=ipython`  and this 
`PYSPARK_DRIVER_PYTHON_OPTS=notebook`  as environment variables and then running 
This command `spark-1.6.1-bin-hadoop2.6\bin\pyspark --packages com.databricks:spark-csv_2.11:1.4.0 --master local[*]` it would start my jupyter notebook but when I type `sc` in cell I get this `‘ ’. `

and when I start my jupyter notebook using this command `ipython notebook --profile=pyspark`  or this  `spark-1.6.1-bin-hadoop2.6\bin\pyspark` and writes `sc` it works perfectly and gives main this `<pyspark.context.SparkContext at 0x584a490>` whats the problem?
I want to load spark-csv package into jupyter notebook without getting sqlcontext not defined error.

**Comment by sidhusmart** [comment]
Hi guys,

Not sure if anyone actually posted the solution to the proxy issue but here's what worked for me:

./sparkR --master yarn --deploy-mode client **--conf "spark.driver.extraJavaOptions=-Dhttp.proxyHost=192.168.18.21 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=192.168.18.21 -Dhttps.proxyPort=8080"** --packages com.databricks:spark-csv_2.10:1.3.0

I had to make use of the spark-csv package, the URL was not accessible directly. Got the maven repositoy URL enabled on our corporate proxy and then added the above configuration options to get it to work.

**Comment by BhushanGarware** [comment]
I download the JARs separately and executed following. I worked for me.     
```
set PYSPARK_DRIVER_PYTHON=ipython'
set PYSPARK_DRIVER_PYTHON_OPTS=notebook
pysaprk --jars spark-csv_2.11-1.5.0.jar,commons-csv-1.1.jar
```
Only care you need to take is to copy these JARs in all the directories from where you are running the notebooks.

**Comment by paulalwin91** [comment]
How can I install databricks csv for pyspark on ubuntu?

It'll be great if someone can help out! 

I used the first command given by using pyspark instead of spark-shell but seems not to work.

IS there any documentation with step by step process?

**Comment by falaki** [comment]
@paulalwin91 this feature has been inlined in Spark since 2.x. You do not need to install anything but Apache Spark.
