### ISSUE TITLE
loading csv with missing column names

### ISSUE THREAD

**Issue by djm1329** [databricks/spark-csv#61]
I think this may be a duplicate issue. Missing column names in the header are not supported. 

java.lang.IllegalArgumentException: The header contains a duplicate entry: '' in [#"Accessibility", NE_VERSION, NE_ID, NE_NAME, EVENT_TIME, cNum, mcID, , , , , ErabAccessibilityInit(%), SumRrcConnEstabSucc(count), SumRrcConnEstabAtt(count), SumS1sigS1ConnEstabSucc(count), SumS1sigS1ConnEstabAtt(count), SumErabEstabInitSuccNbr(count), SumErabEstabInitAttNbr(count), ErabAccessibilityAdd(%), SumErabEstabAddSuccNbr(count), SumErabEstabAddAttNbr(count), ErabConnectionFailureRate(%)]
	at org.apache.commons.csv.CSVFormat.validate(CSVFormat.java:770)

**Comment by falaki** [comment]
Thanks for reporting. Would you please also include how you are calling spark-csv? Specifically what options are you passing?

**Comment by djm1329** [comment]
Sorry, I should have included initially. I tried this:

      val sqlContext = new SQLContext(sc)
      val df = sqlContext.load("com.databricks.spark.csv", Map("path" -> "SSM01-15MIN-20150502-1000/", "header" -> "true"))

Thanks for looking at this.

**Comment by falaki** [comment]
While we work on the issue you can work around it by specifying your schema manually. You can still keep header = true, to get rid of the first line in your file.

**Comment by djm1329** [comment]
Sure. Thanks again.

**Comment by randerzander** [comment]
This seems to expose an issue with dataframes themselves: https://issues.apache.org/jira/browse/SPARK-10357

My data looks like:
MI_PRINX,offense_id,rpt_date,occur_date,occur_time,poss_date,poss_time,beat,apt_office_prefix,apt_office_num,location,MinOfucr,MinOfibr_code,dispo_code,MaxOfnum_victims,Shift,Avg Day,loc_type,UC2 Literal,neighborhood,npu,x,y,,,
934782,90360664,2/5/2009,2/3/2009,13:50:00,2/3/2009,15:00:00,305,NULL,NULL,55 MCDONOUGH BLVD SW,670,2308,NULL,1,Day,Tue,35,LARCENY-NON VEHICLE,South Atlanta,Y,-84.38654,33.72024,,,
934783,90370891,2/6/2009,2/6/2009,8:50:00,2/6/2009,10:45:00,502,NULL,NULL,464 ANSLEY WALK TER NW,640,2305,NULL,1,Day,Fri,18,LARCENY-FROM VEHICLE,Ansley Park,E,-84.37276,33.79685,,,

Despite using sqlContext (also tried with the programmatic raw.select, same result) to remove columns from the dataframe, attempts to operate on it cause failures.

Snippet:
    // Read CSV file, clean field  names
    val raw = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("DROPMALFORMED", "true").load(input)
    val columns = raw.columns.map(x => x.replaceAll(" ", "_"))
    raw.toDF(columns:_*).registerTempTable(table)
    val clean = sqlContext.sql("select " + columns.filter(x => x.length() > 0 && x != " ").mkString(", ") + " from " + table)

    System.err.println(clean.schema)
    System.err.println(clean.columns.mkString(","))
    System.err.println(clean.take(1).mkString("|"))

StackTrace:
15/08/30 18:23:13 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, docker.dev, NODE_LOCAL, 1482 bytes)
15/08/30 18:23:14 INFO storage.BlockManagerInfo: Added broadcast_1_piece0 in memory on docker.dev:58272 (size: 1811.0 B, free: 530.0 MB)
15/08/30 18:23:14 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on docker.dev:58272 (size: 21.9 KB, free: 530.0 MB)
15/08/30 18:23:15 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 1350 ms on docker.dev (1/1)
15/08/30 18:23:15 INFO scheduler.DAGScheduler: ResultStage 0 (take at CsvRelation.scala:174) finished in 1.354 s
15/08/30 18:23:15 INFO cluster.YarnScheduler: Removed TaskSet 0.0, whose tasks have all completed, from pool 
15/08/30 18:23:15 INFO scheduler.DAGScheduler: Job 0 finished: take at CsvRelation.scala:174, took 1.413674 s
StructType(StructField(MI_PRINX,StringType,true), StructField(offense_id,StringType,true), StructField(rpt_date,StringType,true), StructField(occur_date,StringType,true), StructField(occur_time,StringType,true), StructField(poss_date,StringType,true), StructField(poss_time,StringType,true), StructField(beat,StringType,true), StructField(apt_office_prefix,StringType,true), StructField(apt_office_num,StringType,true), StructField(location,StringType,true), StructField(MinOfucr,StringType,true), StructField(MinOfibr_code,StringType,true), StructField(dispo_code,StringType,true), StructField(MaxOfnum_victims,StringType,true), StructField(Shift,StringType,true), StructField(Avg_Day,StringType,true), StructField(loc_type,StringType,true), StructField(UC2_Literal,StringType,true), StructField(neighborhood,StringType,true), StructField(npu,StringType,true), StructField(x,StringType,true), StructField(y,StringType,true))
MI_PRINX,offense_id,rpt_date,occur_date,occur_time,poss_date,poss_time,beat,apt_office_prefix,apt_office_num,location,MinOfucr,MinOfibr_code,dispo_code,MaxOfnum_victims,Shift,Avg_Day,loc_type,UC2_Literal,neighborhood,npu,x,y
15/08/30 18:23:16 INFO storage.MemoryStore: ensureFreeSpace(232400) called with curMem=259660, maxMem=278019440
15/08/30 18:23:16 INFO storage.MemoryStore: Block broadcast_2 stored as values in memory (estimated size 227.0 KB, free 264.7 MB)
15/08/30 18:23:16 INFO storage.MemoryStore: ensureFreeSpace(22377) called with curMem=492060, maxMem=278019440
15/08/30 18:23:16 INFO storage.MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 21.9 KB, free 264.6 MB)
15/08/30 18:23:16 INFO storage.BlockManagerInfo: Added broadcast_2_piece0 in memory on 172.17.0.19:41088 (size: 21.9 KB, free: 265.1 MB)
15/08/30 18:23:16 INFO spark.SparkContext: Created broadcast 2 from textFile at TextFile.scala:30
Exception in thread "main" java.lang.IllegalArgumentException: The header contains a duplicate entry: '' in [MI_PRINX, offense_id, rpt_date, occur_date, occur_time, poss_date, poss_time, beat, apt_office_prefix, apt_office_num, location, MinOfucr, MinOfibr_code, dispo_code, MaxOfnum_victims, Shift, Avg Day, loc_type, UC2 Literal, neighborhood, npu, x, y, , , ]
	at org.apache.commons.csv.CSVFormat.validate(CSVFormat.java:770)
	at org.apache.commons.csv.CSVFormat.<init>(CSVFormat.java:364)
	at org.apache.commons.csv.CSVFormat.withHeader(CSVFormat.java:882)
	at com.databricks.spark.csv.CsvRelation.tokenRdd(CsvRelation.scala:84)
	at com.databricks.spark.csv.CsvRelation.buildScan(CsvRelation.scala:105)
	at org.apache.spark.sql.sources.DataSourceStrategy$.apply(DataSourceStrategy.scala:101)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:59)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.planLater(QueryPlanner.scala:54)
	at org.apache.spark.sql.execution.SparkStrategies$BasicOperators$.apply(SparkStrategies.scala:300)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:59)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.planLater(QueryPlanner.scala:54)
	at org.apache.spark.sql.execution.SparkStrategies$BasicOperators$.apply(SparkStrategies.scala:314)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:59)
	at org.apache.spark.sql.SQLContext$QueryExecution.sparkPlan$lzycompute(SQLContext.scala:943)
	at org.apache.spark.sql.SQLContext$QueryExecution.sparkPlan(SQLContext.scala:941)
	at org.apache.spark.sql.SQLContext$QueryExecution.executedPlan$lzycompute(SQLContext.scala:947)
	at org.apache.spark.sql.SQLContext$QueryExecution.executedPlan(SQLContext.scala:947)
	at org.apache.spark.sql.DataFrame.collect(DataFrame.scala:1269)
	at org.apache.spark.sql.DataFrame.head(DataFrame.scala:1203)
	at org.apache.spark.sql.DataFrame.take(DataFrame.scala:1262)
	at com.github.randerzander.CSVLoad$.main(CSVLoad.scala:29)
	at com.github.randerzander.CSVLoad.main(CSVLoad.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:665)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:170)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:193)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:112)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by islammohamed** [comment]
any updated about this issue, is the fix expected in the next release?

**Comment by falaki** [comment]
Which issue are you referring to?

**Comment by islammohamed** [comment]
the same issue referred here in the same thread
java.lang.IllegalArgumentException: The header contains a duplicate entry

**Comment by neetika-Sri** [comment]
Facing the same errors . Any update ?

**Comment by alonsoir** [comment]
same here, i am using defaults when loading the csv file:

 sqlContext.read
      .format("com.databricks.spark.csv")
      .option("header", haveSchema) // "false"
      .option("delimiter", separator)   // ";"
      .schema(customSchema) 
      .load(pathCSV)

I am creating the customSchema object following this strategy:

mra_schema_parquet=PATH/TO/CUSTOM_SCHEMA.json


`    logger.info("ATTENTION! aplying mra_schema_parquet  " + mra_schema_parquet )

      val path: Path = new Path(mra_schema_parquet)
      val fileSystem = path.getFileSystem(sc.hadoopConfiguration)

      val inputStream: FSDataInputStream = fileSystem.open(path)

      val schema_json = Stream.cons(inputStream.readLine(), Stream.continually( inputStream.readLine))

/*
inspecting schema_json:

{"type" : "struct","fields" : [ {"name" : "codigo","type" : "string","nullable" : true}, {"name":"otro", "type":"string", "nullable":true}, {"name":"vacio", "type":"string", "nullable":true},{"name":"final","type":"string","nullable":true} ]}
*/

      val mySchemaStructType :DataType = DataType.fromJson(schema_json.head)

/*
After this line, mySchemaStructType have four StructFields objects inside it, the same than appears at schema_json
*/

      val myStructType = new StructType()
      myStructType.add("mySchemaStructType",mySchemaStructType)`

/*

After this line, myStructType have zero StructFields! here must be the bug, myStructType should have the four StructFields that represents the loaded schema json

*/
     myDF = loadCSV(sqlContext, path_input_csv,separator,myStructType,header)
     
     inputStream.close()

//Then, i want to create the parquet file from the DataFrame previously loaded, but an exception happens:

`df.write
      .format("com.databricks.spark.csv")
      .option("header", header)
      .option("delimiter",delimiter)
      .option("nullValue","")
      .option("treatEmptyValuesAsNulls","true")
      .mode(saveMode)
      .parquet(pathParquet)`

The exception:

`Caused by: parquet.schema.InvalidSchemaException: Cannot write a schema with an empty group: message root {
}

	at parquet.schema.TypeUtil$1.visit(TypeUtil.java:27)
	at parquet.schema.TypeUtil$1.visit(TypeUtil.java:37)
	at parquet.schema.MessageType.accept(MessageType.java:58)
	at parquet.schema.TypeUtil.checkValidWriteSchema(TypeUtil.java:23)
	at parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:209)
	at parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:311)
	at parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:282)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetOutputWriter.<init>(ParquetRelation.scala:94)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation$$anon$3.newInstance(ParquetRelation.scala:272)
	at org.apache.spark.sql.execution.datasources.DefaultWriterContainer.writeRows(WriterContainer.scala:233)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1$$anonfun$apply$mcV$sp$3.apply(InsertIntoHadoopFsRelation.scala:150)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1$$anonfun$apply$mcV$sp$3.apply(InsertIntoHadoopFsRelation.scala:150)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)`

This is how it looks my pom.xml

`
 <spark.version>1.5.0-cdh5.5.2</spark.version>
 <commons.version>0.1.0</commons.version>
 <databricks.version>1.4.0</databricks.version>

 <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.10</artifactId>
            <version>${spark.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.databricks</groupId>
            <artifactId>spark-csv_2.10</artifactId>
            <version>${databricks.version}</version>
        </dependency>
        <dependency>
            <groupId>com.keedio.mra</groupId>
            <artifactId>mra-commons</artifactId>
            <version>${commons.version}</version>
        </dependency>
        
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
    </dependencies>
`

Can anybody help me?
