### ISSUE TITLE
save csv with python throwing Py4JJavaError

### ISSUE THREAD

**Issue by abhishek-ch** [databricks/spark-csv#77]
I am using pre-built Spark Hadoop version 1.3+ (spark-1.3.1-bin-hadoop2.4).
Launching the Pyspark shell using the command -
```
./bin/pyspark --packages com.databricks:spark-csv_2.11:1.1.0
```

Following is the commandline details while launching-

```
 ./bin/pyspark --packages com.databricks:spark-csv_2.11:1.1.0
Python 2.7.8 |Anaconda 2.1.0 (x86_64)| (default, Aug 21 2014, 15:21:46) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
Ivy Default Cache set to: /Users/abhishekchoudhary/.ivy2/cache
The jars for the packages stored in: /Users/abhishekchoudhary/.ivy2/jars
:: loading settings :: url = jar:file:/Users/abhishekchoudhary/bigdata/cdh5.2.0/spark-1.3.1/lib/spark-assembly-1.3.1-hadoop2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.databricks#spark-csv_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
	confs: [default]
	found com.databricks#spark-csv_2.11;1.1.0 in central
	found org.apache.commons#commons-csv;1.1 in list
	found com.univocity#univocity-parsers;1.5.1 in list
:: resolution report :: resolve 259ms :: artifacts dl 6ms
	:: modules in use:
	com.databricks#spark-csv_2.11;1.1.0 from central in [default]
	com.univocity#univocity-parsers;1.5.1 from list in [default]
	org.apache.commons#commons-csv;1.1 from list in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent
	confs: [default]
	0 artifacts copied, 3 already retrieved (0kB/9ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/abhishekchoudhary/bigdata/cdh5.2.0/spark-1.3.1/lib/spark-assembly-1.3.1-hadoop2.4.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/abhishekchoudhary/bigdata/cdh5.2.0/spark-1.3.1/lib/spark-examples-1.3.1-hadoop2.4.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
15/06/10 19:20:47 INFO spark.SparkContext: Running Spark version 1.3.1
15/06/10 19:20:47 INFO spark.SparkContext: Spark configuration:
spark.app.name=PySparkShell
spark.driver.extraClassPath=/Users/abhishekchoudhary/anaconda/anaconda/lib/python2.7/site-packages/graphlab/graphlab-create-spark-integration.jar:/Users/abhishekchoudhary/bigdata/cdh5.2.0/hbase/lib/hbase-server-0.98.6-cdh5.2.0.jar:/Users/abhishekchoudhary/bigdata/cdh5.2.0/hbase/lib/hbase-protocol-0.98.6-cdh5.2.0.jar:/Users/abhishekchoudhary/bigdata/cdh5.2.0/hbase/lib/hbase-hadoop2-compat-0.98.6-cdh5.2.0.jar:/Users/abhishekchoudhary/bigdata/cdh5.2.0/hbase/lib/hbase-client-0.98.6-cdh5.2.0.jar:/Users/abhishekchoudhary/bigdata/cdh5.2.0/hbase/lib/hbase-common-0.98.6-cdh5.2.0.jar:/Users/abhishekchoudhary/bigdata/cdh5.2.0/hbase/lib/htrace-core-2.04.jar:/Users/abhishekchoudhary/bigdata/cdh5.2.0/spark-1.3.1/lib/spark-examples-1.3.1-hadoop2.4.0.jar:/Users/abhishekchoudhary/bigdata/cdh5.2.0/spark-1.3.1/lib/spark-assembly-1.3.1-hadoop2.4.0.jar:/Users/abhishekchoudhary/bigdata/cdh5.2.0/hbase/lib/guava-12.0.1.jar:/Users/abhishekchoudhary/bigdata/cdh5.2.0/spark-1.3.1/sqlite-jdbc-3.8.10.1.jar
spark.driver.memory=2g
spark.eventLog.dir=file:///Users/abhishekchoudhary/bigdata/ops/spark
spark.eventLog.enabled=true
spark.files=file:/Users/abhishekchoudhary/.ivy2/jars/spark-csv_2.11.jar,file:/Users/abhishekchoudhary/.ivy2/jars/commons-csv.jar,file:/Users/abhishekchoudhary/.ivy2/jars/univocity-parsers.jar
spark.fs.history.logDirectory=file:///Users/abhishekchoudhary/bigdata/ops/spark
spark.history.retainedApplications=200
spark.jars=file:/Users/abhishekchoudhary/.ivy2/jars/spark-csv_2.11.jar,file:/Users/abhishekchoudhary/.ivy2/jars/commons-csv.jar,file:/Users/abhishekchoudhary/.ivy2/jars/univocity-parsers.jar
spark.logConf=true
spark.master=local[*]
spark.rdd.compress=True
spark.serializer=org.apache.spark.serializer.KryoSerializer
spark.serializer.objectStreamReset=100
spark.submit.pyFiles=/Users/abhishekchoudhary/.ivy2/jars/spark-csv_2.11.jar,/Users/abhishekchoudhary/.ivy2/jars/commons-csv.jar,/Users/abhishekchoudhary/.ivy2/jars/univocity-parsers.jar
15/06/10 19:20:47 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/06/10 19:20:47 INFO spark.SecurityManager: Changing view acls to: abhishekchoudhary
15/06/10 19:20:47 INFO spark.SecurityManager: Changing modify acls to: abhishekchoudhary
15/06/10 19:20:47 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(abhishekchoudhary); users with modify permissions: Set(abhishekchoudhary)
15/06/10 19:20:48 INFO slf4j.Slf4jLogger: Slf4jLogger started
15/06/10 19:20:48 INFO Remoting: Starting remoting
15/06/10 19:20:48 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriver@192.168.0.11:49472]
15/06/10 19:20:48 INFO util.Utils: Successfully started service 'sparkDriver' on port 49472.
15/06/10 19:20:48 INFO spark.SparkEnv: Registering MapOutputTracker
15/06/10 19:20:48 INFO spark.SparkEnv: Registering BlockManagerMaster
15/06/10 19:20:48 INFO storage.DiskBlockManager: Created local directory at /var/folders/7l/b9h46wt921b7v7fq3s0tkryw0000gn/T/spark-098dc19c-a26f-4849-abb0-b19cedce066e/blockmgr-d19718a3-b92f-4131-9ee6-7c2d13ff4c0b
15/06/10 19:20:48 INFO storage.MemoryStore: MemoryStore started with capacity 1060.0 MB
15/06/10 19:20:48 INFO spark.HttpFileServer: HTTP File server directory is /var/folders/7l/b9h46wt921b7v7fq3s0tkryw0000gn/T/spark-bc82b915-c8b2-4ec3-b758-2f0e760222b4/httpd-95cae11c-231c-4244-8505-e87448d40f74
15/06/10 19:20:48 INFO spark.HttpServer: Starting HTTP Server
15/06/10 19:20:48 INFO server.Server: jetty-8.y.z-SNAPSHOT
15/06/10 19:20:48 INFO server.AbstractConnector: Started SocketConnector@0.0.0.0:49473
15/06/10 19:20:48 INFO util.Utils: Successfully started service 'HTTP file server' on port 49473.
15/06/10 19:20:48 INFO spark.SparkEnv: Registering OutputCommitCoordinator
15/06/10 19:20:49 INFO server.Server: jetty-8.y.z-SNAPSHOT
15/06/10 19:20:49 INFO server.AbstractConnector: Started SelectChannelConnector@0.0.0.0:4040
15/06/10 19:20:49 INFO util.Utils: Successfully started service 'SparkUI' on port 4040.
15/06/10 19:20:49 INFO ui.SparkUI: Started SparkUI at http://192.168.0.11:4040
15/06/10 19:20:49 INFO spark.SparkContext: Added JAR file:/Users/abhishekchoudhary/.ivy2/jars/spark-csv_2.11.jar at http://192.168.0.11:49473/jars/spark-csv_2.11.jar with timestamp 1433960449229
15/06/10 19:20:49 INFO spark.SparkContext: Added JAR file:/Users/abhishekchoudhary/.ivy2/jars/commons-csv.jar at http://192.168.0.11:49473/jars/commons-csv.jar with timestamp 1433960449231
15/06/10 19:20:49 INFO spark.SparkContext: Added JAR file:/Users/abhishekchoudhary/.ivy2/jars/univocity-parsers.jar at http://192.168.0.11:49473/jars/univocity-parsers.jar with timestamp 1433960449234
15/06/10 19:20:49 INFO util.Utils: Copying /Users/abhishekchoudhary/.ivy2/jars/spark-csv_2.11.jar to /var/folders/7l/b9h46wt921b7v7fq3s0tkryw0000gn/T/spark-a48e6f63-f3c4-474a-80e6-71e4cc82dd91/userFiles-791fdddb-4ed5-4094-a416-daf662e2e342/spark-csv_2.11.jar
15/06/10 19:20:49 INFO spark.SparkContext: Added file file:/Users/abhishekchoudhary/.ivy2/jars/spark-csv_2.11.jar at file:/Users/abhishekchoudhary/.ivy2/jars/spark-csv_2.11.jar with timestamp 1433960449337
15/06/10 19:20:49 INFO util.Utils: Copying /Users/abhishekchoudhary/.ivy2/jars/commons-csv.jar to /var/folders/7l/b9h46wt921b7v7fq3s0tkryw0000gn/T/spark-a48e6f63-f3c4-474a-80e6-71e4cc82dd91/userFiles-791fdddb-4ed5-4094-a416-daf662e2e342/commons-csv.jar
15/06/10 19:20:49 INFO spark.SparkContext: Added file file:/Users/abhishekchoudhary/.ivy2/jars/commons-csv.jar at file:/Users/abhishekchoudhary/.ivy2/jars/commons-csv.jar with timestamp 1433960449351
15/06/10 19:20:49 INFO util.Utils: Copying /Users/abhishekchoudhary/.ivy2/jars/univocity-parsers.jar to /var/folders/7l/b9h46wt921b7v7fq3s0tkryw0000gn/T/spark-a48e6f63-f3c4-474a-80e6-71e4cc82dd91/userFiles-791fdddb-4ed5-4094-a416-daf662e2e342/univocity-parsers.jar
15/06/10 19:20:49 INFO spark.SparkContext: Added file file:/Users/abhishekchoudhary/.ivy2/jars/univocity-parsers.jar at file:/Users/abhishekchoudhary/.ivy2/jars/univocity-parsers.jar with timestamp 1433960449358
15/06/10 19:20:49 INFO executor.Executor: Starting executor ID <driver> on host localhost
15/06/10 19:20:49 INFO util.AkkaUtils: Connecting to HeartbeatReceiver: akka.tcp://sparkDriver@192.168.0.11:49472/user/HeartbeatReceiver
15/06/10 19:20:49 INFO netty.NettyBlockTransferService: Server created on 49474
15/06/10 19:20:49 INFO storage.BlockManagerMaster: Trying to register BlockManager
15/06/10 19:20:49 INFO storage.BlockManagerMasterActor: Registering block manager localhost:49474 with 1060.0 MB RAM, BlockManagerId(<driver>, localhost, 49474)
15/06/10 19:20:49 INFO storage.BlockManagerMaster: Registered BlockManager
15/06/10 19:20:49 INFO scheduler.EventLoggingListener: Logging events to file:///Users/abhishekchoudhary/bigdata/ops/spark/local-1433960449403
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 1.3.1
      /_/

Using Python version 2.7.8 (default, Aug 21 2014 15:21:46)
SparkContext available as sc, HiveContext available as sqlContext.
>>
```

Loading the dataframe works fine-
df_cat = sqlContext.load(source="com.databricks.spark.csv", header="true", path = "/python/avito/Category.tsv", delimiter = '\t')

but When I try to save-
```
df_cat.save("ok.csv","com.databricks.spark.csv")
```
getting the error-
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/abhishekchoudhary/bigdata/cdh5.2.0/spark-1.3.1/python/pyspark/sql/dataframe.py", line 209, in save
    self._jdf.save(source, jmode, joptions)
  File "/Users/abhishekchoudhary/bigdata/cdh5.2.0/spark-1.3.1/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/Users/abhishekchoudhary/bigdata/cdh5.2.0/spark-1.3.1/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError
```

**Comment by abhishek-ch** [comment]
When I checked through the code I found the issue was actually with Spark Configuration.
Spark was expecting some wrong url of Hadoop & that happened because the IP settings change for my server
