### ISSUE TITLE
ClassNotFoundException CsvRelation$$anonfun$buildScan$1 ???

### ISSUE THREAD

**Issue by ophchu** [databricks/spark-csv#83]
I'm trying to use spark-csv both from Zeppelin and from Spark shell and it keeps failing with ``` ClassNotFoundException ```.
I had few missing dependencies but now it looks that it finds all the spark-csv classes beside one...

The command I run in the shell:
``` scala
val df = hc.load("com.databricks.spark.csv", Map("path" -> "my-path", "header" -> "true"))
```
my-path - csv file on s3.

And when:
``` scala
df.count
```
I get the below exception

```
Caused by: java.lang.ClassNotFoundException: com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$1
	at java.lang.ClassLoader.findClass(ClassLoader.java:531)
	at org.apache.spark.util.ParentClassLoader.findClass(ParentClassLoader.scala:26)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at org.apache.spark.util.ParentClassLoader.loadClass(ParentClassLoader.scala:34)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.spark.util.ParentClassLoader.loadClass(ParentClassLoader.scala:30)
	at org.apache.spark.repl.ExecutorClassLoader.findClass(ExecutorClassLoader.scala:64)

```

I'm using spark-csv 1.1.0 with Spark 1.3.1

**Comment by ophchu** [comment]
An update:
When start Spark shell as follows:
```
spark/bin/spark-shell \
--master yarn-client    \
 --num-executors 8    \
 --driver-memory 4g     \
--executor-memory 4g \
--packages com.databricks:spark-csv_2.10:1.0.3
```
Works and I don't get the exception.
So, the questions are:
1. Why it does not work to put the jars on the classpath?
and
2. How can I do it for Zeppelin?

**Comment by jasonfreier** [comment]
I'm also running into this same issue when trying to execute either locally on the name node, or by distributing it out with the yarn client.

**Comment by anabranch** [comment]
same thing when I try and use Spark-CSV on a zeppelin notebook.

**Comment by falaki** [comment]
On number 1, you need to include the dependancies for spark-csv. Basically, spark-csv jar is not a fat jar, so you need to include its dependancies explicitly.

**Comment by nevi-me** [comment]
I presume these are all the dependencies to include when adding the jar to the classPath?

```scala
libraryDependencies ++= Seq(
  "org.apache.commons" % "commons-csv" % "1.1",
  "com.univocity" % "univocity-parsers" % "1.5.1",
  "org.slf4j" % "slf4j-api" % "1.7.5" % "provided",
  "org.scalatest" %% "scalatest" % "2.2.1" % "test",
  "com.novocode" % "junit-interface" % "0.9" % "test"
)

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % testSparkVersion.value % "test" force(),
  "org.apache.spark" %% "spark-sql" % testSparkVersion.value % "test" force(),
  "org.scala-lang" % "scala-library" % scalaVersion.value % "compile"
)
```

Am I correct that I should only include `commons-csv` and `univocity-parsers`? I'm assuming that the rest are for testing.

**Comment by sherman94062** [comment]
Anyone get the Databricks CSV library working successfully with Zeppelin?  I like this library because you can do a lot with just a few lines of code, which fits nicely into the Zeppelin dashboards where you mostly want to show the results of running Scala code.
I'm getting an error which looks similar to the ones that people refer to above:
java.lang.VerifyError: class org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFsStatusRequestProto overrides final method getUnknownFields.()Lcom/google/protobuf/UnknownFieldSet;
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)

**Comment by conker84** [comment]
I have the same issue...

**Comment by pbhati5** [comment]
Is this issue resolved?

**Comment by sherman94062** [comment]
Yes, this has been resolved, your attention to this was much appreciated!

-Mike

**Comment by pbhati5** [comment]
Hi Sherman,

I am using zeppelin on EMR cluster and trying with adding the dependency as %def as shown above but I am still running into ClassNotFound exception. Please let me know what I am missing, it will be really great if you can throw some insights on how it worked for you. Thanks a lot in advance.

**Comment by jasonfreier** [comment]
For zeppelin, make sure you do the following before you run anything else, otherwise you need to either unbind the interpreter, or restart zeppelin:

If you're attempting to do this on Amazon's emr-4.1.0 with their 0.6.0 snapshot of Zeppelin, do not use the %dep as it will error (at least that's what I've been seeing the last few days):

z.load("com.databricks:spark-csv_2.10:1.0.3")

If you get errors, try unbinding the interpreters, save, rebind them, save and try again.  If that still fails, I would recommend stopping the zeppelin daemon, then starting it.  I've seen really strange behavior with using restart.

Somewhat related, when trying to set .mode(SaveMode.Overwrite) with Scala as the language in a cell, it errors out, so not sure if something is happening in the interpreter not actually seeing this as valid syntax for the Scala classes or not, or if something else is causing it...

**Comment by amjadshabani** [comment]
I had just to add 2 properties to the spark interpreter:
spark.driver.extraClassPath	/PATH/TO/commons-csv-1.2.jar,/PATH?TO/spark-csv_2.10-1.0.0.jar 
spark.executor.extraClassPath	/PATH/TO/commons-csv-1.2.jar,/PATH?TO/spark-csv_2.10-1.0.0.jar

And it worked well for me

**Comment by ayee** [comment]
After restarting spark interpreter and load dependency with

%dep
z.load("com.databricks:spark-csv_2.10:1.3.0")

sqlContext.read.load loads dataframe fine.  However, when I got exception when I tried to use a different sql paragraph to do select queries.   Seems like the dependency is not loaded but %sql is just the same interpreter, right?  Weird.

%sql 
select count(*) from crime

java.lang.ClassNotFoundException: com.databricks.spark.csv.CsvRelation$$anonfun$1$$anonfun$2

**Comment by conker84** [comment]
Please try 
```
%dep
z.load("com.databricks:spark-csv_2.11:1.3.0")
```
It worked for me

**Comment by mvherweg** [comment]
I stumbled on this same issue with a notebook i'm working on. This whilst i did never have it before.
What i noticed: doing a sqlc.cacheTable("MY_TABLE") makes the problem go away.

Without sqlc.cacheTable, i get exactly the errors mentioned here. With it, all goes just fine and i can perfectly query in %sql cells.
(note: i load the spark-csv_2.10 dependency through a %dep cell)

**Comment by echarles** [comment]
Zeppelin has recently changed the way dependencies are loaded (no more via %dep, but via a UI in the interpreter settings page).

I was lucky to have a fix for free simply by taking the latest master version (see issue described on https://github.com/datalayer/datalayer-zeppelin/issues/5)

**Comment by mwd102** [comment]
It's a little late, but I just hit upon this problem today. You can still load via %dep (it'll just moan about depreciation) - i noticed references to hive classes not being found in the stack trace. Setting useHiveContext to false under interpreter settings in the UI fixed it for me.

I did not build spark with hive so that probably explains it!

**Comment by ekfliu** [comment]
Is this fixed? i am still getting the error. Already did the interpreter dependencies but it did not fix the issue.
using zeppelin 0.6.2-all version
`java.lang.ClassNotFoundException: com.databricks.spark.csv.CsvRelation$$anonfun$1$$anonfun$2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.InnerClosureFinder$$anon$4.visitMethodInsn(ClosureCleaner.scala:435)
	at org.apache.xbean.asm5.ClassReader.a(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.b(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
	at org.apache.spark.util.ClosureCleaner$.getInnerClosureClasses(ClosureCleaner.scala:84)
	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:187)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:122)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:2055)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1.apply(RDD.scala:707)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1.apply(RDD.scala:706)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.mapPartitions(RDD.scala:706)
	at com.databricks.spark.csv.CsvRelation.tokenRdd(CsvRelation.scala:92)
	at com.databricks.spark.csv.CsvRelation.buildScan(CsvRelation.scala:174)
`

**Comment by eborrelli** [comment]
Hello, apparently if in your Zeppelin notebook you have loaded the jars successfully using %dep and you have defined the Spark submit option '--jars <path/to/jar1>,...,<path/to/jarN>' then, as you can read in https://issues.apache.org/jira/browse/ZEPPELIN-194, the problem happens only when the data frame created using com.databricks.spark.csv is not cached (thanks Sourav!).
