### ISSUE TITLE
Exception While Parsing the Csv

### ISSUE THREAD

**Issue by mkanchwala** [databricks/spark-csv#98]
Hi Guys,
I used the library to parse a Pipe delimited file and threw me this exeception 

2015-07-13 17:39:47,583 ERROR [Example][Executor task launch worker-0|CsvRelation$] 209 apply Exception while parsing line: b0be2d059eb2cdc608f9c345d1ea144e|0006f788fcbd963d836a118e9c9cf30b|5fff401425eafe99b832a80f4751202d|3e0d30e5a4fa79f18617f0b5bb08d8a6|524290|2014|9b1834adbc4c88e383476f61c8138431|53fe6b6b-0000-1000-4047-e1e1e13b31f8|dsf 2014|||54188199-0000-1000-401c-e1e1e13b31f8|1|174|dsf|d6b01d16006840fa842ce45b6be1c888|abeccc327e940bc75101bbc793e01efd|53fe694e-0000-1000-4047-e1e1e13b31f8|1H0S680SEE0766848|b0be2d059eb2cdc608f9c345d1ea144e|b0be2d059eb2cdc608f9c345d1ea144e|cm2|m|cm|l1hr-1||||||bu||||||||||||mm|mm|mm|ew|re|fe|0|8759237e8305facbedfbb066c5fd7517|2a635240a648ae4f64e5c29719ca326c|||b0be2d059eb2cdc608f9c345d1ea144e|b0be2d059eb2cdc608f9c345d1ea144e|1453|1524|0|1524|30.2724818218|-108.251687179|179.473406982421|754017|11587.4534706116|0.0|0.0|\N|\N|\N|\N|0.0|false|76.0331592559814|47.1158632812501|41.65|\N|\N|\N|\N|\N|\N|\N|\N|\N|\N|\N|\N|\N|\N|\N|552a4837c7cdff1e4163a51791a20dbe|2014-09-15|\N|\N|87c35180a648a8b9ca946b7e526bc1fc|2015-06-23|87c35180a648a8b9ca946b7e526bc1fc|87c35180a648a8b9ca946b7e526bc1fc|87c35180a648a8b9ca946b7e526bc1fc|87c35180a648a8b9ca946b7e526bc1fc|87c35180a648a8b9ca946b7e526bc1fc|\N|\N|\N|\N|\N|\N|\N|\N	. 
java.lang.NumberFormatException: For input string: "\N"

Can you guys please let me know for a fix?

I think it might be some error in the CSV parsing cause when I convert Rdd to DF using a Schema it works perfect for me.

**Comment by mkanchwala** [comment]
And when I took it as StringType instead of Double in my schema then it threw : 

java.lang.IllegalArgumentException: For input string: "\N"

**Comment by mkanchwala** [comment]
https://github.com/databricks/spark-csv/issues/46

**Comment by mkanchwala** [comment]
Linking the code used for the Same

**Comment by svravitej** [comment]
I have gotten the same problem.

I am using spark-csv_2.10 : 1.2.0

Seems like the issue #46 gives a work around for lower versions of spark-csv.

Could anyone let me know how to fix this for the version I am using (1.2.0) ?

**Comment by falaki** [comment]
@svravitej would you please include the exception and the (relevant part of) input data that causes the exception?

**Comment by svravitej** [comment]
@falaki 

This is the input I am using (test.csv)

>ABC,\N
>BCD,2
>RAE,79408

Now when I execute the below code and do a df.show I get the below error

```scala
import org.apache.spark.sql.types.{StructType,StructField,StringType,IntegerType,FloatType};
val schema = StructType(Seq(StructField("f1",StringType,true),StructField("f2",IntegerType,true)))
val df = sqlContext.read.format("com.databricks.spark.csv")
.schema(schema)
.load("/user/hadoop/test/test.csv")
```

*Error*
```java
15/08/19 06:31:26 ERROR executor.Executor: Exception in task 0.0 in stage 2.0 (TID 4)
java.lang.NumberFormatException: For input string: "\N"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.lang.Integer.parseInt(Integer.java:527)
        at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229)
        at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
        at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:45)
        at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:119)
        at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:105)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:308)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
        at scala.collection.AbstractIterator.to(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$3.apply(SparkPlan.scala:143)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$3.apply(SparkPlan.scala:143)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
        at org.apache.spark.scheduler.Task.run(Task.scala:70)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by svravitej** [comment]
The castTo method of TypeCast class is unable to resolve '\N' to null.
Due to which we are getting a NumberFormatException.

These lines from TypeCast.scala 
```scala
if (datum == "" && nullable && !castType.isInstanceOf[StringType]){
      null
    }
```
says that null is returned only when the datum is one of the values in the if condition (above).

I think, '\N' should also be evaluated in the if condition to return null or the user should be able to provide the null value (\N or NULL or "NULL") being used in the source csv file.

Please suggest on this.

**Comment by falaki** [comment]
@svravitej based on your use cases, do you think configurable null value resolves this issue? Specifically, I am wondering if I recover https://github.com/databricks/spark-csv/pull/76 it would be enough for such use cases.

**Comment by svravitej** [comment]
Yup, as in #76, providing another option like `.option("null_values", Seq("NULL", "NA", "NaN"))` would help a lot.

**Comment by mkanchwala** [comment]
Any updates on the same?

**Comment by barrybecker4** [comment]
We are seeing this same error when using databricks to parse a CSV.
In our case we want to load a column as an integer column but the data contains some doubles.
Having more null values will not help inour case.

stacktrace:
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 0.0 failed 1 times, most recent failure: Lost task 1.0 in stage 0.0 (TID 1, localhost): 
java.lang.NumberFormatException: For input string: \"1.9\"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)\r\n\tat java.lang.Integer.parseInt(Integer.java:580)\r\n\tat java.lang.Integer.parseInt(Integer.java:615)\r\n\tat scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272)\r\n\tat scala.collection.immutable.StringOps.toInt(StringOps.scala:30)\r\n\tat com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:61)\r\n\tat com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:120)\r\n\tat com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:107)\r\n\tat scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:396)\r\n\tat scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:369)\r\n\tat scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:369)\r\n\tat org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$3$$anon$1.hasNext(InMemoryColumnarTableScan.scala:169)
```

**Comment by Auroratan** [comment]
We are seeing this same error when using databricks to parse a txt.

Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 33322.0 failed 1 times, most recent failure: Lost task 0.0 in stage 33322.0 (TID 925, localhost): ExecutorLostFailure (executor driver exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 159469 ms
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1952)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1025)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:1007)
	at org.apache.spark.graphx.impl.VertexRDDImpl.count(VertexRDDImpl.scala:90)
	at com.dbcs.CommunityUtil.communityInfluence(CommunityUtil.scala:427)
	at com.dbcs.CommunityUtil$$anonfun$execute$1.apply(CommunityUtil.scala:542)
	at com.dbcs.CommunityUtil$$anonfun$execute$1.apply(CommunityUtil.scala:530)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofLong.foreach(ArrayOps.scala:168)
	at com.dbcs.CommunityUtil.execute(CommunityUtil.scala:530)
	at com.dbcs.LouvainHarness.run(LouvainHarness.scala:82)
	at com.dbcs.Main$.main(Main.scala:137)
	at com.dbcs.Main.main(Main.scala)
